### ISSUE TITLE
Rename getTangentAt(), getNormalAt(), getLocationOf() & co.

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#563] opened 2014-11-17 23:11 UTC
I run into this problem:
https://github.com/paperjs/paper.js/issues/553

I have to say I am confused on how paperjs uses the word tangent/handle. I think the confusion comes from some kind of issue, and better documentaion also needs.

As I understand correctly handle is used for Berzier curves, and the length of the handles carries relevant information for it. Okey. But what is the meaning of the tangent vector? Documentation doesn't mention it. As I played with it (code bellow), it seems in some cases tangent = 3*handle if the handle exits, which not intuitive at all. In some other cases it seems just a random value.

The useful return value should be (optionally):
1) always 1 (unit vector)
2) the real length of the tangent vector in time parameter
3) the real length of the tangent vector in length parameter

One more thing, getTangentAt should return undefined if the offset doesn't make sense, e.g.
getTangentAt(5, true)
getTangentAt(-100, false)

Demo snippet:
http://sketch.paperjs.org/#S/lZI7b8IwFIX/ylUWEikkIYIF1KHq1KFqpXQDBhPfPBRjR7ZDixD/vXZeaoYCHWz53pz7+fgoF4eTIzprJ6lQp4XjO6mgtj4RCTXRBTwBxy/4MEf3orQUFb4IJuR6JpHOrt5mJ3fcCgNS1+z8RrQsv81QRpjC9uOwalFyPeDs2V1EkW9WxygIpwzfm6lkFfmw6hUK8yOOiKSr3BbrA28Y82GE/PZFqduPepu/zcTGTDw188onirkxc9Osec3yca92v2czbeQJlaG0kq6yfU143uG73jbaBznqz679bLzGPmjZoGfVYXhXHwWL/w2YqCIPwhBKDaoQDaNwQGg4xazkSB+kzJf9rbdJqeBKMAyYyN2e6Y3BZSbHc4IMU43UXGV5Q37mfz5IJFUbvHLW2/31Bw==

**Comment by lehni** [comment] 2015-08-19 12:31
@Skalkaz if you plot the normals (the rotated tangents), you will quickly see that the `* 3` in the special edge cases is actually right:

http://sketch.paperjs.org/#S/bVLLboNADPwVi0tAkDRq1Asph6qnSn1E6jFwoOAQFPCiZdMeIv69632kROoe0Ho8M17bXAIqewzS4POEqjoGSVCJmuPvUsKxpLpDyOBhvc0pJ8aGUh01QvgDO30NLzmBPiM2PZIaU9hbgM8FBtGS0tj9ep2A/hSJM/04M2zvHium5D/thrWbmfaFNLr02qUXW23hPEYlxQmfRSdkCguJ9SKnKbq2MSocuLGtDTukxvTF7a1s5FKVOJPSmTfOVNh2oSPfGRO2dGZX3EhMqYOQELJLq/O6jUGMfNnq+DFzPGjjOAI3x/YAoeZmLhn9DcRKr09jyOyDp+Qf3qDacfykQk2PZjRV0oz0LmRfdrcsv9HVa0vo18rnIEWf2jqz/SjhMIjZfJa5nXwjEWlhs5Ovxb3EmZmfRib9131JLE/GbwzSfTH9Ag==

The only case that's strange is when the handle of a given segment has zero-length and the tangent is calculated for that segment. The tangent's length should then be 0, but at the moment it is the distance between the handles:

http://sketch.paperjs.org/#S/bVJNb4MwDP0rEZeCoF21ahc6DtNOk/ZRacfCIaMuRQWnCul2qPjvs/PRUWk5oPj5vefY5hKh7CHKo88jmPoQZVGtdhx/Sy0OEncdiEIs1yWWyNBJmgMBCD9iQ9f4UqKgM0DTA5ohF1sH8LmIk2rREHa/XGaCPlXmPT/ODLt7wKox+0+7Yu1qon1BQudBOw9ip628x2C0OsKz6pTOxUzDblbimFzbGAycqI2HtQs7wMb2xe0tXORTtTqjocwbZ2pou9iT76wJW3qzK24lttReaRGzS8tDzKinwU6T4sfC80Sbponwc2z3IiZu4ZPJ30Cc9Po0huw+eErh4Q2YDcdPJiZ6MqEZiRPSu9K97G5ZYaOL1xYhrJXPXqs+d3Um+zHKYyJl80nmdvKNBsCZy46hFveSFnZ+hIz0031pkEfrN0T5thp/AQ==

I think the solution is as mentioned, to introduce a second parameter that controls if the result should be normalized or not. But I'd like to make the normalized result the default (with a vector length of 1), and call the parameter `weighted`. When set to `true`, weighted vectors will be returned that might be of length 0, with their length reflecting curve speed at the given position.

**Comment by lehni** [comment] 2015-08-19 13:21
@Skalkaz, your "one more thing" comment above has long been addressed in a separate issue: #660

**Comment by lehni** [comment] 2015-08-19 13:56
After some more tests, I think it's not so good to add another parameter to all these methods. I'd rather introduce new methods, while the current ones return normalized results:

`getWeightedTangentAt()`, `getWeightedNormalAt()`

**Comment by lehni** [comment] 2015-08-19 15:59
Similarly, I would then rename `CurveLocation#parameter` to `#time`, along with all occurrences. And `Path#split()` would be divided into `Path#splitAt(offset / location)` and `#splitAtTime(index, time)`. The same with `Path#divide()`.

**Comment by puckey** [comment] 2015-08-20 09:00
I really like the idea of adding a description of the type of value that is being passed in the function name.
i.e. path.splitAtTime  is better than path.splitAt(time)

and
```
path.getPointAtOffset(offset);
path.getPointAtParameter(parameter);
```

**Comment by lehni** [comment] 2015-08-20 12:43
Yeah I start feeling that a bit more verbosity is not a bad thing. We could then also separate the AtLocation and AtOffset versions... Just more work for documentation and all : )

We could then deprecate the old `*At(offset, isParameter)` versions, but keep them around for a good while still.

Sounds like the way to go to me. Are there other areas that could benefit from this kind of naming?

And do you prefer `time` over `parameter`? I do, as curve time is what's normally used in mathematical papers for the parameter `t`. On the other hand, `location.parameter` should then probably become `location.curveTime`, as otherwise it can be confusing too, out of context?

**Comment by lehni** [comment] 2015-10-23 17:40
I'm still not sure if `time` or `parameter` is better... Curve-time is what it's called normally, and `parameter` also makes sense, but is very generic; `time` is nicely short.

Another issue will be that we have to rename many existing functions to stay consequent:

    path.getLocationAt(offset); -> path.getLocationAtOffset(100);
    path.getLocationOf(point); -> path.getLocationOfPoint(new Point(100, 200));
    path.getNearestPoint(point); -> path.getNearestPointOfPoint(new Point(100, 200));
    curve.getParameterOf(point); -> curve.getParameterOfPoint(new Point(100, 200));
    curve.getParameterAt(offset); -> curve.getParameterAtOffset(100);

It's a whole lot of changing... And not always for the better. I think the `*Of(point)` versions are actually quite good. I also liked the `*At(offset)` naming, but the problem is that there can also be `*At(time)` which so far was controlled with an optional 2nd parameter `isParameter`, and that was a really bad decision. So maybe all we need is the `*AtOffset()` `*AtTime()` distinction, and we leave the `Of(point)` variants alone? A `Point` object is also more explicit as a passed argument than a numeric value...

**Comment by lehni** [comment] 2016-01-12 18:19
So after a longer skype session with @puckey we have come to a conclusion here:

- `parameter` as property and function argument will be renamed to `curveTime`
- All ambivalent function names that exist in versions will be made explicit, following a simple convention:
  - Only the preposition `At` will be used, `Of` and `Width` are dropped.
  - `CurveTime` is shortened to `Time` when part of function names
  - `getLocation` + `At` + (`Point` / `Offset` / `Time`)

Some examples that make the convention clear:

```js
path.getLocationAtPoint(pt);
curve.getTangentAtOffset(10);
curve.getNormalAtTime(0.5);
curve.getWeightedNormalAtTime(1.0);
var loc = path.getLocationAtOffset(path.length / 4);
console.log(loc.curveTime);
console.log(loc.curveOffset);
console.log(loc.pathOffset); // NOTE: This used to be just loc.offset
```

**Comment by iconexperience** [comment] 2016-01-12 19:05
`getLocationAtPoint()`sounds alright to me, its intuitive and unambigous. But `time` feels a bit strange and it may be confusing if people start using paper in animations. People seeing these functions may misunderstand the meaning of *time*, but with 't' they will see that they have to look up the meaning of t.

**Comment by lehni** [comment] 2016-01-12 19:26
Hmm that's a really good point that we didn't consider... but which one is it then: `getLocationAtParameter(t)` or `getLocationAtT(t)`?

**Comment by iconexperience** [comment] 2016-01-12 19:33
`Parameter` is a very generic term and `curveTime` is quite long. My personal favourite is `t`

**Comment by lehni** [comment] 2016-01-12 19:37
To be fair, `Parameter` and `CurveTime` have the same length. `T` is just a bit brutally short... But perhaps it's fine, since working with curve-time directly is also quite advanced and a bit brutal too.

**Comment by iconexperience** [comment] 2016-01-12 19:51
But it *feels* longer :) You are right, of course, but I feel `getTangentAtParameter()` is uncomfortably long, even when using code completion.

**Comment by lehni** [comment] 2016-01-12 19:52
You should work with [Apple's Cocoa Frameworks](https://github.com/Quotation/LongestCocoa). Now that's long!

**Comment by iconexperience** [comment] 2016-01-12 21:50
There are reasons I keep using Windows :) 

I do not mind longer names if that helps understanding the code. Prefering `t` is probably personal thing, because I learned the term "curve time" long after I got used to the name `t`.

**Comment by lehni** [comment] 2016-01-12 22:05
Mr T, yeah we all go used to him very long time ago!

![t](http://fq540.com/wp-content/uploads/2015/07/mr-t-e1426880574236.jpg)

**Comment by lehni** [comment] 2016-01-15 08:07
So I started working on the renaming, and I've found some inconsistencies that bug me still. I then realized a few things that should be taken into account, too:

- All the functions handling curve-time only exist on `Curve` (and a bit on `CurveLocation`). I consider them to be quite low-level methods that are used internally a lot, and wouldn't necessarily show up a lot in your own paper.js based code (except if you work at rather low level with bezier curves).

- On `Curve`, we have a couple of functions that determine curve-time, and are currently named: `#getParameterAt(offset)`, `#getParameterOf(point)`. On `CurveLocation`, there currently is the `#getParameter()` getter which becomes `curveLocation.parameter`. I don't really see these being named `#getTAtOffset(offset)`, `#getTOfPoin(point)`,  `curveLocation.t`.

- `curveLocation.curveTime` is probably better, and is also working better for me than the current unclear `curveLocation.parameter`

- It is then weird to end up writing code that looks like this: `var res = curve.divideAtT(loc.curveTime);`

I think this line of code can serve as a good test to figure out a good naming scheme.
From working through the existing code and starting the conversion, I came to the following preferred naming:

- We keep the current `get*Of(point)` and `get*At(offset)` (so using `At` / `Of` as the distinction between a point and an offset). This may seem weird, but one can argue that the offset is a plain numeric value at which to get the offset of, while point is an object of which to get something. This works for me, always did, and it's nicely short.

- The origin of the problem has always been the necessity to also have a way to get things at curveTime, on the curve objects. So I propose to use the `get*AtTime(t)` variant for these. This may be a little confusing at first, but it's still better and clearer than all the alternatives discussed here, it feels best when using in actual internal code, and the confusion about time can easily be explained in documentation. Also, it only exists on `Curve`, so not in a place that can easily be confused with animation.

```js
path.getLocationOf(point);
curve.getTangentAt(10);
curve.getNormalAtTime(0.5);
curve.getWeightedNormalAtTime(1.0);
path.divideAt(offset);
var loc = path.getLocationAt(path.length / 4);
console.log(loc.curveTime);
console.log(loc.curveOffset);
console.log(loc.pathOffset); // NOTE: This used to be just loc.offset
```

Can we all live with this? It's also the change that risks the least breakage, and requires the lowest amount of deprecation.

**Comment by lehni** [comment] 2016-02-02 11:00
@iconexperience I hope you can live with these changes:

Curve#getNormalAt(time, true) -> #getNormalAtTime(true)
Curve#divide() -> #divideAt(offset) / #divideAtTime(time)
Curve#split() -> #splitAt(offset) / #splitAtTime(time)
Curve#getParameterAt(offset) -> #getTimeAt(offset)
Curve#getParameterOf(point) -> getTimeOf(point)
Curve#getPointAt(time, true) -> #getPointAtTime(time)
Curve#getTangentAt(time, true) -> #getTangenttTime(time)
Curve#getNormalAt(time, true) -> #getNormalAtTime(time)
Curve#getCurvatureAt(time, true) -> #getCurvatureAtTime(time)
CurveLocation#parameter -> #time
Path#split(offset/location) -> #splitAt(offset/location)

**Closed** 2016-02-02 11:00 UTC
Labels: pri: important, type: api-change

**Comment by lehni** [comment] 2016-02-05 21:30
@iconexperience it looks like the change in 340a1e2a5f1f9523672c82cad8445438211e7178 has broken your boolean test suite (the curve offsetting one). I've changed `runTestCycle()` to use lengths instead of the strange combination of index and parameter that we supported before, but it produces really strange paths and I can't figure out why. Everything else is supposed to be backward compatible, so it would be good to figure out where it goes wrong...
```js
    runTestCycle = function() {
        tP1 = incT(tP1, speedP1);
        tP2 = incT(tP2, speedP2);
        tC1 = incT(tC1, speedC1);
        tC2 = incT(tC2, speedC2);
        var curve = path.firstCurve;
        curve.point1 = pathP1.getPointAt(pathP1.length * tP1);
        curve.point2 = pathP2.getPointAt(pathP2.length * tP2);
        curve.handle1 = pathC1.getPointAt(pathC1.length * tC1).subtract(curve.point2);
        curve.handle2 = pathC2.getPointAt(pathC2.length * tC2).subtract(curve.point1);
        updateCurve();
... 
```

**Comment by iconexperience** [comment] 2016-02-05 22:07
What are all those `pathXX.length`doing there? Shouldn't it be like this?

```
        curve.point1 = pathP1.getPointAt(4 * tP1, true);
        curve.point2 = pathP2.getPointAt(4 * tP2, true);
        curve.handle1 = pathC1.getPointAt(4 * tC1, true).subtract(curve.point2);
        curve.handle2 = pathC2.getPointAt(4 * tC2, true).subtract(curve.point1);        
```

**Comment by iconexperience** [comment] 2016-02-05 22:10
Yes, I can live with those changes. I just noticed that code size will often become even smaller, because we will get rid of a lot of `,true`

**Comment by lehni** [comment] 2016-02-05 22:14
`path.getPointAtTime()` doesn't exist. There is now curve-time over the full length of a path. Before I was faking it by adding `index` and `time` together to something like `path-time` but this doesn't really make sense. It doesn't run consistently across the path. This is why I replaced these calls with `getPointAt(offset)` calls. And those calls are not the issue. The paths still move very similarly to before with this in place. But there is a proper problem happening elsewhere. Look for yourself : )

**Comment by lehni** [comment] 2016-02-06 17:48
@pomax in case you'd like to join the discussion: To explain the context of my [question on Twitter](https://twitter.com/juerglehni/status/695972371912658944) here a bit:

Since in Paper.js we're dealing more with paths than curves, and since it's supposed to be an easy to use, abstracted graphics framework, we decided to work more with offsets and curve-time parameters. This is why we have these methods, on both `curve` and `path` objects:

```js
curve.getPointAt(offset);
curve.getTangentAt(offset);
curve.getNormalAt(offset);
curve.getCurvatureAt(offset);
```

We also have a `CurveLocation` object which describes the location on a curve / path, and is for example returned by hit-testing, intersection code, and also these methods, again on curve and path:
```js
curve.getLocationAt(offset);
curve.getLocationOf(point);
```
Any of the methods above that receive a offset can also receive a location object.
We also have these methods, again on path and curve:
```js
path.divideAt(offset); // inserts a new segment into the path at the given offset
path.splitAt(offset); // splits the path into two paths at the given offest
```
But next to these higher level methods, we also need to give access to methods that handle curve-time directly. Those are also the ones used the most internally. At the moment, these were renamed to:
```js
curve.getPointAtTime(t);
curve.getTimeAt(offset);
curve.getTimeOf(point);
````
etc.

And before we roll these out in the next release, I want to make sure we found the best possible naming for them. I'm not convinced yet but couldn't come up with a better name, hence the question on Twitter.

**Comment by Pomax** [comment] 2016-02-06 18:10
They seem sensible given the rest of the API described; the only thing that might get tricky is that `getTimeOf` can yield more than one result (certainly for paths, but even for single segments that self-intersect), whereas its name implies a single value. It might be behaviourally better to use `getTimesFor(point)` and then keep the other two the same (offsets can only ever have one associated time).

**Comment by lehni** [comment] 2016-02-06 18:14
We're a bit lazy there and simply return the first solution if there are multiples. This is mainly use internally anyway, e.g. when intersecting two curves that are actually linear: There we use the much simpler line intersection code and then determine the curve-time parameter in hindsight using this function.

**Comment by Pomax** [comment] 2016-02-06 18:16
A little iffy to me as outside party, but as long as it's well documented I guess that shouldn't be a real problem =)

**Comment by lehni** [comment] 2016-02-06 18:20
Yeah I know : ) Oh well! Hey, thanks so much for the feedback. I couldn't tell anymore if the naming was decent or a bit crazy... Been too close to it.

**Comment by Pomax** [comment] 2016-02-06 18:37
heh. It reminds me of the SVG API (`getPointAtLength`) which is probably a good thing.

**Comment by lehni** [comment] 2016-02-07 10:06
@Pomax oh wow, I wasn't aware of that command. Funny that we ended up with almost the same naming!

**Comment by iconexperience** [comment] 2016-02-09 11:49
@lehni I just tried my test suite with the latest build and everything works well (except for glitch 2511). All I did was replace these line:

```
runTestCycle = function() {
        tP1 = incT(tP1, speedP1);
        tP2 = incT(tP2, speedP2);
        tC1 = incT(tC1, speedC1);
        tC2 = incT(tC2, speedC2);
        var curve = path.firstCurve;
        curve.point1 = pathP1.getPointAt(pathP1.length * tP1);
        curve.point2 = pathP2.getPointAt(pathP2.length * tP2);
        curve.handle1 = pathC1.getPointAt(pathC1.length * tC1).subtract(curve.point2);
        curve.handle2 = pathC2.getPointAt(pathC2.length * tC2).subtract(curve.point1);
        updateCurve();
```

**Comment by lehni** [comment] 2016-02-09 11:52
Hmm what have I done! Could you perhaps share your code again with me? By email?
