### ISSUE TITLE
Using paper.js with react-native

### ISSUE THREAD

**Issue by clozr** [paperjs/paper.js#1268] opened 2017-03-04 16:11 UTC
I am trying to use paper.js with react-native but it fails in getCanvas. Any idea how I may be able to work around it.

**Comment by lehni** [comment] 2017-03-04 22:10
I've never used react-native. Perhaps you could provide a small test-case for reproduction, or describe the steps required to set things up?

**Comment by clozr** [comment] 2017-03-05 20:14
I set up a git repository for you. You can clone this.
git clone https://github.com/clozr/react-native-paperjs-example.
You will need IOS or Android tools to build and launch the project.

**Comment by lehni** [comment] 2017-03-09 11:44
Ouff... Thats a bit much for me. Are you sure that canvas works in react native? A bit of googling brings this up, but that looks unfinished: 

https://github.com/iddan/react-native-canvas

**Comment by gentlefox** [comment] 2017-03-10 06:25
[React Canvas](https://github.com/Flipboard/react-canvas) by Flipboard is maintained (unlike react-native-canvas) and dedicated to mobile performance. It does appear to be predominantly aimed at mobile web instead of native, but worth a look.

**Comment by lehni** [comment] 2017-03-10 09:53
I think those are two separate things though?

**Comment by clozr** [comment] 2017-03-10 16:47
Lehni,
Is there a way around that we don't need canvas to use paperjs. The way react native will work is you will need to get the drawing spec and use [react-native-svg](https://github.com/react-native-community/react-native-svg) to render the component. You may be able to use node-canvas perhaps with rn-nodify. I haven't tried that yet.

**Comment by lehni** [comment] 2017-03-10 16:58
There is no SVG backend at the moment, Canvas is the requirement if you want to actually draw something. You can also use the library as you would in a worker to just do vector graphics processing, of course, but that's not the point here.

**Comment by lehni** [comment] 2017-03-10 17:48
For displaying content, it looks like fallback to WebView is the only possibility right now. That's also what [react-native-canvas](https://github.com/iddan/react-native-canvas) is doing internally...

[More info here](https://discuss.reactjs.org/t/react-native-canvas/3151)

**Comment by clozr** [comment] 2017-03-10 18:14
I agree...how about using paperjs to do vector processing e.g path optimization etc. so that we can use part of the paperjs awesomeness in conjunction with react-native-svg? react-native js doesn't have web-worker.

**Comment by lehni** [comment] 2017-03-10 19:44
You can use `exportSVG()` to export static SVG and display that. Anything beyond that means we finally need to build that SVG backend that we never find time for :)

**Comment by lehni** [comment] 2017-03-22 23:00
I am going to close this issue as there is no easy fix for this scenario at the moment until react-native has a proper, native canvas element.

**Closed by lehni** 2017-03-22 23:00 UTC

**Comment by flyingbuddha** [comment] 2017-11-16 07:52
@clozr Did you get any further with this problem? I'd really like to use Paper.js inside a RN project too.

**Comment by FlashTang** [comment] 2021-01-03 19:25
> @clozr Did you get any further with this problem? I'd really like to use Paper.js inside a RN project too.

Did you find a way to use  Paper.js in RN ?
