### ISSUE TITLE
path.angle seems to not calculate the right angle

### ISSUE THREAD

**Issue by celevra** [paperjs/paper.js#1158] opened 2016-09-08 16:46 UTC
Hi,

i want to draw a point move the angle by 72 degrees and write another point. I want to do it 4 times so that i make one round with 5 points
but it seems that the angles are not calculated right
this it the code i'm using to test the calculation:

```
paper.install(window);
var tool1

var middle = {}
var pWidth
var pHeight

window.onload = function() {
    paper.setup('paper')
    pWidth = $('#paper').width()
    pHeight = $('#paper').height()
    middle.x = pWidth/2
    middle.y = pHeight/2
}

tool1 = new Tool();
tool1.onMouseDown = function(e) {
   //this is my first point
    var x = e.point.x;
    var y = e.point.y;

    //now add 72 degrees 4 times so that we get one round
    for (var i = 1; i <= 4; i++) {
        var point1 = new Point(x,y)
        var point2 = new Point(middle.x,middle.y)
        vector = point2.subtract(point1)

        vector.angle += 72
        console.log(i,vector.angle)
    }
}
```

if you click somewhere in the canvas you get this console output of the calculated angles:
```
1 -162.9834944270716
2 89.01650557292841
3 -18.98349442707159
4 -126.98349442707156
```

if i do it with 3 rounds and 90degress everything seems to work as expected:
```
1 160.99129287936148
2 70.99129287936148
3 -19.008707120638533
```

could it be that there is an failure in the calculation of the angle?

regads

celevra

**Comment by lineto** [comment] 2016-09-08 16:59
I tried your script, and it prints 4 times the same value, which makes sense since you're recreating `point1` and `point2` each time. Are you sure your version produces these values at your end?

[Here a simplified sketch](http://sketch.paperjs.org/#S/VVHBasMwDP0VkVNKuoSNwqBdb7vutOOyg2srqWkjBVtJGKX/PsVZYAWBkJ783pN8y8h0mO2zzwuKPWfbzLKb69EE6LxzV4QjjB6n0iIJhkNNNTUDWfFMwPTBQ8R3nijHDdxqAoCqkrOPoNH9QONDFOjZkyRw5u1FObFMzUPqpvaIVjgotOiWcThJMFbyXjZ/Y1VFPIFxDl5fwGEbECPsQHynOTLI2QhMCC2KekMIPJBbnjZKnc8yXhWeD5rejrDTXBSrcVid9AHHee1kqLRXpcpXC2lmAQy1ep7iqGb+gZYpstq/cpv77cPsYwVPSWgpVvp7TRr6D6eA5pJOFLP91/f9Fw==) that does what I think you'd like to do, and the changes in values seem correct. Note that the angle wraps around +- 180 degrees.

**Comment by lehni** [comment] 2016-09-08 17:01
I tried your script, and it prints 4 times the same value, which makes sense since you're recreating `point1` and `point2` in each iteration. Are you sure your version produces these values at your end?

[Here a simplified sketch](http://sketch.paperjs.org/#S/VVHBasMwDP0VkVNKuoSNwqBdb7vutOOyg2srqWkjBVtJGKX/PsVZYAWBkJ783pN8y8h0mO2zzwuKPWfbzLKb69EE6LxzV4QjjB6n0iIJhkNNNTUDWfFMwPTBQ8R3nijHDdxqAoCqkrOPoNH9QONDFOjZkyRw5u1FObFMzUPqpvaIVjgotOiWcThJMFbyXjZ/Y1VFPIFxDl5fwGEbECPsQHynOTLI2QhMCC2KekMIPJBbnjZKnc8yXhWeD5rejrDTXBSrcVid9AHHee1kqLRXpcpXC2lmAQy1ep7iqGb+gZYpstq/cpv77cPsYwVPSWgpVvp7TRr6D6eA5pJOFLP91/f9Fw==) that does what I think you'd like to do, and the changes in values seem correct. Note that the angle wraps around +- 180 degrees.

Example Output:

```
1 -160.22431569404534 -288
2 -88.22431569404534 72
3 -16.224315694045348 72
4 55.775684305954655 72
```

**Comment by celevra** [comment] 2016-09-08 17:14
thanks for the fast answer

your script is exactly what i was trying to explain, sorry that mine isn't working.

in your output is a -288 that seems like the error to me
i have added a few lines to draw lines on the canvas, please try to draw a line from the upper left corner to the middle and you will see that there are not equal "pizza slices"

**Comment by lehni** [comment] 2016-09-08 22:21
-288 is not the error, it's the mentioned wrap around. Please note that internally, `Point` does not store `angle` and `length`, it stores `x` and `y` coordinates, so you may see other strange things happening, like float conversion imprecisions. Let's look at this example:

```js
var vector = new Point({ angle: 150, length: 100 });
console.log(vector.angle);
vector.angle += 50;
console.log(vector.angle);
```
Output:
```js
150.00000000000003
-159.99999999999997
```

So two things are happening here: 150 becomes 150.00000000000003, and adding 50 to it results in 200, which is > 180, so it really becomes 200 - 360 = -160, but again it's not exactly that value, due to conversion to and from x / y.

**Comment by lehni** [comment] 2016-09-08 22:23
For your use case, I'd probably keep `angle` in a separate variable that you increase, and assign its result to `vector`. This is not really a bug, and I don't see an easy fix / improvement, so will close this issue.

**Closed by lehni** 2016-09-08 22:23 UTC

**Comment by celevra** [comment] 2016-09-09 13:26
hm, my usecase is to move x y by for example 72degrees, i don't see how i can do this with storing the angle in a extra variable, i don't need the result from path.angle +=72 i need the result of path.x after i've added 72degrees to the angle and that result seems to be wrong.
can you guide me in the right direction with an example with storing the angle in a extra variable, i don't get it, sorry

thank you again for your help and time

**Comment by celevra** [comment] 2016-09-09 14:28
here i've got a new example, if i try to draw a line starting from the middle 100px tall and move it 72degree, also if i calculate everytime a new vector. 
isn't that what rotating vector is for? [doc](http://paperjs.org/tutorials/geometry/vector-geometry/#rotating-vectors)
[sketch](http://sketch.paperjs.org/#S/hVPLbsIwEPwVKxeIoIGiSpVIOfUHkHroATgYZwlWEhvZJiRC/HvXj5SkpWpy8GNmd8bj5BoJWkG0jD4KMOwYTSMmM7uuqSIVz7ISyIrUHC4JA2FApVthoRM1x95UI+l6ww372g1cC7iQNU7Hsd9KtFGygHdZSoXwaF+eYZQOsE+eudLntOuT0Cwbex+x27SK2HktuTCdiJ0HUtJMg+2kfVrM53GvTVf27aeS0tr77lsDM85b6KDPe6MoM/3KrTggZWzp3DnF4W1FXnCcTGJytQyCz2yGkoQ6gy4QbagyXOSEC2KOEDQ82UW44btBaukQ+x0fZcXoMamf4wD+maZ3WskanCcqcrzvg5KVW54U1FyeNfFdyb4lr4sMcgWgfa1PLPF1kxXCQZFJoSVGWMp8zKeB19dktGTnkhov7FKyCXu4ud9BMwkajYfaO9R2UHtvqykexafuweDzr6+mmbZx/yj/XX5QAfPI9iBm2xnPe9sK/Kn2CmjhmDpabna3Lw==)

you can comment line 35 and 36

**Comment by lehni** [comment] 2016-09-10 14:49
Alright, I see what's going on now. That's what providing a function illustration of the problem is always crucial. Just describing it in words will not help, usually.

First I've simplified your sketch to only use vector algebraic statements instead of separate x / y calculations, for clarity. I also inlined all graphics related things into object literal constructors, and I've used different colors to visualize the sequence of results:

[Sketch 1](http://sketch.paperjs.org/#S/jVLLTsMwEPyVVS4pSigBISGl9MQPIHHgkOTg2ktqxbEr2w0g1H9n/UBQwYFc/JidnfFOPgrNZiza4mlCz/dFXXAjwnlhFmYphELYwiLxdc1Re7SbXvf66ooJAQw0vsKB+T04z6yXegSpwe8xM0PhzCakyuumObyBZ0qBkhrheOh1kBDoPAlkpUvomhpummbYJDg230adR9quPnoN9DkcZ3LjWugSs46NhjrD3poJH4wytoVypxifyjPoWQq/b+G616eL/CDOFD8q5jH6X5B7Y5OHtP9pMmhF2pdFR2gXPL9Q4SrcSrppNrTcwy0tVXUB2TuNxCxJhemR+r1YM8fjweIizdFlk7B7h7sbgaNFdImbrKwTr9oSvMkASfLw3mCktCjKGspA1GGzU0cMq7HExHLo5JB53GhnFK6VGVeJX0HZUm1SSsNJrs8HFJM3Uvtv/fMoq9ziRweH/i9uHCBZ+iPnf2T9K+/4jF/gd+LhLqZ+6jX97juLbIpuXNF2w+kT)

Now you can see that the distribution appears strange at first. But if you would flip the black line down, it would actually be correct. And that's where the real reason lies:

```js
var vector = middle - dest;
```

In order to calculate the vector from `middle` to `dest`, you need to subtract `middle` from `dest`, not the other way round, or you'd get the reversed vector. Reverse it, and it works as expected:

```js
var vector = dest - middle;
```

[Sketch 2](http://sketch.paperjs.org/#S/jZLLTsMwEEV/ZZRNihJKQEhIKV3xA0gsWCRZuPaQWnHsynYDCPXfGT8QVLAgGz9m7tzjmXwUms1YtMXThJ7vi7rgRoTzwizMUgiFsIVF4uuao/ZoN73u9dUVEwIYaHyFA/N7cJ5ZL/UIUoPfY1aGxJlNSJnXTXN4A8+UAiU1wvHQ62Ah0HkyyE6X0DU13DTNsEnhWHwbfR5pu/roNdDncJyJxrXQJWUdCw11DntrJnwwytgWyp1ifCrPQs9S+H0L170+XeQHcab4UTGPkX9B7o1NDGlPFJH1MrNG2Reio2gXmF8ocRVuJd00G1ru4ZaWqrqAzE4tMUtyYXqkR79YM8fjweIizdFlSNi9w92NwNEiuqRNKOukq7YU3uQAWfLw3gBSWhRlDWUQ6rDZqSOG1VhSYjl0csg6brQzCtfKjKukr6BsKTc5peYk6vMGxckbqf23//koq1ziRwWH/i9tbCAh/THnf8z617zjM34Fvyce7uLUT72m331nkU2RxhVtN5w+AQ==)

**Comment by lehni** [comment] 2016-09-10 14:51
Please note that when working with JavaScript directly without PaperScript, you'd have to write `dest.subtract(middle)` etc, since operator overloading will not work there.

**Comment by celevra** [comment] 2016-09-10 14:56
omg, you are right, i've calculated the angle from the middle point not from the end point!
thank you very much for your help and time! This problem was driving me nuts!

**Comment by lehni** [comment] 2016-09-14 20:54
No problem. Glad it wasn't a bug :)
