### ISSUE TITLE
projectToView return different values

### ISSUE THREAD

**Issue by sevaTechoPark** [paperjs/paper.js#1442] opened 2018-02-10 11:28 UTC
try to feed any point twice, for example this
**Point {x: 14.573041200000041, y: 11.047296549999977}**
for the first time projectToView return
**Point {x: 711.4704004999991, y: 695.2117449999987}**
for the second time
**Point {x: 711.4577746297396, y: 694.7684687454869}**

the bug is saved on all browsers and computers
"paper": "0.11.4"

**Comment by lehni** [comment] 2018-02-10 20:56
I can't reproduce this:

http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUCvIz80oUbBXyUssVAkBsjeoKKwVDEz1Tc2MDE0MjAzAwMdRRqAQKG+oZmJgbWZqZmliCgLl5rWZMXnJ+XnF+TqpeTn66RllmarleQVF+VmpySUh+GJCnAbZBkwR1QAcmFaUmZoMFipWsomNrAQ==

Without a reproduction test-case I can't do anything and will have to close this issue.

**Comment by sevaTechoPark** [comment] 2018-02-11 09:27
This sandbox return point. not projectToView. I don not how there reproduce this case

**Comment by lehni** [comment] 2018-02-11 09:40
I don't understand what you mean.  `projectToView()` always takes a point and returns one.

**Comment by lehni** [comment] 2018-02-21 13:07
I will have to close this issue in absence of a reproduction test case.

**Comment by sasensi** [comment] 2018-10-09 06:56
I close this issue as there were finally no reproduction case.

**Closed by sasensi** 2018-10-09 06:56 UTC
