### ISSUE TITLE
Some blendModes do not work, or reposition the object the center of the canvas, with an apparent position of [0, 0]

### ISSUE THREAD

**Issue by SkepticaLee** [paperjs/paper.js#1479] opened 2018-05-25 18:29 UTC
Using the example in the documentation for Rasters:

var url = 'http://assets.paperjs.org/images/marilyn.jpg';
raster = new Raster(url);

// If you create a Raster using a url, you can use the onLoad
// handler to do something once it is loaded:
raster.onLoad = function() {
    console.log('The image has loaded.');
    raster.blendMode = "add";
};

This causes the image to disappear and a message in red appears on the console:

SecurityError: The operation is insecure.

Blend modes that appear to do this are e.g.:
add, subtract, negation, average, pin-light

Blend modes that work as expected are e.g:

normal, screen, multiply, overlay, soft-light, hard-light, color-burn, color-dodge,

In my applications the image is translated into the center of the canvas, and its position is read out to be [0, 0].

Is this a bug?

**Comment by SkepticaLee** [comment] 2018-09-02 09:12
The security error refers to line 13715 of paperjs version 0.11.5, which is the line:

var dstData = dstContext.getImageData(offset.x, offset.y,
					srcCanvas.width, srcCanvas.height)

This would normally be triggered by a cross origin, which is not the case here.

**Comment by sasensi** [comment] 2018-10-02 13:43
Hi, as you have guessed, it is a CORS issue.

Problematic modes are those which are not natively supported by your browser and thus need access to the image data. And this image data access is by default prevented by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image).
Here is another [issue](https://stackoverflow.com/a/52439291/7615922) related to this problem.
To enable CORS access from `Paper.js`, you need to set the [crossOrigin](http://paperjs.org/reference/raster/#crossorigin) property on your `Raster` instance.

    new Raster({
        crossOrigin: 'anonymous',
        source: 'http://assets.paperjs.org/images/marilyn.jpg'
    });

Here is a [Sketch](http://sketch.paperjs.org/#S/XVTBjpswEP0VKxeShiVs1UgVaU89VWrVattbNofBNmBibDS2sxut8u+1zUKglhCemec37xmbt5WCjq+K1Z8zt7RZpSuqWYgrp6gVWhEmTC/h+r2Dmq97LZRNSSm5Yj89cEPenvFZET8UfyFPYCzH9ZQLg6I25heKWqiCJKC0unbamSSdg4x2SLmvN9b2xW4HxnBrsh56jq3JNNY7EQSYXQco5FVlbV8vKXptRBBckEHkgp6CFKouSJ593C8qWv3QwAoy2l17R7YRJpsskq93u4fbuPa2OcyN/w4t//JXu/QelbwLIltyzNPP+WnRn2plecBMPRbl1hkrKkFhcJZQj+W4NF4JKb9pqdHXSwn0nPwnMooOT1QKtsmeOLWgasnvcnFMFeQi+EtWaqeYmRrNm2j0QB67vHcIzwWQdF6/8Rt2HJclSmMHMklJ0jlpRS+vYW4ocq7CTF84+tMVk7qyD1LUjb37SxpANia9/aDggWnm209h6TBSMcDzQBrxYTrRMFFVHLmicR1/pdIZv6MhaFzMGbAO4zZHBtcJFQ7UdUYS24UqMBaXuNIi0KgMvA8YVPVC3RUrXg+kgeV0GDcK9UvYp09TwnO7ToXcPuYqjWQdCsKn8oN/fRkxPthuZxdvgrYDtPXQwO9nC1wY40fyyPitji35MPXeEnE6zNGLqz8d8/VjngesX/m4z1MyhO0QbtJIfL8dt8UJ9P+XEjmc440wq+J4uv0D) showing all blend modes in action.

**Comment by SkepticaLee** [comment] 2018-10-03 08:28
I thought it was a CORS issue as well, but then the images on http://paperjs.org/reference/raster/#raster shouldn't show at all to begin with. It is only when the blendMode is manipulated tha tth einmage disappears. Try this in the box on that page:

```
var raster = new Raster({
    crossOrigin: 'anonymous',
    source: 'http://assets.paperjs.org/images/marilyn.jpg',
    position: view.center
});

raster.scale(0.5);
raster.rotate(10);
raster.blendMode = 'negation';
```

BTW in your sketch you should have 5 rows, not 4, to show the "negate" effect.

**Comment by sasensi** [comment] 2018-10-03 09:00
Sorry about the missing blend mode in the sketch :)

Your seing this issue on http://paperjs.org/reference/raster/#raster because when you load the page, the image is drawn in the canvas without CORS attribute and that result in a [tainted](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image) canvas.
> As soon as you draw into a canvas any data that was loaded from another origin without CORS approval, the canvas becomes tainted. A tainted canvas is one which is no longer considered secure, and any attempts to retrieve image data back from the canvas will cause an exception to be thrown.

So when you change the code snippet and click the run button, despite you use CORS attribute, the canvas is still tainted and this produces an error.
This can be reproduced in [Sketch](http://sketch.paperjs.org/#S/pZHBTsMwEER/xfIlrQhJxNH8AhUSHNsets6Sum12La9DVVX5d2wJlx7gxDt5pB3vjH3VBCNqo9+PGO1e19pynzXhWb2BRAyL6yZsSCWEp2DRqGofozdtCyIYpfHgMRyk4TC0boQBpR0huNOFmoMfqrrYPYuLjsmoT4fnxiKl29WDWj8+dV2tuu1tkumFoTfqYyKbHYuluoXI/BauYAOLvAY3uLSoAmK6jDzJT4zCP9sU/myVS911KuxOSP0qPXLaTDhA9lb3Q/Pyucg5H751+ppdQDh6dhRFm/V2/gI=) by loading two images consecutively. First without, then with CORS attribute.

I'm not sure if we can / must do something about that.
Is it user responsability to never load an image in the canvas without taking care of CORS if he wants to manipulate image data later ?
@lehni & @sapics, what do you think ?

**Comment by SkepticaLee** [comment] 2018-10-03 09:02
Well, you should do something about it, otherwise it looks like the page is broken and/or paperjs doesn't work...

**Comment by SkepticaLee** [comment] 2018-10-03 09:40
Besides, if you leave out the crossOrigin property in your sketch, the modes "normal", "hard-light", "difference" and "color" still work, even though the latter three are not native blend modes. Something else is going on here.

**Comment by SkepticaLee** [comment] 2018-10-03 10:11
Try this in the sketch to see what happens with the position, despite CORS being set:

```
function displayImage(point, blendMode) {
    new Raster({
        source: 'http://assets.paperjs.org/images/marilyn.jpg',
        crossOrigin: 'anonymous',
        position: point,
        scaling: 0.25,
        onLoad: function() {this.blendMode = blendMode;}
    });
    new PointText({
        point: point + [0,80],
        content: blendMode,
        justification: 'center',
        fillColor: 'black'
    });
}

new Path.Rectangle({
    rectangle: view.bounds,
    fillColor: 'orange'
});

var modes = [
    'normal', 'multiply', 'screen', 'overlay', 'soft-light',
    'hard-light', 'color-dodge', 'color-burn', 'darken', 'lighten',
    'difference', 'exclusion', 'hue', 'saturation', 'luminosity',
    'color', 'add', 'subtract', 'average', 'pin-light', 'negation'
];
for (var i = 0; i < 25; i++) displayImage(new Point(100 + (i % 6) * 150, 100 + Math.floor (i / 6) * (i % 6) * 135), modes[i]);
```

**Comment by sasensi** [comment] 2018-10-03 10:40
You are right, I haven't realized that the error stopped the script execution.
So the least we can do is catch this error and provide an help message.
Here is an [updated Sketch](http://sketch.paperjs.org/#S/ZVTBjpswEP0VC6mCNCxJK6WqSKtK7amHVavt3rI5GDOAE2OjsZ3ddJV/r20WAikSif3med680ZjXSNIWojz6cwTDmiiNmCr9vrKSGa4kKbnuBD3/bGkNSae4NCkpBMjy3hEX5PUJnyRxj4Rn8kC1AUxGzD8Mlda/kNdc5iSmUslzq6yO0ylJK4sMXLwxpstXK6o1GJ11tAM86ExhveK+AL1qKXJxltmhq+cpOqW5LzgnfZGz9IwKLuucrLOPm1lkdJJfl0P8sthOzf32aR/hxcz9BbU3UbIku3VKPq/3MxGmpAFPGiUcMQnmMm27TqHJJDX8BN8Hgt6N3P00lX++kZgkPX8RE9e0eDGTO1hteMUZ7dsRM6cNOO9WxYX4oYRCFy8EZcf4xvXF//g3WKemyR6AGSprAVf/OEA5OXF4zgplZalHoamIQkeEoPKm4N8TRdJ6u+Qr2Q3HYqmwpSJOSdxaYXgnzn6tGQJIv1InQDeSAVSVuRO8bszVX9xQLAfQ2fcV3JWqdPLjtrAYUpUUj33SwPfLMU3JqwoQJAvn4IUJq11H/aaxAdPUWAxtDhlsy6WfwvMkSZDzUVqW4YgtDFIWKqPOB+2r6rj8z4aEus/tkf126JfLaFvpO7YZMc3/ggM+fFoHqFJIEo9zB6637u9L3+bMDVVtGocsl5O7O7vj46wnIet7d2k2fl45eTdoLxzqgymZUe79mFRCKXTk1S15kfY17Pj+ZsTcV6dAoMdwh3SU7/aXfw==) precising which mode is natively supported.

**Comment by lehni** [comment] 2018-10-05 15:40
@sasensi do these errors show up in the console? If so, what do they say? And do we really need to catch them and print a message?

**Comment by lehni** [comment] 2018-10-13 12:50
@sasensi I think in that case we shouldn't add special code to emit warnings... We can just direct questions to this issue instead? Are you OK with closing this MR without merging?

**Comment by sasensi** [comment] 2018-10-13 13:18
@lehni if you think that's the right way to go, it's fine for me.
I closed the PR.

**Comment by sasensi** [comment] 2018-11-23 11:11
I close this issue because the cause of the problem can't be fixed in the library.
As a final note and as mentioned earlier in this discussion, any image loaded from an external source should be loaded with the `crossOrigin` attribute set, in order to avoid tainted canvas errors.
```javascript
var raster = new Raster({
    crossOrigin: 'anonymous',
    source: 'http://assets.paperjs.org/images/marilyn.jpg'
});
```

**Closed by sasensi** 2018-11-23 11:11 UTC
Labels: type: bug
