### ISSUE TITLE
Error trying to build server side rendering angular 9

### ISSUE THREAD

**Issue by ozaytunctan** [paperjs/paper.js#1912] opened 2021-03-25 14:38 UTC
I got the same error and a few more when using paper 0.12.0 . The server folder is not generated when the build part of the distribution kit for server rendering is build.
The commands that I ran:
```
ng add @ nguniversal / express-engine
npm run build: ssr && npm run serve: ssr
````

# Exceptions and warnings:
```
WARNING in ./node_modules/paper/dist/node/extend.js 29:8-15
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/paper/dist/node/extend.js 48:32-39
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/paper/dist/node/canvas.js
Module not found: Error: Can't resolve 'canvas' in '/home/ubuntudev/workspace/dev/repos/client/btxclient/node_modules/paper/dist/node'

ERROR in ./node_modules/jsdom/lib/jsdom/utils.js
Module not found: Error: Can't resolve 'canvas' in '/home/ubuntudev/workspace/dev/repos/client/btxclient/node_modules/jsdom/lib/jsdom'
 ```

**Comment by sapics** [comment] 2021-03-26 07:06
@ozaytunctan
This looks duplicate of #1904. Please make one issue for one problem to avoid confusion.
If you have additional information, please add comment to the existing issue.
I copy the information to #1904, thus, I close this issue as duplicate.

I think the problem is how to run paperjs on angular, so, it looks better to make a question to them.
・https://stackoverflow.com/questions/tagged/paperjs
・https://groups.google.com/group/paperjs

**Closed by sapics** 2021-03-26 07:06 UTC
