### ISSUE TITLE
Path boolean operations failed for Bezier paths

### ISSUE THREAD

**Issue by ghenania** [paperjs/paper.js#1074] opened 2016-06-11 18:25 UTC
[Here](http://sketch.paperjs.org/#S/lZRbb9MwFMe/ylFf0kmJZzt2bA/xMLYgVWxjajsJxHhIU7NWC8mUy8ZFfHdO7gkPCFSp8vmf2+8cJ/m5SKOvdnG22DzaMj4s3EWc7Wv7Pn2OcniKygOD15DaF7jF89K59oUhRgdCuDT2mOFoUMVdCt7oYVIRSrmUU7E9+VzF1PUloTzQCrgmvvGZ7wY+ERya//Yc9zFYupW9Pri32zjqeoz7hArGBDBKCaMcC3ocRSawH7SnmmEU/6f8QDuEdE7wpqE/nJNX49r4X9Y26d1VGHp70xX826KkIVyaQGI1xjQJTF2ZcyIVmsCkxsZCYCYlvpJaxFwSKaTULi7DKGlwYkkCpZSs0wKtJWhDkJUp3ArRQskgrmMDIw0qdToXUMcaFmgcv0uHPtr1+gJxPRBnVDHXQ1CcoH4qmMS5DK1vxAiiON4d5gpJlGZ0IrYrvU+b55B8OSbJRZZkOa7WecitTZ1XrY/PfVkepQ/WaVJPT2F1sw3Xm/BiC6sNhNe324+wLPPKQtwkFIesSvaws7BLovjxpL3DY1ravLBxiQXb9oOybFrWZIM079/UcWb+Io4Su6REztNKJC2SqLRLJim+N7Sdt8He3L3ZbNfniP32fHUVXsLymMJ3myTZS8dYVLsCK0wYUWmEEXGImSO2dZxZwIxxlEdGD18vV9AOEhHDDxdXd5chHAt4/w4awF1S2Q7PfouTam8HuM4e2Trhz+VVzdX1zhlVL45Mek50d7Pahv3CXo7lAeri68om4Nhnm2b7vdNw5nbfYVbpsRwhG2tEbMw5IGY6M8+6Sur8of7gnKG30gjuT8nbH35+d7mNHp8yfEKKxdmnz79+Aw==) is a simple case where `Path` boolean operations have weird result

```
var path1 = new Path('M349.98644,0c-192.98072,0 -349.98644,157.00255 -349.98644,349.98327c0,35.02687 28.39313,63.42 63.42,63.42c35.02687,0 63.42,-28.39313 63.42,-63.42c0,-123.04114 100.10213,-223.14327 223.14644,-223.14327c35.02687,0 63.42,-28.39313 63.42,-63.42c0,-35.02687 -28.39313,-63.42 -63.42,-63.42z');
var path2 = new Path('M349.98644,0c-35.02687,0 -63.42,28.39313 -63.42,63.42c0,35.02687 28.39313,63.42 63.42,63.42c59.25965,0 118.69687,22.57118 158.98443,60.37584c25.54558,23.97593 65.67775,22.6885 89.64417,-2.84756c23.96959,-25.5424 22.69168,-65.67775 -2.84756,-89.64417c-63.21071,-59.31355 -155.09044,-94.72411 -245.78104,-94.72411z'); 

```

These two paths are composed by cubic beziers. They are overlapped.
But as it is shown in the [sample](http://sketch.paperjs.org/#S/lZRbb9MwFMe/ylFf0kmJZzt2bA/xMLYgVWxjajsJxHhIU7NWC8mUy8ZFfHdO7gkPCFSp8vmf2+8cJ/m5SKOvdnG22DzaMj4s3EWc7Wv7Pn2OcniKygOD15DaF7jF89K59oUhRgdCuDT2mOFoUMVdCt7oYVIRSrmUU7E9+VzF1PUloTzQCrgmvvGZ7wY+ERya//Yc9zFYupW9Pri32zjqeoz7hArGBDBKCaMcC3ocRSawH7SnmmEU/6f8QDuEdE7wpqE/nJNX49r4X9Y26d1VGHp70xX826KkIVyaQGI1xjQJTF2ZcyIVmsCkxsZCYCYlvpJaxFwSKaTULi7DKGlwYkkCpZSs0wKtJWhDkJUp3ArRQskgrmMDIw0qdToXUMcaFmgcv0uHPtr1+gJxPRBnVDHXQ1CcoH4qmMS5DK1vxAiiON4d5gpJlGZ0IrYrvU+b55B8OSbJRZZkOa7WecitTZ1XrY/PfVkepQ/WaVJPT2F1sw3Xm/BiC6sNhNe324+wLPPKQtwkFIesSvaws7BLovjxpL3DY1ravLBxiQXb9oOybFrWZIM079/UcWb+Io4Su6REztNKJC2SqLRLJim+N7Sdt8He3L3ZbNfniP32fHUVXsLymMJ3myTZS8dYVLsCK0wYUWmEEXGImSO2dZxZwIxxlEdGD18vV9AOEhHDDxdXd5chHAt4/w4awF1S2Q7PfouTam8HuM4e2Trhz+VVzdX1zhlVL45Mek50d7Pahv3CXo7lAeri68om4Nhnm2b7vdNw5nbfYVbpsRwhG2tEbMw5IGY6M8+6Sur8of7gnKG30gjuT8nbH35+d7mNHp8yfEKKxdmnz79+Aw==) , boolean operations are not consistent:
- `intersect` fails => returns empty path
- `subtract` fails => does nothing
- `unite` fails => it merges the 2 paths but keeps the overlapping region (visible in 'evenodd' mode)
- `exclude` works well

**Comment by lehni** [comment] 2016-06-12 08:48
Yes you're right! @iconexperience this one's really odd... It looks like it shouldn't give the current code base a hard time, but it does. We'll have to investigate this one too.

**Comment by lehni** [comment] 2016-06-12 14:45
@iconexperience one issue I'm observing here is that since the recent change to fat-line clipping, I now get four intersections between these two shapes instead of two. This is a problem, but weirdly it's not the origin of our issue here, since even before this change, the code was failing:
```js
var path1 = new Path('M349.98644,0c-192.98072,0 -349.98644,157.00255 -349.98644,349.98327c0,35.02687 28.39313,63.42 63.42,63.42c35.02687,0 63.42,-28.39313 63.42,-63.42c0,-123.04114 100.10213,-223.14327 223.14644,-223.14327c35.02687,0 63.42,-28.39313 63.42,-63.42c0,-35.02687 -28.39313,-63.42 -63.42,-63.42z');
var path2 = new Path('M349.98644,0c-35.02687,0 -63.42,28.39313 -63.42,63.42c0,35.02687 28.39313,63.42 63.42,63.42c59.25965,0 118.69687,22.57118 158.98443,60.37584c25.54558,23.97593 65.67775,22.6885 89.64417,-2.84756c23.96959,-25.5424 22.69168,-65.67775 -2.84756,-89.64417c-63.21071,-59.31355 -155.09044,-94.72411 -245.78104,-94.72411z');
path1.fillColor = 'green';
path2.fillColor = 'orange';
var inters = path1.getIntersections(path2);
inters.forEach(function(inter, i) {
    var other = inter.intersection;
    console.log(i + ':',
        'Path:', inter.path.id,
        'offset', inter.offset, inter.point,
        'index', inter.index, 'time', inter.time,
        '- Other:', other.path.id,
        'offset', other.offset, other.point,
        'index', other.index, 'time', other.time);
});
```
Output:
```
0: Path: 1 offset 0 { x: 349.98644, y: 0 } index 0 time 0 - Other: 3 offset 0 { x: 349.98644, y: 0 } index 0 time 0
1: Path: 1 offset 2.686113786305019e-7 { x: 349.98644, y: 0 } index 0 time 4.6396928262010607e-10 - Other: 3 offset 4.893197211936715e-8 { x: 349.98644, y: 0 } index 0 time 4.656612873077393e-10
2: Path: 1 offset 5.372229158537396e-7 { x: 349.98644, y: 0 } index 0 time 9.279388392558431e-10 - Other: 3 offset 4.893197211936715e-8 { x: 349.98644, y: 0 } index 0 time 4.656612873077393e-10
3: Path: 1 offset 1099.4447281344965 { x: 349.98644, y: 126.84 } index 4 time 0 - Other: 3 offset 199.2686014064649 { x: 349.98644, y: 126.84 } index 2 time 0
```
So the first three intersections are in fact one. The reason why they're not merged is in their offsets:

They are each slightly more than `2e-7` apart! So we may have to increase `GEOMETRIC_EPSILON` to `4e-7`, or find a way to increase the fat-line clipping precision. This hasn't struck us so far, so I'm wondering why it's happening now.

More analysis coming...

**Comment by lehni** [comment] 2016-06-12 14:51
@iconexperience could it be that due to the call-count, we allow too much recursion in some situations now, to the point where floating point noise leads to an increase of the imprecision of the results? We may have to look at where we decide to stop the recursion more now : (

**Comment by lehni** [comment] 2016-06-12 15:00
@iconexperience So I've added the recursion counting code back in along with the call counting, and saw that in this case we get 62 recursions, and this produces the imprecision. I think we should put a cap to recursions as well as call counts. I've tried 60 and the additionally found locations go away. You said your example in #940 needed 35 recursions. Does 48 sound like a good amount as a cap?

**Comment by lehni** [comment] 2016-06-12 15:11
So with 614c781f2902e0d0d354db5f85b1ffa160cbf033 in place, we're back to two intersections. The reason why this issue occurs is that the first one of the two is not considered to be a crossing:
```js
var path1 = new Path('M349.98644,0c-192.98072,0 -349.98644,157.00255 -349.98644,349.98327c0,35.02687 28.39313,63.42 63.42,63.42c35.02687,0 63.42,-28.39313 63.42,-63.42c0,-123.04114 100.10213,-223.14327 223.14644,-223.14327c35.02687,0 63.42,-28.39313 63.42,-63.42c0,-35.02687 -28.39313,-63.42 -63.42,-63.42z');
var path2 = new Path('M349.98644,0c-35.02687,0 -63.42,28.39313 -63.42,63.42c0,35.02687 28.39313,63.42 63.42,63.42c59.25965,0 118.69687,22.57118 158.98443,60.37584c25.54558,23.97593 65.67775,22.6885 89.64417,-2.84756c23.96959,-25.5424 22.69168,-65.67775 -2.84756,-89.64417c-63.21071,-59.31355 -155.09044,-94.72411 -245.78104,-94.72411z');
path1.fillColor = 'green';
path2.fillColor = 'orange';
var inters = path1.getIntersections(path2);
inters.forEach(function(inter, i) {
    var other = inter.intersection;
    console.log(i + ':', inter.point, inter.offset, inter.isCrossing());
});
```

**Comment by lehni** [comment] 2016-06-12 16:06
I finally found out what the problem is here. It has to do with how we currently handle the calculation of the angles for the `isInRange()` checks in `CurveLocation#isCrossing()`. The problem is that we're stepping away from the intersection point by a fixed amount of curve-time, and then look at the tangential angles to the curves at these points. But when the curves have different lengths like in the example above, the differences between the angles are not guaranteed to result in the indication of a crossing (the tangents for the example above don't end up crossing).

What we need to do instead is step away by a fixed *offset* along all the involved curves. I remember seeing similar code in Andy Finnell's https://bitbucket.org/andyfinnell/vectorboolean, and I finally understand what the reason for that code was! I will think of a good way to implement this without loosing too much performance.

**Comment by lehni** [comment] 2016-06-12 16:52
I found a new strategy to determine unambiguous tangential angles for all curves involved in an intersection:

If the intersection is on an actual segment, I step away from it at equal offsets on each curve. The offset is determined by taking 1/64th of the length of the shortest of all involved curves. This appears to work well.

1/64th is somewhat random, but if we step away too much we get ambiguous tangents again, and if we step away too little as well.

VectorBoolean has code that slowly shifts these offsets inwards until the resulting tangents are not ambiguous. @iconexperience do you think we need this too?

**Comment by lehni** [comment] 2016-06-12 16:55
Seee 4966f6250f5aeb517e4ea000c0b5962dc56f4e8f for my proposed solution.

**Comment by iconexperience** [comment] 2016-06-12 18:16
@lehni You are moving too fast for me :)
Hmm, I think this solution is not really reliable. Some time ago I had an idea for another approach, but never really made it work. Here it is:
1. Take the shortest distance `lMin` of all four curves from intersection point to end point of the curve.
![image](https://cloud.githubusercontent.com/assets/2122773/15992997/3a71b1d2-30da-11e6-9311-5d82b20196b1.png)

2. Calculate the point at `tMin` for all curves and use the vector from the intersection point to the point at `tMin` as the tangent vector.
![image](https://cloud.githubusercontent.com/assets/2122773/15993005/63dcf2d4-30da-11e6-88df-8b1eb13872de.png)


This will not work for special cases such as loops (where start point of a curve is the same as the end point), In these cases we could use the current approach with the tangent at `tMin`.

 I think this will be more reliable than your approach, because the curves cannot wind around each other if the length difference is very large. What do you think?

**Comment by iconexperience** [comment] 2016-06-12 19:33
A first implementation of my idea looks like this:

```javascript
var p = this.getPoint();
    // get the minimum distance from intersection on curve to beginning/end of curve
    var distMin = Math.min(
      c1.point1.getDistance(t1Inside ? c1.getPointAtTime(t1) : c1.point2),
      c2.point2.getDistance(t1Inside ? c2.getPointAtTime(t1) : c2.point1),
      c3.point1.getDistance(t2Inside ? c3.getPointAtTime(t2) : c3.point2),
      c4.point2.getDistance(t2Inside ? c4.getPointAtTime(t2) : c4.point1)
    );
    // get curve lengths from beginning of curve to distMin
    var l1 = t1Inside ? c1.getPartLength(0, t1) - distMin : c1.getLength() - distMin,
      l2 = t1Inside ? c2.getPartLength(0, t1) + distMin : distMin,
      l3 = t2Inside ? c3.getPartLength(0, t2) - distMin : c3.getLength() - distMin,
      l4 = t2Inside ? c4.getPartLength(0, t2) + distMin : distMin;
    // get points on curves for distMin
    var v2 = c2.getPointAt(l2).subtract(p),
      v1 = c1.getPointAt(l1).subtract(p),
      v4 = c4.getPointAt(l4).subtract(p),
      v3 = c3.getPointAt(l3).subtract(p);
```

This does not handle cases like the above mentioned loops, but it looks nice at first sight.

**Comment by lehni** [comment] 2016-06-12 20:56
Hmmm... Since your approach doesn't cover loops, or near-loops, I'm wondering: Can you come up with a scenario where my approach would actually fail?

**Comment by iconexperience** [comment] 2016-06-12 21:09
I was thinking of cases like these, where a curve comes back to the intersection. Maybe this is a very constructed case and not relevant for the real world?
![image](https://cloud.githubusercontent.com/assets/2122773/15993815/471abf92-30f2-11e6-9853-ff91cfca7f4a.png)
We could cover these cases by setting the length to `Math.max(c.getPartLength(0, tMin), distMin)` or similar for each curve.

**Comment by lehni** [comment] 2016-06-12 21:10
I just tried this approach, and it fails a current unit test:

```js
var path1 = new Path.Circle(new Point(110, 110), 80);
var path2 = new Path.Rectangle(new Point(110, 110), [100, 100]);
path1.strokeColor = 'red';
path2.strokeColor = 'blue';
```

They have two crossings, but only one of them is found to be a crossing.

**Comment by lehni** [comment] 2016-06-12 21:12
My proposed solution is covering all unit tests, this new issue, and all the tests suites I've been running separately. I'm not convinced that's there are issues with it. Can you explain why you think it's not reliable?

**Comment by iconexperience** [comment] 2016-06-12 21:23
I do not have a real example, but here is a mockup:
![image](https://cloud.githubusercontent.com/assets/2122773/15993904/82f2aa32-30f4-11e6-8d4a-09e98cc430f5.png)
![image](https://cloud.githubusercontent.com/assets/2122773/15993906/8de322e6-30f4-11e6-8a83-e1e8d94cc5db.png)

This is quite a strange example and I thought before that it would be easier to find examples that would fail, so maybe your proposal method is better than I initially thought.

**Comment by lehni** [comment] 2016-06-12 21:29
Yeah I was thinking about such scenarios. But how would your proposal protect us against these? I feel that the most reliable approach is probably what VectorBoolean is doing: moving away from the intersection point at constant offset steps until the resulting tangents are significantly different in their angles from the starting angles. For each curve you'd probably stop as soon as the first change of angle is significant, and use that. And there would need to be a strategy for when there is no change. I can look more into who they are handling this.

But we can also increase the divisor further, e.g.`/ 128`, `/ 256`, etc.

**Comment by iconexperience** [comment] 2016-06-12 21:40
Note that I am not using the tangent at the points, but the vector from the intersection point to the point on the curve. Where my approach can fail is when one curve is extremely short, but this could be worked around with setting the minimum length as above.

Just as it happens, this case that I am currently working on, seems to cause problems with your new approach:
```javascript
var p1 = new paper.Path({segments:[[246.97910285795234, 178.9392357483178, -37.579269102990025, 0, 18.789634551495, 0], [295.09126232639085, 198.86694338951378, -12.312558139534872, -12.312558139534872, 1.1871674413560527, 1.1871674413560243], [298.519138493481, 202.55684107480155, -1.0972115374110558, -1.2718925495427982, 10.282380232989283, 11.91938141733695], [315.0189699675869, 246.97910285795234, 0, -16.977952355015617, 0, 37.575016611295666], [246.97910285795234, 315.0189699675869, 37.579269102990054, 0, -18.789228964374274, 0], [198.8677407210611, 295.09046499484356, 12.312495152364619, 12.312621146933395, -12.313026711106886, -12.313152711115151], [178.9392357483178, 246.97910285795234, 0, 18.78791384687213, 0, -37.579269102990025]], closed:true});
var p2 = new paper.Path({segments:[[295.09179388785265, 198.866411828052, 0, 0, 1.1869628034385187, 1.1873728078610952], [298.519138493481, 202.55684107480155, -1.097060801433031, -1.2720418282001162, 10.282380232989283, 11.91938141733695], [315.0189699675869, 246.97910285795234, 0, -16.977952355015617, 0, 37.575016611295666], [246.97910285795234, 315.0189699675869, 37.579269102990054, 0, -18.789228964374274, 0], [198.8677407210611, 295.09046499484356, 12.312495152364619, 12.312621146933395, -12.313026711106886, -12.313152711115151], [178.9392357483178, 246.97910285795234, 0, 18.78791384687213, 0, -37.579269102990025], [246.97910285795234, 178.9392357483178, -37.579269102990025, 0, 18.789634551495, 0], [295.09126232639085, 198.8669433895138, -12.312558139534872, -12.312558139534872, 0, 0]], closed:true});       
var ints = p1.getIntersections(p2);
```

**Comment by lehni** [comment] 2016-06-12 21:57
Ok, I'll look at this. But did you see the case I posted above? There are no short or irregular curves in it. Something else must be going on. I haven't had the time to look at it yet.

**Comment by lehni** [comment] 2016-06-12 22:01
Regarding your case: It looks like two circles on top of each other, one rotated. 6 intersections are found, none of them crossings. What do you expect to be found?

**Comment by lehni** [comment] 2016-06-13 06:27
Some more thoughts on the two proposed approaches:

* if `t1` or `t2` are inside a curve, there is no need to step away from the intersection point, because it is in a location where the curve is continuous and the tangent unambiguous. Using the tangent in the actual intersection point is perfectly fine.
* When stepping away from a intersection point that occurs in a segment, my method takes the tangent in that new location, yours the vector to the intersection point from it. I agree that your approach is probably less prone to error here.
* The two approaches use different strategies to determine how far away we should step. Mine uses a fraction of the shortest involved curve (involved curves are the ones where the intersection ins inside, not no a segment), yours uses the shortest length of the distance of the end-points of all curves.

I believe we can combine the two approaches. But before I work more on it, I'd like to find out what is the new issue with the paths posted [here](https://github.com/paperjs/paper.js/issues/1074#issuecomment-225462140)

**Comment by lehni** [comment] 2016-06-13 06:31
Some more remarks about code.

* `c1.getPartLength(0, t1)` can be written as `c1.getOffsetAtTime(t1)
* `c1.getPointAt(c1.getLength() - distMin)` can become `c1.getPointAt(-distMin)` because negative offsets will be applied from the end of the curve instead of the beginning.

**Comment by lehni** [comment] 2016-06-13 06:36
A combined method could look like this:
```js
var lenghts = [];
if (!t1Inside)
    lenghts.push(c1.getLength(), c2.getLength());
if (!t2Inside)
    lenghts.push(c3.getLength(), c4.getLength());
var pt = this.getPoint(),
    offset = Math.min.apply(null, lenghts) / 64,
    v2 = t1Inside ? c2.getTangentAtTime(t1) : c2.getPointAt(offset).subtract(pt),
    v1 = t1Inside ? v2.negate()             : c1.getPointAt(-offset).subtract(pt),
    v4 = t2Inside ? c4.getTangentAtTime(t2) : c4.getPointAt(offset).subtract(pt),
    v3 = t2Inside ? v4.negate()             : c3.getPointAt(-offset).subtract(pt),
```

**Comment by iconexperience** [comment] 2016-06-13 08:36
@lehni Sorry for the wrong issue yesterday, I was testing against a different codebase. Your code was actually throwing a `Uncaught TypeError: Cannot read property 'negate' of null`

Regarding the tangents for `t1Inside` and `t2inside`you are probably correct, we can keep it the current way for these cases.

The reason why I decided on the distance between intersection point and curve end points was that I wanted to make sure these cases cannot happen, where a long curve is "overtaking" a short curve:

![image](https://cloud.githubusercontent.com/assets/2122773/16001499/97adc52a-3152-11e6-9ebc-2e06cfe188a3.png)

With my approach these cases should not be possible. I am not sure if this is possible with your approach.

**Comment by iconexperience** [comment] 2016-06-13 09:07
I am trying to think of a case where your approach could teoretically fail. In the first 1/64 of the curve it would need an s-shape, while the other would need a hook, overtaking the s-shaped curve, like this:
![image](https://cloud.githubusercontent.com/assets/2122773/16002232/de77a03a-3156-11e6-8457-e3187384106d.png)

And zoomed in:
![image](https://cloud.githubusercontent.com/assets/2122773/16002238/e925ad60-3156-11e6-863a-d62807da5e2e.png)

Possible in theory, but how relevant for real world scenarios?

**Comment by lehni** [comment] 2016-06-13 09:35
Please note that it's not 1/64 of the full curve, but 1/64 of the lenght of the shortest involved curve, as an offset, not curve-time. I think we're good.

**Comment by lehni** [comment] 2016-06-13 11:35
@iconexperience iv'e read too quickly and missed the main point of your comment. You are right, there may be a curve where this catches us. This is probably the reason for the iterative approach in VectorBoolean. How would you handle it?

**Comment by ghenania** [comment] 2016-06-17 07:45
@lehni @iconexperience Guys, thanks for your support! 
So what about this issue now ? I tried to follow your discussion but too expert for me ;-) Do you think you could found a fix ?

**Comment by lehni** [comment] 2016-06-17 08:45
It's fixed on the `develop` branch, of which you can get a prebuilt version [here](https://github.com/paperjs/paper.js/tree/prebuilt/module). The bug is still open because the fix could need some improving for rare edge cases.

**Comment by ghenania** [comment] 2016-06-17 09:37
Great !!!
Thank you guys.

**Comment by lehni** [comment] 2016-07-19 15:37
@iconexperience could you share your latest state of `isCrossing()`? Thanks!

**Comment by iconexperience** [comment] 2016-07-19 16:21
@lehni Here it is (unfortunately uncommented and not in your formatting style):
```
  isCrossing: function() {
    var inter = this._intersection;
		if (!inter)
			return false;
    var t1 = this.getTime(),
      t2 = inter.getTime(),
      tMin = 4e-7,
      tMax = 1 - tMin,
      t1Inside = t1 > tMin && t1 < tMax,
      t2Inside = t2 > tMin && t2 < tMax;
    if (t1Inside && t2Inside)
      return !this.isTouching();
    var c2 = this.getCurve(),
      c1 = t1 <= tMin ? c2.getPrevious() : c2,
      c4 = inter.getCurve(),
      c3 = t2 <= tMin ? c4.getPrevious() : c4;
    if (t1 >= tMax)
      c2 = c2.getNext();
    if (t2 >= tMax)
      c4 = c4.getNext();
    if (!c1 || !c2 || !c3 || !c4)
      return false;

		function isInRange(angle, min, max) {
			return min < max
				? angle > min && angle <= max
				: angle > min && angle <= 180 || angle >= -180 && angle <= max;
		}

    var p = this.getPoint();
    // get the minimum distance from intersection on curve to beginning/end of curve
    var distMin = Math.min(
      c1.point1.getDistance(t1Inside ? c1.getPointAtTime(t1) : c1.point2),
      c2.point2.getDistance(t1Inside ? c2.getPointAtTime(t1) : c2.point1),
      c3.point1.getDistance(t2Inside ? c3.getPointAtTime(t2) : c3.point2),
      c4.point2.getDistance(t2Inside ? c4.getPointAtTime(t2) : c4.point1)
    );
    // get curve lengths from beginning of curve to distMin
    var l1 = Math.min(t1Inside ? c1.getPartLength(t1, 1) + distMin : Math.max(c1.getPartLength(tMax, 1), distMin), c1.getLength()),
      l2 = Math.min(t1Inside ? c2.getPartLength(0, t1) + distMin : Math.max(c2.getPartLength(0, tMin), distMin), c2.getLength()),
      l3 = Math.min(t2Inside ? c3.getPartLength(t2, 1) + distMin : Math.max(c3.getPartLength(tMax, 1), distMin), c3.getLength()),
      l4 = Math.min(t2Inside ? c4.getPartLength(0, t2) + distMin : Math.max(c4.getPartLength(0, tMin), distMin), c4.getLength());
    // get points on curves for distMin
    var v2 = c2.getPointAt(l2).subtract(p),
      v1 = c1.getPointAt(-l1).subtract(p),
      v4 = c4.getPointAt(l4).subtract(p),
      v3 = c3.getPointAt(-l3).subtract(p);

    var a1 = v1.getAngle(),
			a2 = v2.getAngle(),
			a3 = v3.getAngle(),
			a4 = v4.getAngle();
		return !!(t1Inside
				? (isInRange(a1, a3, a4) ^ isInRange(a2, a3, a4)) &&
				  (isInRange(a1, a4, a3) ^ isInRange(a2, a4, a3))
				: (isInRange(a3, a1, a2) ^ isInRange(a4, a1, a2)) &&
				  (isInRange(a3, a2, a1) ^ isInRange(a4, a2, a1)));
	},
```

One problem that I had initially was that a partial length of a curve could give a larger value than the full length of the curve (in the area of `1e-14`), that's why I limit `l1`, `l2`, `l3` and `l4` to the curve's length.

**Comment by lehni** [comment] 2016-07-19 16:30
@iconexperience thanks! You were saying there were situations where this worked while the current implementation didn't. Could you share some of those, so I can create unit-tests?

I do get one new failing test with your implementation that worked before, from issue #923. I haven't looked at why that is yet.

**Comment by iconexperience** [comment] 2016-07-19 16:38
@lehni Uh, did I say so?  I am not sure if I can find that test case, but the problem is probably with the `<=` comparisons in `isInRange()`. I remember there was one case where this helped, and it did not cause any other problems on my side. But please note that I do not check against your tests all the time. For my little hacks it is only important that there are no issues with my use case.

**Comment by lehni** [comment] 2016-07-19 17:02
@iconexperience here you said:

>It's a bit hacky, but I just had to get things working.

https://github.com/paperjs/paper.js/issues/1075#issuecomment-233200314

So I was under the impression it solves things that my implementation doesn't?

**Comment by iconexperience** [comment] 2016-07-19 17:15
I really do not remember, maybe I used it because I understood my implementation but didn't understand yours :)
Anyway, I will go through my own test cases tonight and check if they still fail with the current version. If so, I will open a new issue. Does that sound alright for you?

**Comment by lehni** [comment] 2016-07-19 17:50
@iconexperience yes, that's great!

**Comment by lehni** [comment] 2016-07-28 11:56
Note to self:https://github.com/paperjs/paper.js/issues/1073#issuecomment-235874249 is related to this issue here, both need wrapping up.

**Comment by lehni** [comment] 2016-07-28 12:02
@iconexperience a thought regarding your observation in https://github.com/paperjs/paper.js/issues/1074#issuecomment-225526866: 

Couldn't we use the checks similar to what you developed in https://github.com/paperjs/paper.js/issues/773#issuecomment-144018379 to find out such cases?

Also, please note that there is some new information in https://github.com/paperjs/paper.js/issues/773#issuecomment-212840326 that sounds interesting.

**Comment by lehni** [comment] 2016-07-28 12:03
e.g.

![screen shot 2016-07-28 at 14 03 16](https://cloud.githubusercontent.com/assets/213275/17211876/1c0ff2ba-54cc-11e6-85af-21681ac49e90.png)

**Comment by deanm** [comment] 2016-08-15 13:16
I haven't really followed this discussion, but just from a brief look at Paper's code, I think it would benefit to take a more formal approach to classifying cubic curves.  There are pretty simple / cheap to compute calculations to categorize the curve (loop, etc), the approach I find the simplest is the one covered in LoopBlinn.  The GPU Gems article goes into the math a little bit deeper (but be careful there is an error in one of the cross products).

Perhaps it's helpful I created this table for the 4 types of cubic curves (A and D are both Serpentine).  There are additionally the degenerate cases of quadratic/line/point.  It is written in column form, so each column is a type of curve.


```
                        A           B           C           D
                       Func        Cusp        Loop

  Inflection Points     1           -           -           2
              Cusps     -           1           -           -
 Self-Intersections     -           -           1           -
 Curvature Extremum     2          0/2         1/3         3/5
```

I think it is easiest to just follow Loop and Blinn, but for more background the classic reference is:

Maureen C. Stone and Tony D. DeRose. 1989. A geometric characterization of parametric cubic curves. ACM Trans. Graph. 8, 3 (July 1989), 147-163. DOI=http://dx.doi.org/10.1145/77055.77056

**Comment by lehni** [comment] 2017-01-05 10:51
I have created a separate issue to track work on @deanm's suggestion: #1235

**Comment by lehni** [comment] 2017-01-11 14:05
@deanm thank you for all the suggestions and help! This worked out beautifully.

**Comment by lehni** [comment] 2017-01-24 12:53
@iconexperience I have implemented a new approach based on inception and peak points in 1806b5959e3914cb0068a5656fde6c30f2516c09

This should address scenarios such as the one outlined in https://github.com/paperjs/paper.js/issues/1074#issuecomment-225526866

It also addresses the issue here: https://github.com/paperjs/paper.js/issues/1073#issuecomment-234305530

Please let me know your thought, so we can close these two issues finally!

**Closed** 2017-01-25 12:56 UTC
Labels: cat: boolean-operations, type: bug
