### ISSUE TITLE
Shadow doesnt scale when zooming the view 

### ISSUE THREAD

**Issue by tobmaster** [paperjs/paper.js#831] opened 2015-11-18 08:57 UTC
When I define a Symbol/item like this

```
new paper.Symbol(
      new paper.Shape.Circle({
        center: [0, 0],
        radius: 5,
        fillColor: 'lime',
        strokeColor: 'green',
        shadowColor: new Color(0, 0, 0),
        shadowBlur: 6,
        shadowOffset: new Point(3, 3)
      })
    );
```

I expected the shadow to resize as the circle does. Instead its size is steady and changes the distance to the circle when zooming out and is disappearing behind the circle when zooming in. 

As I am new to paperjs it still might do something wrong but it appears as a bug.

**Comment by lehni** [comment] 2015-11-18 09:35
This is a canvas weirdness and not necessarily a Paper.js bug. From the Mozilla website:

>  this value doesn't correspond to a number of pixels and is not affected by the current transformation matrix.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/shadowBlur

We could try and "fix" this in paper.js of course, but I'm not sure how many people are already expecting the current behavior... Or we could make it controllable through a `item.shadowScaling` property, similar to the already present `item.strokeScaling`.

**Comment by sapics** [comment] 2015-11-21 01:48
:+1: `item.shadowScaling`
Just my two cent, it would be useful, scaling with item scaling at `item.shadowScaling = 1` (which is similar to `strokeScaling = true`), and scaling with `view._matrix.scaling` at `item.shadowScaling = 2`.

**Comment by iconexperience** [comment] 2015-11-21 07:41
Even if this is the behavious specified by canvas, it is a really weird. When zooming I would expect the whole view to appear just as if I looked through a magnifying glass, which means the shadow should change its extent and offset accoring to the zoom factor.

I have tried to simulate the expected behaviour. <a href="http://sketch.paperjs.org/#S/dVJNa4MwGP4rIZfqEHEb7GDZZd11tLBj20MaX2sw5pUYFVb870viR6VsEoU8HybPk9yoYhXQlH6XYHhBI8oxc/OOaXKRrSbv5G170iflAMzzBoyFXj00w1xoLsHCCnpSsxp0fGCmiHceD25OR+zDQRnQKTk+J0lE7OcczZRmmWiblLwkC5QLKXco0Ro2UlSwWZjGaCxh5q4aQK3IgmXYT+R9Qx4I7LJuhA/qDxs09XEfiL0PvP7PAYUywVhENBUSOtMQLp24d1R3AvoY1Re2DXxir2xHeau4EahIAJ3tIyRLPa7KH8TKilZuh2yXBn2j8X3XVutP6Yn8r9vPp/Z3isk7h5mmY5pha2/ERQMra+doaHo8D78=">Here is the Sketch.</a>

It is not perfect, but probably good enough. Here is a comparison between the original circle and zooming it with 4.76, then scaling it back to original size with an image editor:

![image](https://cloud.githubusercontent.com/assets/2122773/11317314/06f903dc-902b-11e5-987c-390f8cfbb646.png)

So I agree, `item.shadowScaling` :+1:

**Comment by tobmaster** [comment] 2015-11-22 13:41
Thanks for the nice tip and the answers. 
That tip should work for me now. Even when that can become slightly harder to maintain through the application lifecycle. 
The behavior is weird in canvas yes, a library should try to abstract that away or provide a way to control that behavior. So i think shadowScaling is the way to go looking for the backward compatibility.

**Comment by iconexperience** [comment] 2016-02-12 20:21
I found this strange behavior that if I use browser zooming and reload a page, the shadow offsets are changed. Actually, it stays the same, but the proportions change.

Here is an example. At the left is the browser at 100%, at the right is the browser at 75%.

![image](https://cloud.githubusercontent.com/assets/2122773/13019110/af345b4e-d1cd-11e5-98ed-9a3f2d51a998.png)

<a href="http://sketch.paperjs.org/#S/TY5BCoMwEEWvMmQTCyLaZaSbeoAWurQuYjLWYExKEutCvHuTQsHNwMx//zEbMXxGwshjwiBGkhNhZdo/3IGACxhc4c7DWDTKCY3ZJtAEdAzac1nmEEeXg+NSLZ5BlU6D0rqx2kaGvqyWaJyVdD/VTyMKP3Jp19sweAx/u1UmZLEY20fo54gM7TUXEz0kV72koCrr+G/vkE/v5PCEtd3+BQ==">And here is the Sketch that I am using</a>

When zooming in and out once the image is displayed, the proportions stay the same, until the script is run again.

Before I thought this would only affect scaling from inside paper.js., but this is quite a strange behaviour and I think it should be fixed. 

@lehni Do you think there is a way to only respect browser zooming, but no other scaling for the shadows?

**Comment by lehni** [comment] 2016-02-12 20:24
Which browser?

**Comment by lehni** [comment] 2016-02-12 20:26
This looks like a Chrome bug. Safari doesn't behave this way. Firefox does the same. Ah man.

**Comment by iconexperience** [comment] 2016-02-12 20:27
Chrome, Firefox and InternetExplorer 11

**Comment by iconexperience** [comment] 2016-02-12 20:29
Do we have access to the browser`s zoom factor from inside paper.js at all?

**Comment by lehni** [comment] 2016-02-12 20:32
It looks like a real pain: http://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers

**Comment by iconexperience** [comment] 2016-02-12 20:33
I was just about to post the same link. This looks horrible.

**Comment by iconexperience** [comment] 2016-02-13 07:45
Here is a little non-paper.js test case that uses canvas shadows. It seems that the problem does not occur here, so maybe we have a chance to fix without having to get the browser's zoom factor:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Test for Canvas Shadow Offset</title>
    </head>
    <body>
        <canvas id="myCanvas" width="512" height="512"></canvas>
        <script>
            var canvas = document.getElementById('myCanvas'),
                context = canvas.getContext('2d');
    
            context.rect(100, 384, 28, 30);
            context.fillStyle = 'orangered';
            context.fill();
            context.beginPath();
            context.rect(128, 128, 256, 256);
            context.fillStyle = 'mediumaquamarine';
            context.shadowColor = '#000';
            context.shadowBlur = 0;
            context.shadowOffsetX = 0;
            context.shadowOffsetY = 30;
            context.fill();
        </script>
    </body>
</html>
```

![image](https://cloud.githubusercontent.com/assets/2122773/13026608/fcaea1b2-d22d-11e5-9311-6c46126842d2.png)

The height of the little orange rectangle should always have the height of the balck rectangle (which is the shadow).

**Comment by lehni** [comment] 2016-02-13 08:17
Interesting. You can use the internal `ProxyContext` class to produce the sequence of drawing commands used by paper.js to draw the scene. This can then also be extracted into such a "paperless" file, and from there you can maybe find out at what causes the offsets:
```js
view._context = new ProxyContext(view._context);
```

**Comment by iconexperience** [comment] 2016-02-13 09:18
OK, I will look into this one.

**Comment by tobmaster** [comment] 2016-02-13 12:10
Hey guys. I just want to note, my issue was about zooming with the paper.js view. 
You are now talking about Browser zooming
I guess that is another thing or not?

**Comment by iconexperience** [comment] 2016-02-13 13:23
@tobmaster 
Yes, but it's related, and I guess it's easiest to fix them at the same time. I hope you don't mind if we keep the together.

**Comment by iconexperience** [comment] 2016-02-13 13:55
OK, I have hooked the `ProxyContext` on the view's context, but the only difference that I can see is that a different area is cleared via `clearRect()` at the beginning. This should not make a difference.

<a href="http://sketch.paperjs.org/#S/nVdtb9s2EP4rqvdBVMwqdj46C7DURbcWRRMkwdYicQeGom0utKiRVGw1yH/fHSnZkq1kw2jA5stzx3vn+WmQs5UYTAbXD8Lx5YAOuM5wfZfvPo/MRJdGb6qpzp3YuOgsysU6mpc5d1LnJIme7vIIBgIzYbmRBR5YAN6GExyxZY+CJDGNYiOs06ZeWM6UIBtahSPtmBOE5Qsl/IYzLLcK9wKkxdAfzbVZEUbvKacZFXQeeAp38+LhQul7ps5VsWQddmF/qleFttKJi0IYhnp4hs7oB3HtKiVwOZdK1YsWA24EyPlZ5oKZXw3LpMgd2YxoNaKbMa3GSQ/6CmBM7aFNTUBNL80lc06YnMgVWwhqRCGcREG9dgqu/0Nmbtkspqxopp+0zDv8VqCn+Szhxyu5ZJleX8znYL6v+xvfdhvvVGk6bML2VCttEMUVGOBKcIcuo2u6TBqb7W22WXgDHxDdi4XMQd9liBWutBW75Uo/iht9GBio63Y/iv8uWYau5NPSeAJebCgvKnpAeC9+SGF2sDHixhV8neDspCGJYmY43uC9tDmh1QlFF5a2y8/s6wNkfh3A1Dpm3DnGOhV5FiYsB0mV5g9raUWXHZqwThpvrjAH3dbXlXVi9UHz0l7JfLE7mJaQat2DttW50UqhQT/mTv8uxbqxsyzCTNpLCBr3MTih0X4OlaCbilAXzpVc+GTBxTtmBbqh8fwN7BE8QAvSFdv4GO2LgReR4G/BbGl2iC45qvsRU6JOjGxDs2priIMTmq1ptnydhd1QW1G7pna5R9Tkoke/Z44Rj+pL1x3EM81gFuqQcC3q3U1dHkXpehg00kjjqq/h51v48dYK09+EXCz3jASZjAXqPbNLwoxh1bZo4FZI9TjgZ6e7sj6XQmVY0I+PjqJfFASr7bwJP0VHx80zgEPmUJGYkj/EZPdQ8IBN2kAcbilt+id3G+BfY077EDLPoEaiFKPW+TPFR6pZoVE9zJfuSc8r1QxUCyIOuMXx3nXwbEQEz6W/C35+7ooAW8PhAUccyHEILL2x99g+d5dGuNLkSNHWJkyfTxulGgUQBwks5xVIpkrRud2Zal+Ymvun64sv6T5p+76IM3j5IyIO1Kk5eJJo2LVSI2YjJaZ7KhhfknYDQHfmb213LkIrr7wEZ+3eIfV75Pg7uf1OZsOE3N2R5Og4oV0RsXsBQg++Hc/2TqX90BjvLHrzJqBOZi015DwiO9SBBULU3+ItM2Dxciw1vII8Z2fbFidODoHeYe1oevv29BAFiWC1EqnSC+LR3cgGGcAlkDNpDBN/L6xJ3H8djmF0jvmeFtBiaVcVIrVKcpFC+6WgFCzKFcpCo9ELIjcDXFOQbUQl6V/wPhAsIq/QgWjJaZz0qNm1GraI/8lkw2EPrzpgt+UkOC5lRaEqst2l0VbZfYGeO4khlBX/EhE9YQBueq3qvC5rj1Ld8tYM27nlsCC0x/+KJCyLr8fB8LAiAV2/l1/WGO7xxH2av+Kcuvw0d9W8QxXaOHieSPAUAkItxU/bEneD7d+HSXQ3ANkLBh1/+ghNEMgXnqGUl8aAobZ/JpKaVw+2/lvUfhVJD6zhgIWPNzTQW6VTaaBxJk8c7hNmEt2ejEY0gq8ZjUK7OInGuIXtlO+1J9BDaAWONDqLvS142m7ZG+7YwBEgBOo2yPNAP98rxh/i1gk2+HAwHp3CP8J7aGIeCuRhB5Pb2fM/">Here is my sketch</a>

And this is the output:

```
transform: undefined
ctx.clearRect(0, 0, 1727.9847412109375, 1527.9801025390625); // this is the only part that changes
ctx.save();
    ctx.save();
        ctx.globalAlpha = 1;
        ctx.save();
            ctx.globalAlpha = 1;
            ctx.beginPath();
            ctx.moveTo(100, 200);
            ctx.bezierCurveTo(100, 144.77152501692063, 144.77152501692063, 100, 200, 100);
            ctx.bezierCurveTo(255.22847498307937, 100, 300, 144.77152501692063, 300, 200);
            ctx.bezierCurveTo(300, 255.22847498307937, 255.22847498307937, 300, 200, 300);
            ctx.bezierCurveTo(144.77152501692063, 300, 100, 255.22847498307937, 100, 200);
            ctx.closePath();
            ctx.fillStyle = "rgb(218,165,32)";
            ctx.shadowColor = "rgb(0,0,0)";
            ctx.shadowBlur = 10;
            ctx.shadowOffsetX = 0;
            ctx.shadowOffsetY = 100;
            ctx.fill("nonzero");
            ctx.shadowBlur = 0;
        ctx.restore();
    ctx.restore();
ctx.restore();
```

**Comment by lehni** [comment] 2016-02-13 15:31
And did you try this in an isolated HTML container along with the zooming, to see if the same occurs?

**Comment by lehni** [comment] 2016-02-13 15:33
It doesn't happen here on Chrome: https://jsfiddle.net/n2xqmozz/

**Comment by lehni** [comment] 2016-02-13 15:34
Perhaps it's got something to do with CSS styling of http://sketch.paperjs.org/

**Comment by lehni** [comment] 2016-02-13 17:41
Ok, found it. The weird scaling happens because the zoom level changes `window.devicePixelRatio` on these browsers, and we're using its initial value to set up HiDPI support. These two issues are indeed linked...

https://github.com/paperjs/paper.js/blob/develop/src/view/CanvasView.js#L53

**Comment by lehni** [comment] 2016-02-13 17:48
Here the script that replicates your problem:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Zoom</title>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(event) {
    var canvas = document.getElementById('canvas');
    var ctx = canvas.getContext('2d');
    var deviceRatio = window.devicePixelRatio || 1;
    ctx.save();
    ctx.restore();
    ctx.save();
    ctx.scale(deviceRatio, deviceRatio);
    ctx.clearRect(0, 0, 1000, 1000);
    ctx.save();
        ctx.save();
            ctx.globalAlpha = 1;
            ctx.save();
                ctx.globalAlpha = 1;
                ctx.beginPath();
                ctx.moveTo(100, 200);
                ctx.bezierCurveTo(100, 144.77152501692063, 144.77152501692063, 100, 200, 100);
                ctx.bezierCurveTo(255.22847498307937, 100, 300, 144.77152501692063, 300, 200);
                ctx.bezierCurveTo(300, 255.22847498307937, 255.22847498307937, 300, 200, 300);
                ctx.bezierCurveTo(144.77152501692063, 300, 100, 255.22847498307937, 100, 200);
                ctx.closePath();
                ctx.fillStyle = "rgb(218,165,32)";
                ctx.shadowColor = "rgb(0,0,0)";
                ctx.shadowBlur = 10;
                ctx.shadowOffsetX = 0;
                ctx.shadowOffsetY = 100;
                ctx.fill("nonzero");
                ctx.shadowColor = "rgba(0,0,0,0)";
            ctx.restore();
        ctx.restore();
    ctx.restore();
});
</script>
</head>
<body>
    <canvas id="canvas" width="1000" height="1000"></canvas>
</body>
</html>
```

**Comment by iconexperience** [comment] 2016-02-13 20:32
Yes, the scaling happened before I could exchange the context with the `ProxyContext`. I worked around this by inserting these lines before initializing the paper project:

```
canvas.getContextOriginal = canvas.getContext;
canvas.getContext = function(a) {
    return new ProxyContext(canvas.getContextOriginal(a));
}
```

Anyway, the result is the same.

So this means that even without browser zooming the shadow offset will be different on  HiDPI environments than on standard environments?

**Comment by lehni** [comment] 2016-02-13 20:38
No, it just means that when fixing the weird shadow behavior we also need to take this initial scaling into account. It can all be solved together, I think. But it's not very high priority at my end...

**Comment by iconexperience** [comment] 2016-02-14 06:36
Fixing the zooming issue would actually be quite easy, we only have to multiply with the pixel ratio when setting the shadow offset and shadow blur to the canvas. Like this (<a href="https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L3953">in Item.js lines 3953ff</a>):

```
ctx.shadowBlur = style.getShadowBlur() * (_pixelRatio || 1);
var offset = this.getShadowOffset();
ctx.shadowOffsetX = offset.x * (_pixelRatio || 1);
ctx.shadowOffsetY = offset.y * (_pixelRatio || 1);
```
The problem is that at the moment we do not have access to `_pixelRatio`there, because it is stored in the view, but we only have access to the canvas context at that place.

**Comment by lehni** [comment] 2016-02-14 09:21
Yes but we need to fix *both* issues here (they are not the same)...

**Closed** 2016-02-14 12:49 UTC
Labels: cat: canvas-rendering, type: bug

**Comment by lehni** [comment] 2016-02-14 12:51
While working on the new hit-testing features for #536, I got an idea for this simple and elegant solution. It covers both issues described here and works like a charm for me :)
