### ISSUE TITLE
Uniting paths sometimes makes some paths disappear.

### ISSUE THREAD

**Issue by MichaelPriebe** [paperjs/paper.js#1321] opened 2017-05-06 03:46 UTC
I'm using paper to create svgs based on a texture. I combine all the 'pixels' into one optimized path using unite, but this one pixel causes it and the rest of the connected pixels to disappear.

![illustrator_2017-05-05_23-36-20](https://cloud.githubusercontent.com/assets/5238952/25769623/b32a7c12-31ec-11e7-8ff4-e67ecf2ad840.png)

You can see what pixel makes it go wrong if I change that pixel to a different color.

![illustrator_2017-05-05_23-41-51](https://cloud.githubusercontent.com/assets/5238952/25769628/c681a13c-31ec-11e7-936d-4abf335c32fa.png)

Is there a better way to keep merging geometry without the possibility of it deleting stuff like this?

**Comment by lehni** [comment] 2017-05-06 16:48
Could you provide a test case for replication? Hard to tell without seeing it in action

**Comment by MichaelPriebe** [comment] 2017-05-08 17:37
Its hard to give you a example because its a node.js application creating svgs basted on .json files and textures.
For example, before optimization:
![illustrator_2017-05-08_13-32-07](https://cloud.githubusercontent.com/assets/5238952/25816780/32d76dc8-33f3-11e7-8769-a314b5f70675.png)
After my optimization (subtracting all the faces from below, uniting the same colors into one compound path, etc.)
![illustrator_2017-05-08_13-30-04](https://cloud.githubusercontent.com/assets/5238952/25816817/5bcfe0e8-33f3-11e7-804c-34f7d2693195.png)
You can see there's some problems where faces go missing after uniting them.

**Comment by lehni** [comment] 2017-05-08 19:27
It's simple: I can't fix a bug if I can't reproduce the problem.
You should be able to identify two rhombus shapes where the problem occurs, and log their segments, e.g. `console.log(path.segments)`

**Comment by MichaelPriebe** [comment] 2017-05-08 20:33
http://sketch.paperjs.org/#S/bdVRS8MwEAfwr1L60gqZJOm11oFPex4IPqoP2VbZWNaOrlNQ/O7+MycI938p9NdrSC53yVfeh0OXz/OnfTett7nJ18Mmvb+HMTuGaZs9ZH33kS2Gw3E495tHUFksKzG+it64OLs+Zu5zWbVMxRovOtYzFWitYy3VxvhGqW+ZilDFCHd6BKppxURbpgJt9bjCNOVBa8oZGQGx93QOWmtL1ZvK6nEt01pM5ZS6lilWUXm2Q0Qd1ZoqcsZiMQdSfcIUFUXU0VjUGdEGqivVeaZpviQW89X1ix0imvZCV2pDNe2mVkc15UFXasokUcs05YzEYt9orRNFXxB1dAR0ANFUk7qq0bFEhWraCzKCNUL6omWKrLNYKOkLy7SmiuwI7QCiWJvQDiDqaWxaGzl/hSn6mMVixfSsZopYUpOWKc4zoeev1uLmpU+X1O3bLsbFEIcR11WximG9L65fTusQu7L5C5zG0J9imLrSW2syPPAl3XXnfjd1G/x+Cbu8lfj0y/9+w7GKf3BPrsYu7I/Drp9O+fz59fsH
I mean this isn't quite the same issue, but I'm sure its related. I just want the top part in a nice, optimized compound path.

**Comment by lehni** [comment] 2017-05-08 21:16
Thanks! That works. I wonder what is going wrong here...

@iconexperience looks like we have some more work to do!

**Comment by fsih** [comment] 2017-06-19 19:22
I have a relatively small repro case for this: [sketch](http://sketch.paperjs.org/#S/7VRNb6MwEP0rFhfMxlg23yTltOdKK632FHIg1GmsOgYZ05U24r+vDcVpt91f0HKBmfdm3jDSvKsnmwvztt7PJ6bbs4e8tnuw8XOjwLHrBGvkL8k1AxU4jbLVvJPQhJchANda1tryFBtGoXc2PHUK2hSvyA7wu5mJBZOP+mzizealqtb8BDmoKkBcptZLH6M0l+3JAbeikwwGu4UxLS/b3xB6R+QHPNoZ4dIAgSuXA1N6q9XIprV6AbFil+751tNp2o5zblGRFtKjkre/mywsrXrf6PNgavYHk5oD3I/DGUr2G/wwIfTvaYajJIlzFNI4wjktYhFGJS6zPM0QxXGZFFFLEAEhTXBZxHmBCM7KPKFzJioyU0tTnBWUlu0LhFYuWBG0ct9nhJMLX+s5uXDVc3Kh01sx5KYDDkRuvo9yf/wg+O9SErMUw47tUhJMaUyjr63c5xmmuZnEbiXFKTHfn2ortTSuARbbMEdljQPcLTf2zjqAeWbEHv2JC/G9E6a4Ar56PEJ/A/m3lAQbH334Gfi7f1po1chBNMY7UkIQiAixE03roc+28mDav7ZCOFdb3gK/naMfVS+Yf0NvEquAcdmjYs1T33GpB2+7P0x/AQ==)

There are 3 paths here. If you unite the first two, you can see that the result is already not right, the overlapping paths are not merged into one:
![screen shot 2017-06-19 at 15 20 13](https://user-images.githubusercontent.com/2855464/27301938-0440a296-5503-11e7-9ed0-a264ea44be6b.png)

Then uniting those with the 3rd path, the 2nd path gets "erased":
![screen shot 2017-06-19 at 15 20 36](https://user-images.githubusercontent.com/2855464/27301961-15d0919c-5503-11e7-822e-fe0008a8c9ec.png)

**Comment by fsih** [comment] 2017-07-27 21:12
@iconexperience

Any ideas based on this new info?

**Comment by iconexperience** [comment] 2017-09-07 06:43
@fsih I am not sure if the behavior your example is caused by the same bug as in the original code. I will first try to solve the original issue and then we will see if that fixes yours.

**Comment by iconexperience** [comment] 2017-09-07 06:46
Here is a simplified version of the original test case:

```javascript
var path = new CompoundPath('M24,38l2,1l-2,1l-2,-1z M26,39l2,1l-2,1l-2,-1z M28,40l2,1l-2,1l-2,-1z ')

path.fillColor = 'black'
path.scale(6)
path.translate(200, 200)
var united = path.unite()
united.fillColor = 'blue'
united.translate(0,100)
```
![image](https://user-images.githubusercontent.com/2122773/30149722-0443f0ba-93a9-11e7-8db7-3aff356a2374.png)


<a href="http://sketch.paperjs.org/#S/bVDLCoMwEPyVkEsUYokPxAo9eRYKPdYeoqYoxo3E2EJL/73RSgttLwMzszuz7B0D7wVO8aETpmowxZWqZ37hGg3cNGiHQFxRpvpBTVDvreSQPIhomMiA+tJbwfNvKA9iGm7/yAmN2I9M3AIKmDs251bKTEmlbRspJa86sjpjxaVwYnelRnMYJTfCCRijyIJ15lMnaI2o7foytjDHWi/5O38S5G19Ehn1l7gC7BdKLXg3qBbMiNPj6fEE">Here is the sketch</a>

**Comment by iconexperience** [comment] 2017-09-07 08:25
What is strange is that the result is correct if we unite the child paths of the CompoundPath separately. If the middle path is added to the CompoundPath (with only the two remaining paths as children), the result is correct:

```javascript
var path = new CompoundPath('M24,38l2,1l-2,1l-2,-1z M28,40l2,1l-2,1l-2,-1z ')
var path2 = new Path('M26,39l2,1l-2,1l-2,-1z');

path.fillColor = 'black'
path.scale(6)
path.translate(200, 200)
path2.fillColor = 'red'
path2.scale(6)
path2.translate(200, 200)

var united = path.unite(path2)
united.fillColor = 'blue'
united.translate(0,100)
```
![image](https://user-images.githubusercontent.com/2122773/30153409-d0a2176a-93b6-11e7-89b1-7d0e3cadf142.png)

<a href="http://sketch.paperjs.org/#S/bZDLCsIwEEV/JWSTFqK0qYgPXLkuCC6ti9iOWBonJU0VFP/dWFPFx2bgzp17ZpgrRXkEOqPrCmx+oJzmunjokzSklvZAFgThTJb6WOsWi5VrBSwVI55MlOCxGvgyiC8kFRM+in7aLMywxwnP6zljnky/AyycZ5jhY3y4L5VaaqWNy7GdknnFvNPkUkEwDr20RmKjpIVARBEnrnhHfDIMFKw3PhHiP+N5e4ulhcIBumWdCrqQm3h636e2wF7WGxzx2FHdm3cGZFXrEm1DZ5vt7Q4=">Here is the sketch</a>

**Comment by iconexperience** [comment] 2017-09-07 09:27
I am pretty sure that the problem is cause by <a href="https://github.com/paperjs/paper.js/blob/c403c86a23f54f07bb7e9448c7f05df5cebb464c/src/path/PathItem.Boolean.js#L1171">this loop</a> in `path/PathItem.Boolean.reolveCrossings()`. After running through the loop, the child path in the middle is empty.

**Comment by iconexperience** [comment] 2017-09-07 10:04
@lehni As I understand it the loop removes segments in cases of several subsequent overlaps. I think the problem is that it currently does not check if these overlaps are all with the same path. If we add a check for this, this issue should be solved. A simple and clumsy solution would be to replace <a href="https://github.com/paperjs/paper.js/blob/c403c86a23f54f07bb7e9448c7f05df5cebb464c/src/path/PathItem.Boolean.js#L1175">Line 1175</a> with this:
```
if (hasOverlap(prev) && hasOverlap(next) && prev._intersection._path._id == overlaps[i]._path._id && next._intersection._path._id == overlaps[i]._path._id) {
```

A better implementation would be to replace `hasOverlap()` with a function that also checks if the path is the same, something like this:

```
function hasOverlapOnPath(seg, path) {
    var inter = seg && seg._intersection;
        return inter && inter._overlap && inter._overlap._path._id == path._id;
    }
}
```

**Comment by iconexperience** [comment] 2017-09-07 11:00
@fsih
The problem that you are seeing has a diffent cause. This seems to be a problem with `tracePath()`. I recommend we open a new issue with this test case.

**Comment by lehni** [comment] 2017-10-04 15:25
@fsih @iconexperience I've created a separate issue for that one here: #1387

**Comment by lehni** [comment] 2017-10-04 15:52
@iconexperience thanks for solving this one!

**Closed** 2017-10-04 15:52 UTC
Labels: cat: boolean-operations, type: bug
