### ISSUE TITLE
path.simplify memory leak / heap pick / GC

### ISSUE THREAD

**Issue by v1r** [paperjs/paper.js#750] opened 2015-08-08 00:06 UTC
![gc](https://cloud.githubusercontent.com/assets/321221/9148147/0c648a68-3d41-11e5-9198-8c79946285be.PNG)

![image](https://cloud.githubusercontent.com/assets/321221/9148219/a10de276-3d42-11e5-9c59-c3459ee4b7de.png)

Hi there, 

Thanks for this awesome library! 

There is a huge performance issue with the path simplify method when its used with drawImage.. 

How to reproduce : 
- create a canvas next to the paperjs canvas
- Draw path or multiple paths in the paper  canvas
- onEach mouseUp
  - Simplify the path 
  - use the drawImage method to copy papercanvas on the other canvas. 

Thank you to look at this problem asap. 
Cheers!

**Comment by lehni** [comment] 2015-08-10 13:20
Could you provide a test-case? I don't understand why the use of drawImage should cause the issue. simplify() is a complex operation, so I'm not surprised that it creates lag. Are you sure GC is the cause?

**Comment by v1r** [comment] 2015-08-12 22:08
Hi, I figured out the main cause. 
The lag is caused by an agressive time interval that runs every 1/60 ms.. 
Thank you for your answer.

**Comment by lehni** [comment] 2015-08-17 12:36
I am closing this issue then. Feel free to reopen if you think there's a bug still.

**Closed by lehni** 2015-08-17 12:36 UTC
