### ISSUE TITLE
[0.9.21] ReferenceError: \u00C2 is not defined paper-full.js:725

### ISSUE THREAD

**Issue by THEZENEAG** [paperjs/paper.js#635] opened 2015-02-09 18:11 UTC
I am getting this error in all modern browser with 0.9.21. Weird because there is no such string in the source.

![index2_html](https://cloud.githubusercontent.com/assets/7512128/6112316/64f80766-b08f-11e4-8956-8df715b36f40.png)

![mozilla_firefox](https://cloud.githubusercontent.com/assets/7512128/6112279/3e1be3e2-b08f-11e4-8ee5-f0d6d8968692.png)

**Comment by eljefedelrodeodeljefe** [comment] 2015-02-09 18:13
Sorry, I posted this with the Organisation. Please refer to me for this issue.

**Comment by iconexperience** [comment] 2015-02-09 20:41
I think this is a duplicate of #602, at least it seems to be in the same line.

**Comment by eljefedelrodeodeljefe** [comment] 2015-02-09 20:44
It is. Thanks.

**Closed** 2015-02-28 18:13 UTC
