### ISSUE TITLE
Unable to set bounds, once the width or height is zero

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#771] opened 2015-09-08 07:31 UTC
```js
var rect = new Path.Rectangle(new Point(0,0), new Size(10,10))
rect.fillColor = 'black'

rect.bounds = new Rectangle(new Point(0,0), new Size(20,20))
rect.bounds = new Rectangle(new Point(0,0), new Size(0,0))
rect.bounds = new Rectangle(new Point(0,0), new Size(20,20))
```

**Comment by franverona** [comment] 2015-09-08 09:44
You can use *expand* function to provide a new size to your rectangle bounds:

```js
var rect = new Path.Rectangle(new Point(0,0), new Size(10,10))
rect.fillColor = 'black'

rect.bounds.expand(10,10);      // Size: 20, 20
rect.bounds.expand(-20,-20);    // Size: 0, 0
rect.bounds.expand(20,20);      // Size: 20, 20
```

But the whole Path will be expanded from center point, so you will have to move it to the original position again.

Regards,

Fran

**Comment by lehni** [comment] 2015-09-08 11:52
Dupe of #558

**Closed by lehni** 2015-09-08 11:52 UTC
