### ISSUE TITLE
paper-full.js:15726 Uncaught SyntaxError: Unexpected token (9:9)     at raise (paper-full.js:15726)     at unexpected (paper-full.js:16366)     at parseObj (paper-full.js:16844)     at parseExprAtom (paper-full.js:16799)     at parseExprSubscripts (paper-full.js:16730)     at parseMaybeUnary (paper-full.js:16716)     at parseExprOps (paper-full.js:16682)     at parseMaybeConditional (paper-full.js:16669)     at parseMaybeAssign (paper-full.js:16655)     at parseExpression (paper-full.js:16644)

### ISSUE THREAD

**Issue by sandeep318kumar** [paperjs/paper.js#1798] opened 2020-04-13 04:27 UTC
# Description/Steps to reproduce

# Link to reproduction test-case

# Expected result

# Additional information

**Comment by sapics** [comment] 2020-04-13 04:51
Duplicate of #1799

**Closed by sapics** 2020-04-13 04:51 UTC
