### ISSUE TITLE
documentation for support of svg features

### ISSUE THREAD

**Issue by irisjay** [paperjs/paper.js#1410] opened 2017-11-10 09:03 UTC
I understand that paperjs supports most, but not all of svg features (for import and export), so is there a list somewhere which documents which are or are not supported? Thanks!

**Comment by lehni** [comment] 2017-12-07 10:23
No there isn't.. There's also unfortunately not time to create one. I'm closing this issue as it's not a bug.

**Closed by lehni** 2017-12-07 10:23 UTC
