### ISSUE TITLE
Cannot combine ctrl+a

### ISSUE THREAD

**Issue by pulse-kostis** [paperjs/paper.js#1028] opened 2016-03-31 12:53 UTC
Hi, I need to implement ctrl+a to select all the items on the canvas using the code below

`
function onKeyDown(event) {
if (event.modifiers.control && Key.isDown('a')) {
        project.activeLayer.selected = true;
    }
}
`

but it does not work. However, if I replace 'control' with 'shift' it works:

`
function onKeyDown(event) {
if (event.modifiers.shift && Key.isDown('a')) {
        project.activeLayer.selected = true;
    }
}
`

Am I missing something?
Thanks

**Comment by lehni** [comment] 2016-03-31 14:34
What browser / OS are you on?

**Comment by pulse-kostis** [comment] 2016-03-31 21:58
I am using chrome/win 7 but I need it to play everywhere. Is this hard to do?
Thanks

**Comment by pulse-kostis** [comment] 2016-04-01 06:46
Actually, I have a json object taken from project.importSVG that is the attached one. The code I use for this is the following:

`var textObject = project.importSVG("<svg xmlns='http://www.w3.org/2000/svg' version='1.1'>" + svg + "</svg>", { expandShapes: true, applyMatrix: true });
        textObject.fitBounds(view.bounds);
        textObject.scale(1);

var paths = textObject.children[0].children;

        for (p = 0; p < paths.length; p++) {
            paths[p].closed = true;
            paths[p].fillColor = 'white';
            paths[p].strokeColor = 'black';
        }

        for (i = 0; i < paths.length; i = 0)
            project.activeLayer.appendTop(paths[i]);`

if I replace the last two lines with what you suggest, it does work: the paths cannot be selected on mous down etc...

[ObjectFromProject.ImportSVG.txt](https://github.com/paperjs/paper.js/files/199078/ObjectFromProject.ImportSVG.txt)

**Comment by lehni** [comment] 2016-04-04 23:49
Same issue as #1006, closing.

**Closed by lehni** 2016-04-04 23:49 UTC

**Comment by lehni** [comment] 2016-04-04 23:54
PS: Have you tried the prebuilt version yet? I'm not able to reproduce it there:

https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by pulse-kostis** [comment] 2016-04-05 06:30
Thanks, it worked.
