### ISSUE TITLE
<script type="text/paperscript" src="js/myjs.js" canvas="myCanvas"> </script>cant work

### ISSUE THREAD

**Issue by nanmenxue** [paperjs/paper.js#669] opened 2015-04-03 06:57 UTC
chrome says XMLHttpRequest cannot load file:///Users/wai121/Desktop/dfabwork/paper/js/myjs.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource. why?i need your help

**Comment by lehni** [comment] 2015-04-04 12:00
Duplicate of #636. It's not a paper.js issue, and there is a simple solution to this common problem: Serve the local website from a local web-server, e.g. through http://anvilformac.com/

**Closed by lehni** 2015-04-04 12:00 UTC

**Comment by nanmenxue** [comment] 2015-04-04 13:31
thank you .but i am still confuse.you mean paperscript tag cant be uesd on local?would you mind to say more details.

**Comment by nanmenxue** [comment] 2015-04-04 13:31
thank you .but i am still confuse.you mean paperscript tag cant be uesd on local?would you mind to say more details.

**Comment by nanmenxue** [comment] 2015-04-04 13:31
thank you .but i am still confuse.you mean paperscript tag cant be uesd on local?would you mind to say more details.

**Comment by lehni** [comment] 2015-04-04 14:18
Due to browser "same origin policy" restrictions, you cannot get access to the contents of files from the local file system anymore, hence the error. The work-around is to either disable the restriction in the browser (e.g. http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome, http://stackoverflow.com/questions/17088609/disable-firefox-same-origin-policy), or serve all files through a local web-server, so they have the same origin.

search for "same origin policy" and "local file system" and you will find lots of information, e.g.:

http://stackoverflow.com/questions/12587731/same-origin-policy-google-chrome-canvas-and-file-scheme
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy
https://developer.mozilla.org/en-US/docs/Same-origin_policy_for_file:_URIs

**Comment by nanmenxue** [comment] 2015-04-04 15:50
sorry ,my english is poor .i want to say it is very nice of you .let me read your reply.if i still have question i hope i can ask you again.
