### ISSUE TITLE
"keepalive" attribute does not work

### ISSUE THREAD

**Issue by boraxeater** [paperjs/paper.js#1415] opened 2017-11-21 19:41 UTC
# Description
"keepalive" does not work. After minimizing and changing tabs, the animation stops.

# Example:
https://stratkey.com/rectangle.html

# Expected Result
Expected result would be that it doesn't stop the animation on unFocus and minimize.

**Comment by lehni** [comment] 2017-12-07 10:36
Duplicate of #1395, please search first.

**Closed by lehni** 2017-12-07 10:36 UTC
