### ISSUE TITLE
Subtract/Exclude on a circle path with an arc of same radius hangs

### ISSUE THREAD

**Issue by voneiden** [paperjs/paper.js#719] opened 2015-07-01 08:05 UTC
Sketch (uncommenting last line leads to hang): http://sketch.paperjs.org/#S/hVHBisIwEP2VIafKZrUeRBA8SJHd07Lgse0hJhGDMZE0lYVl/92ZJlXxsqfMvPcyb17yy5w4a7Ziu5OO8sg4k15RH4QyfQdrWJRNaNzFdyYa7xColyWHZdkSPJtBFbSIGqQJ0mrCUoXCbxGP02roihrvlC2HNHby0E0PxtrKWx/wRsOCVg17Yu++b2sYa6Kz+SZIuIrQUYsnHII/04ro9p6s2pGKPhMv+NWIOTEJpi2f5udwAm3mBFGRg6F1QXZ8mMBx/iQrXiLtba9TJuL+CbT9kbZX43OCcArIncPn5utjl0T5aXSSFkgPzvh3e1z3dPHGxY6t6vbvBg==

Issue applies also to crescent shapes that have exactly same outer radius.

**Comment by iconexperience** [comment] 2015-07-09 18:31
Hi @voneiden,

this seems to be a duplicate of #648. If curves are (almost) identical, thousands of intersections can be found, which can cause the program to hang. Actually, it does not hang forever, just for quite a long time (about three minutes on my machine).

Sorry that there is not good solution for the issue yet.

**Comment by voneiden** [comment] 2015-07-09 19:43
No problem. Assuming it's not going to be solved anytime soon, perhaps a small warning about possible performance issues  in the docs would be a good idea. I can work around the issue since I know it exists, but somebody else might end up having a hard time figuring whats wrong with their code especially if the freeze happens in a more complex environment.

Anyway, thanks!

**Comment by lehni** [comment] 2015-08-26 15:55
Who would have thought! I managed to address these issues in the current code base, and the work in the `boolean-fix` branch has landed on `develop`! Time to test thoroughly, but I'm closing these bugs. Feel free to reopen if similar problems arise.

**Closed by lehni** 2015-08-26 15:55 UTC

**Comment by voneiden** [comment] 2015-08-27 06:25
Neat! I'll give it a go.

**Comment by lehni** [comment] 2015-08-27 10:37
PS: You need to close the arc for the example to work. This relates to #757

```js
radius = 50
position = [70, 70]
// Create circle
circle = Path.Circle([0, 0], radius)
circle.fillColor = "red"
circle.position += position

// Arc vars
var from = [0, -radius]
var to = [0, radius]
var via1 = [radius, 0]

// Create arc 1
arc = Path.Arc(from, via1, to)
arc.fillColor = "blue"
arc.closed = true;
arc.position += position;
arc.pivot = arc.bounds.leftCenter;
// arc.rotate(45);

// Exclude circle and  arc, HANGS
var res = circle.exclude(arc);
res.position += [0, 120];
````
With that, I get these results:

![screen shot 2015-08-27 at 12 37 08](https://cloud.githubusercontent.com/assets/213275/9518627/678a69ea-4cb8-11e5-9f21-92c0471f172a.png)
![screen shot 2015-08-27 at 12 37 16](https://cloud.githubusercontent.com/assets/213275/9518631/6c771138-4cb8-11e5-87ed-a8bc7680f464.png)
