### ISSUE TITLE
Is rgb Color buggy when red = 0?

### ISSUE THREAD

**Issue by maen007** [paperjs/paper.js#1536] opened 2018-10-03 08:48 UTC
First off: Paper.js v0.11.5 

I used a color picker for testing purposes and I tested a lot!
Easy case:
`var color = new Color (r,g,b,alpha);
console.log(color);`
Here my results, input copy-pasted from picker, outcome from console:
I: rgba(50, 50, 50, 0.5)
O: { red: 0.2, green: 0.2, blue: 0.2, alpha: 0.5 } -> correct
I: rgba(50, 0, 50, 0.5)
O: { red: 0.2, green: 0, blue: 0.2, alpha: 0.5 } -> correct
I: rgba(50, 50, 0, 0.5)
O: { red: 0.2, green: 0.2, blue: 0, alpha: 0.5 } -> correct
I: rgba(0, 50, 50, 0.5)
O: { red: 0, green: 0, blue: 0 } -> **wrong!**

As long as red is "0", I always get the last result!

**Comment by lehni** [comment] 2018-10-03 09:27
I don't understand. How to you create your color objects from `'rgba(0, 50, 50, 0.5)'` ?

This works for me:

http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfFj8soSixSS83PyixRsFfJSyxWcwWwN9aL0pEQNAx0FUyg20DPVVNe0jslLzs8rzs9J1cvJT9cAa9S0BpqXVJSamF2Qn5lXUqxkFR1bCwA=

**Comment by maen007** [comment] 2018-10-03 10:00
According to the [reference](http://paperjs.org/reference/color/#color-red-green-blue), I created it like this:
`console.log("RGB: " + RGB.r + ", " + RGB.g + ", " + RGB.b + ", " + RGB.alpha);
 var Color = new Color(RGB.r,RGB.g,RGB.b,RGB.alpha);
 console.log("Fillcolor: " + Color);`

And with input rgba(0, 50, 50, 0.5), console gives the following:
RGB: 0, 0.2, 0.2, 0.5
Fillcolor: { red: 0, green: 0, blue: 0 }

**Comment by lehni** [comment] 2018-10-03 10:05
It also says in the docs that the values need to be between 0 and 1, but yours are 0..255.

I still can't reproduce your issue though even with wrongly scaled RGB values:

http://sketch.paperjs.org/#S/JY67CsMwDEV/RWhKwJguWRw69RM6Nh1s1zglrhSU0A4h/14/piNdrg46kOwnoMH7EnY/o0LPr7J/rYBEB1c4QAxcFEQDQ4ZrsGmdbc71AOdEpe05seQ+hR/c6txlgRZVPDo2uIZ63Y8TeaaNU9CJY1cF/Zh/cBLssvKb9g3N43n+AQ==

Could you share an actual sketch that reproduces your issue?

**Comment by maen007** [comment] 2018-10-03 10:12
Sorry, perhaps there is a misunderstanding!??? All colors which are inserted are between 0 - 1.
The result of console shows for console.log("RGB: " + ...) from above shows:
- RGB.r = 0; 
- RGB.g = 0.2;
- RGB.b = 0.2;
- RGB.alpha = 0.5;

These values are inserted next line! Or not???

**Comment by maen007** [comment] 2018-10-03 10:19
How can I create a sketch???

**Comment by maen007** [comment] 2018-10-03 10:40
http://paper-layer-ordered.druckgott.de/
Click on the sun, in canvas again, change to whatever with red = 0. 
Enjoy ;)

**Comment by maen007** [comment] 2018-10-03 10:54
and her's the sketch, now I know how this works ;)
[sketch](http://sketch.paperjs.org/#S/jVRNb+IwEP0r00grbBGFpGgvIPaw249LtVqxR8xWSRiCVWMjx7RIKP99HYekTqiq+mBlxu+9+bAn50Cmewxmwd8XNPkuCINcbWr7NdWwfPwJCzhXcyZrs3wtngs0v5RQ2vq3R5kbriQQyJ2LnpkEu2qsRouQ+AZLLO5PBzJhjJDVP7oeU8bohM7foUssj8JYuMYIT5gTp+YjXMQnXpo/qHOUNbYhrZK1B9untgJ7NoRH5UFwQ0YhjHxVjXe84OYqz805DqdVl6JtQpSKwy61wOTic5GirdL3ab4jbSMIN7gPudzgqW1FL7Xfx32G2hXqIjfV1qQ2Vr34ljgJuFnA1Ne5HDYqxFNcxWsKPyAZgrtMu8B9EkwgieN5n1T1TRQlfiri0T3qB7S6zo/KXCwgpq7LA/H5QM5nJA2j+DrjtmFkX2dMae/ur1lVe23NnitZKoGRUAVhgaXOgAUwvpQ2tkb47iiGjmzocHH997rlQrSzV79Y902ceugk3Z6FV+R+Yg9Wxk3YJb1Otl+NN/v2Xpn0h5+MdJGlJP4Wwm23xdF3aufL/kEyjenLQXFpymC2Wlf/AQ==)

**Comment by lehni** [comment] 2018-10-03 11:06
Ok I see now... You're code provides some of these values as strings, that's why it doesn't work:

http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfGT8/OK83NS9XLy0zXyUssVnPNz8os0qhWKrBTUDdR1FNJBtJ4RkJUEZSnUamoC9ScVpSZmF+Rn5pUUK1lFx9YCAA==

That is a little bug, I guess. You can fix your code by coercing the values to numbers, e.g. `+RGB.r`, etc.

But why do you write your own parser? This already works:

```js
var color = new Color ('rgba(0, 50, 50, 0.5)');
```

**Comment by maen007** [comment] 2018-10-03 11:15
Thank you very much! I appreciate your support! 
I couldn't find your solution in the reference, that's why!!! 
Doesn't matter.

**Comment by maen007** [comment] 2018-10-03 13:36
- Add JSDocs for Color(string) constructor

- Handle string values in color components

**Comment by lehni** [comment] 2018-10-03 14:48
Closed in da3a36230f1828bac6e62b385dae6d49f6a2eac5

**Closed by lehni** 2018-10-03 14:48 UTC
