### ISSUE TITLE
Mouse move  event occurs everytime

### ISSUE THREAD

**Issue by kannangandhi** [paperjs/paper.js#646] opened 2015-02-27 14:49 UTC
Hi,

 We are using below code  for show the image. 

if (raster) {
            raster.remove();
            initPaperScope();
        }
        raster = new paper.Raster(pageURL);
        raster.on('load', function () {

            raster.size = paperScope.view.viewSize;

            raster.position = paperScope.view.center;

            paperScope.view.draw();
});

After execute the above code, "mousemove()" in paper.js function called every mouse move. 
function mousemove(event) {
.
.
.
.
}
How can we avoid this issue, Please suggest any solutions
Thanks
kannan

**Comment by lehni** [comment] 2015-02-28 18:05
I don't understand what the issue is? Paper.js does install its own mouse handlers when initializing the view. But what's the issue with that?

**Comment by lehni** [comment] 2015-04-04 13:29
Closing for the lack of a respsone.

**Closed by lehni** 2015-04-04 13:29 UTC
