### ISSUE TITLE
paper.view.center values aren't updated before resize event is fired, causing resizing to fail (always using previous/old values)

### ISSUE THREAD

**Issue by Friksel** [paperjs/paper.js#1203] opened 2016-11-16 11:53 UTC
First of all: nice lib! Having fun working with it!

That said, using the latest paper.js (0.10.2) there is a problem in the automatic resizing behaviour. No resizing is done when device orientation changes for the first time (rotating a device). From the second device orientation change on resizing IS working fine, but the first orientation change doesn't set paperjs to resize well. The paperjs resize-event is being triggered though.

This is clearly not a bug n Android nor the browsers, 'cause other animations (using other libs and own resize functions) work fine. The orientation change-events fired in the browsers are working as expected.

The exact same problem is also there in the paperjs examples as found in the latest paperjs. For example in examples/Animated/AnimatedStar.html. (Seen in Chrome and Firefox on Android).

paperJS is triggering a resize-event though. But somehow the resizing is not being done (right).

**Comment by Friksel** [comment] 2016-11-17 12:27
Resizing seems to fail also on Windows browsers while users switch the browserwindow to maximized or back to restored window size (middle button on each topright buttons of each window). (Failing in Chrome, Firefox and IE11).
Only during initialisation or manually resizing the browserwindow (by dragging the window to get a new size) let paperjs resize well.

**Comment by Friksel** [comment] 2016-11-17 13:10
Alright, I just located the bug in more detail:
The value of paper.view.center value isn't updated before paperjs fires the resize event. Instead, paperjs ALWAYS returns the PREVIOUS center x/y values. That explains why setting an object to the center with the build in center position isn't working when maximizing a window or orientation change on mobile. 
When manually changing the browserwindowsize with a drag it SEEMS LIKE IT'S WORKING, BUT IT'S NOT! It's always at least 1 pixel off, 'cause the resizing is done with OLD values!

So using resize with this function and using the center position (like in the paperjs tutorias) should work, but always fails:
```
function onResize() {   
        path.position = p.view.center; // p.view.center isn't updated in time, so this bugs!!
    }
```

And this is workaround works (but obviously isn't the best way to do it):
```
function onResize() {   
        path.position.x = p.view._viewSize._width / 2;
        path.position.y = p.view._viewSize._height / 2;
    }

```

With the bug located, it seems to be just a matter of setting the centerposition BEFORE throwing the resize event instead of after. Should be an easy bug to fix in the lib now I'd say...

**Comment by Friksel** [comment] 2016-11-17 13:18
btw this bug was not there in paperjs 0.9.21. On that version (just tested) the center-position was working fine inside de resize handler

**Comment by lehni** [comment] 2016-11-20 20:10
Could you test the latest development builds also? This kind of sounds like a bug I've recently fixed, probably since the last release... http://paperjs.org/download/#development-builds

And could you provide a simple test case for me to test this?

**Comment by Friksel** [comment] 2016-11-26 11:21
Yes, a simple test case are your own examples, like the example I wrote about.
I don't have much time now and already had too much time spent to debug this, but I tried the dev-build and downloaded the master-zip, but it doesn't contain javascript files in the dist-folders and I don't have the time to (find out how to) build one myself rightnow. 
I spent a lot of time to debug this already and think this shouldn't be too much of a problem to fix for you anymore now it's clear where the problem is.

**Comment by lehni** [comment] 2016-11-29 00:18
These should work:
https://github.com/paperjs/paper.js/raw/prebuilt/module/dist/paper-full.js
https://github.com/paperjs/paper.js/raw/prebuilt/dist/paperjs.zip

I'd appreciate if you could quickly test with your code and confirm.

**Comment by Friksel** [comment] 2016-11-29 15:07
Thanks. Unfortunately it wasn't possible to test it with my code, 'cause I worked around the bug and changed to much to the project for a quick test. Therefore I just tested with your AnimatedStar example; in the last released paperjs version the problem is still visible. Replacing the paper lib by the latest dev you sent in a zip-file all seems to work now. I'd say time for a new release ;)

**Comment by elmath** [comment] 2016-12-01 18:55
I had a similar issue, and the problem is fixed by the new version you provided.

**Closed** 2016-12-01 23:23 UTC
