### ISSUE TITLE
view.center is mutable

### ISSUE THREAD

**Issue by arctwelve** [paperjs/paper.js#947] opened 2016-02-07 08:04 UTC
Is it a conscious decision to not return a clone of the view center point?

```javascript
let c = view.center;
c.x = 200;
```

Later on in the code other calls to `view.center` will be inaccurate. It seems unusual not to return a clone of the point in the getter.

**Comment by lehni** [comment] 2016-02-07 09:58
Yes, this is by design: The getter is returning a `LinkedPoint`, which is an internal class that propagates changes up the chain of ownership. We use this on Item quite a lot, e.g. `Item#bounds`, `Item#position`, etc. I am not sure what you mean by "will be inaccurate" though? As for unusual or not, I guess it's a design choice. We decide that the availability of accessors allows for nice simplifications in code that are easier to teach, e.g.:

`item.bounds.center = ... `
`item.position.x += ...`

etc.  But it does make for the occasional awkward moment where you need to explicitly call `clone()`.

**Closed** 2016-02-07 09:58 UTC

**Comment by arctwelve** [comment] 2016-02-07 16:35
> I am not sure what you mean by "will be inaccurate" though?

Only that you'd expect `view.center` to always be the absolute center when you assign it. Since `view `is global, one class or circumstance could change the value of `center`'s internals -- a separate class asking for `view.center` wouldn't know it's 'dirty'. Not a big deal once the behavior is known.

**Comment by lehni** [comment] 2016-02-07 17:40
Well, it is. If you change it, you actually change the view's center.

**Comment by arctwelve** [comment] 2016-02-14 00:37
Is what? A big deal? No, it's just bad design.

**Comment by lehni** [comment] 2016-02-14 00:54
What I meant to say is: `view.center` is always the center, and since it's not a clone, changes to the view's matrix will be reflected in this object. 

Also, please let's keep it friendly here.
