### ISSUE TITLE
RBG, grey values from getPixel are inaccurate

### ISSUE THREAD

**Issue by SkepticaLee** [paperjs/paper.js#1219] opened 2016-12-15 16:30 UTC
If I create a grey image, load it as a Raster, then Raster.getPixel([x, y]) returns values that differ from the values obtained for this grey value in other programs (IrfanView, GIMP, Imagemagick) for all values of R = G = B < 250 / 255.

So, for example with an image where R = G = B = 249 / 255, the values returned are:
red 248 / 255
green 248 / 255
blue 248 / 255
gray 247.9752 / 255

(Values multiplied by 255 for easier understanding).

Please mark this as a bug.

**Comment by lehni** [comment] 2016-12-15 16:50
This is what we return from `getImageData()` it may be that it's a question of attached color profiles?

**Comment by lehni** [comment] 2016-12-15 16:50
See here: https://github.com/paperjs/paper.js/blob/develop/src/item/Raster.js#L598

**Comment by SkepticaLee** [comment] 2016-12-15 17:35
No. image.getImageData ([1, 1, 1, 1]).data returns [ 248, 248, 248, 255 ] instead of the expected [ 249, 249, 249, 255 ]. Color profile is ordinary RGB.

**Comment by lehni** [comment] 2016-12-16 01:56
Yeah but that's surely not a Paper.js bug? This is happening in the canvas internals, no?

**Comment by SkepticaLee** [comment] 2016-12-16 10:26
No, it's not happening when I look at the values directly in JS.

<script>
canvas = document.getElementById("myCanvas");
ctx = canvas.getContext("2d");
ctx.fillStyle = "rgb(249,249,249)";
ctx.fillRect(0,0,200,100);
pixel = ctx.getImageData (50, 50, 1, 1);
document.write (pixel.data[0], pixel.data[1], pixel.data[2]);
</script>

Returns 249249249 as expected.

Note that the HTML 5.2 standard requires that the pixel values not vary between <img> and <canvas> elements.

Also why the unusual value for "gray"? Since R = G = B, the grey value has to be the same regardless of which model is used (brightness, luminance) to translate the colour values.

**Comment by iconexperience** [comment] 2016-12-18 20:22
Paper.js uses "luma" when calculating the grey value, using this function:

`luma = r * 0.2989 + g * 0.587 + b * 0.114`

The problem is that `0.2989 + 0.587 + 0.114 = 0.9999`, while the result should preferably be `1`.

I do not think this issue is of any importance but this discussion can easily be resolved by setting the coefficient for the red component to `0.299`.

Here is more information on luma: https://en.wikipedia.org/wiki/Luma_(video)

**Comment by lehni** [comment] 2016-12-19 02:37
I thought the problem was that he gets 248 for all components, while it should be 249?

**Comment by lehni** [comment] 2016-12-19 02:39
@SkepticaLee when you draw directly it's different, but you're comparing apples and oranges. What you need to test in pure JS is loading the same image and drawing it to the canvas, then getting the pixel values. I believe you'll see the same shift then too.

**Comment by iconexperience** [comment] 2016-12-19 06:41
@lehni Ooops, sorry.

**Comment by lehni** [comment] 2016-12-31 09:54
I am going to close this issue until there is evidence that rendering the same image in pure JS , and getting pixels from the canvas, yields different results.

**Closed by lehni** 2016-12-31 09:54 UTC
