### ISSUE TITLE
curve.getLocationAt()should return null if argument offset is null.

### ISSUE THREAD

**Issue by bildlich** [paperjs/paper.js#660] opened 2015-03-18 00:37 UTC
Hey Jürg,
I may have found a bug in `path.getOffsetOf(point)`. When `path` has multiple curves the offset will be wrong as soon as `point` is not on the first curve. Example:

    path = new Path(new Point(100,100),new Point(200,100),new Point(300,100));
    path.strokeColor = 'black';
        
    var offset = 0;
    while (offset < path.length) {
        var point = path.getPointAt(offset);
        // The following computes 0 after entering the path's second curve.
        console.log (path.getOffsetOf(point));
        offset += 19;
    }

I believe the problem is in `Curve#getIndex()`. It always returns 0 which breaks the length calculation in `Path#_getOffset()`.

**Comment by iconexperience** [comment] 2015-03-18 06:57
Can you say where `Curve#getIndex()` always returns 0? I checked with your example and it seems to return the correct value:

<pre>
path = new Path(new Point(100,100),new Point(200,100),new Point(300,100));
path.strokeColor = 'black';
path.fullySelected = true;

for (var i = 0; i &lt; path.curves.length; i++) {
    console.log("CurveIndex: " + path.curves[i].getIndex());
}
</pre>

**Comment by iconexperience** [comment] 2015-03-18 07:38
After looking a bit deeper into this issue I think I found what causes this bug. First, here is the call tree:

<pre>
path.getOffsetOf()
-> path.getLocationOf()
  -> curve.getLocationOf()
     -> curve.getLocationAt(curve.getParameterOf())
</pre>

The problem is in the last line. `curve.getParameterOf()` returns `null` if the point is not on the curve, which is correct. **BUT** `curve.getLocationAt()`returns a `CurveLocation`object, even if the `offset`argument is `null`. See yourself:

<a href="http://sketch.paperjs.org/#S/ZY69CsJAEIRfZbnqAiFG7SIW9haCZZLivCxJyLkb7kcL8d29OwQLi4WZ+WB2XoLUHUUjrgt6PYlSaB6SX5Wf4AiET7hEKbPgmbzc1nUZryh/0e4/2n+j4tDZjnSwD4x1qbXKxrV1n1HGTI4NVoZHmWk1oj+zVn5mOnlJwZjYBJsNuImDGcCiD5Yggbj5ZlEta/rrRNP27w8="><pre>path = new Path(new Point(100,100),new Point(200,100),new Point(300,100));
curve = path.curves[0];
console.log(curve.getLocationAt(null)); // should return null</pre></a>

The reason why this happens is that in Javascript the term `null >= 0 && null <= 1` is `true`.

So the issue boils down to this: `curve.getLocationAt()`should return `null` if argument `offset` is `null`.

**Comment by bildlich** [comment] 2015-03-18 10:11
Thanks for investigating, @iconexperience!

**Comment by iconexperience** [comment] 2015-03-19 07:34
Currently the function returns `false` if `offset` is out of range, therefore I think it should also return `false` if `offset` is `null`.

Another strange behaviour of this function is the different behaviour depending on the value of `isParameter`. If it is set to false, a `CurveLocation` object will be returned, even if `offset` is out of range or `null`. But I think this should be fixed in `getParameterAt()` which should return `false`in these cases.

**Comment by lehni** [comment] 2015-04-04 14:11
Great, thanks for looking into this @iconexperience! I agree about getParameterAt(), although the return value in all these cases should really be `null`, not `false`. Will create some test-cases now and then fix these bugs.

**Closed** 2015-04-04 15:06 UTC

**Comment by lehni** [comment] 2015-04-06 17:35
@iconexperience `false` being returned was a bit of a mistake. I'm not a fan of mixing boolean and numbers (feels very PHP somehow), it's better to return a number if the result is valid, and `null` otherwise.
