### ISSUE TITLE
Path Boolean Subtraction not working properly

### ISSUE THREAD

**Issue by mitsos1os** [paperjs/paper.js#661] opened 2015-03-18 16:00 UTC
When you have two Paths and you try to subtract one from the other, if their curves overlap, they remain in the final operation result (which is transformed to a Compound Path). I believe this is not correct, because normally when you subtract a shape you want to include its bounds in the operation and not just the fill area...

I have created a code for reproducing this behavior. You can also check it in PaperJS Skecth here: http://sketch.paperjs.org/#S/rZI9bwIxDIb/SnQDd0joOLViuYqpXTogVdANGMJhICU4NHFALeK/1zkE9yHaqdnsN3792MkpQrmDKI8mW6BiE/WiwixDfJBWGE8EdvLppQUxFAhH8SZpk46hIIlrDclphqJ29kYh5WI6yHqDbN5rik59Qy4es6yVXymtn402NhexhWVcqefu0wyrMCApxP8meviTaG0BsM0USAgcMUJ9R6nzC7KyoKSGGe6Hu+nNlaviL9DaHOOr5kDzBLBkiayHcuzQhL3UAV4JdmVq5ZETBoXBkfEOXswREzgAUle0Bu/3HdCI3zJpLvG6yI2iMTivwwx7az64fcq5d6a5OKbl6kJxvbQC4rrKo9OpglRdcG8bu8Nt5foXbrUSSdWk2xSbBEzoVGk7FDXkemv+zwsLclsKLsqn8/MP

code to see problem
```javascript
var outterSquare = new Path.Rectangle({
            point: [50,50],
            size: 300,
            fillColor: 'red'
        });

var innerSquare = new Path.Rectangle({
    point: [50,50],
    size: 200,
    fillColor: 'green'
});
var test = outterSquare.subtract(innerSquare);
test.fillColor = 'yellow';
test.selected = true;

var activeItem;

function onMouseDown(event) {
    //setMode();

    var hitResult = project.hitTest(event.point);
    activeItem = hitResult && hitResult.item;
}
function onMouseDrag(event) {
    if (activeItem)
        activeItem.position = event.point;
}
```

Just Drag the test object in yellow to see that it includes the top left segment of the innerSquare Path.
If you make the inner square start from 49,49 Point then the subtractions works correctly (since curves don't overlap)

**Comment by lehni** [comment] 2015-03-20 17:55
Duplicate of #449 and #653. Closing (please search first before reporting bugs).

**Closed by lehni** 2015-03-20 17:55 UTC
