### ISSUE TITLE
Consider switching to newer JSDOM

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#782] opened 2015-09-14 05:50 UTC
Yesterday I tried to build PaperJS on a Windows 7 machine with cygwin and things turned out ot be a bit more difficult than expected.
The only way I could make it work was to change the version of jsdom in package.json to "~4.0.0", because since that version jsdom does not depend on contextify and gyp anymore, which were the reason for my problems. 

I do not know if anything has changed in the newer jsdom version that would cause new problems in other environments, but if there is nothing else stopping you from moving to a newer jsdom version (4.0.0 or newer), please do so because builing PaperJS on Windows would get much easier.

**Comment by lehni** [comment] 2015-09-14 07:26
What version of Node are you using there?

**Comment by iconexperience** [comment] 2015-09-14 08:34
version 4.0.0

**Comment by iconexperience** [comment] 2015-09-14 09:21
Oh, and I had to use `npm install --no-optional` because of canvas.

**Comment by lehni** [comment] 2015-09-14 09:53
Yeah and jsdom 4.0.0 doesn't run on the Node versions that support canvas... So for now, we're stuck with old Node.

**Comment by lehni** [comment] 2015-09-14 09:54
You can track progress on that here: https://github.com/Automattic/node-canvas/pull/622

**Comment by lehni** [comment] 2015-09-14 10:03
Kind of a dupe of #772, closing.

**Closed by lehni** 2015-09-14 10:03 UTC

**Comment by iconexperience** [comment] 2015-09-14 10:39
Alright, I can live with that.

**Comment by lehni** [comment] 2015-09-14 11:16
"Note that as of this release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you are stuck on legacy technology like Node.js™."

: )

**Comment by lehni** [comment] 2015-09-14 11:17
You can feel the heat between these platforms that were now finally merged again, producing a version jump in node from v0.12.7 to v4.0.0. Confusing!

**Comment by iconexperience** [comment] 2015-09-14 11:19
Yes, does not feel nice to be a collateral damage in that fight.
