### ISSUE TITLE
[TS] String is not assignable to Color.

### ISSUE THREAD

**Issue by Domvel** [paperjs/paper.js#1690] opened 2019-07-11 09:58 UTC
The color properties only accept `Color` from paper. But strings are also possible. TypeScript type definition issue.

Example:
```ts
const triangle = new paper.Path.RegularPolygon(new paper.Point(80, 70), 3, 50);
triangle.fillColor = '#e9e9ff'; // <- Type '"#e9e9ff"' is not assignable to type 'Color | null'.ts(2322)
```

Affected class: `Item` (Item#fillColor). Maybe more color properties like strokeColor.
http://paperjs.org/tutorials/paths/creating-predefined-shapes/

paper.js 0.12.3

**Comment by sasensi** [comment] 2019-07-11 10:12
I close this issue because it is a duplicate of https://github.com/paperjs/paper.js/issues/1665.
Please add your voice there if you have an idea on how we could solve this.

**Closed by sasensi** 2019-07-11 10:12 UTC
