### ISSUE TITLE
Path resolution on certain tablets

### ISSUE THREAD

**Issue by JFenlon** [paperjs/paper.js#731] opened 2015-07-14 18:37 UTC
Hello,

I have an application that can generate many lines intersecting a single point. On a PC or iPhone 6 (iOS 8.4) the screen resolution looks perfect in any browser. However, on an older iPad 2 (iOS 8.4) and newer iPad mini, I am seeing some very degraded resolution from the same application. I'm not sure if I'm missing a setting but I can't seem to fix the issue. The app is hosted on a local web server for testing so it's delivered to my devices exactly the same. Is this just an iPad issue? I don't have access to an android tablet currently so I cannot test there.
Please see the attached images.
And thank you in advance for any assistance,

John

iPad screens:
![img_0225](https://cloud.githubusercontent.com/assets/4052559/8681361/8890057c-2a2c-11e5-85ad-b06a4842682a.PNG)
![img_0224](https://cloud.githubusercontent.com/assets/4052559/8681360/888b8600-2a2c-11e5-8f19-6d76329213e6.PNG)

iPhone screens:
![img_1289](https://cloud.githubusercontent.com/assets/4052559/8681489/4bdeb708-2a2d-11e5-9afc-c3b904e66e4d.PNG)
![img_1288](https://cloud.githubusercontent.com/assets/4052559/8681490/4be14a90-2a2d-11e5-8187-27f9624020d6.PNG)

**Comment by lehni** [comment] 2015-07-23 10:04
I have responded to this on the mailing list, let's keep discussing it there. Since it's probably not a bug, I am closing the issue.

**Closed by lehni** 2015-07-23 10:04 UTC
