### ISSUE TITLE
Image/Raster Quality Issue

### ISSUE THREAD

**Issue by nishikawa7863** [paperjs/paper.js#1426] opened 2017-12-19 07:54 UTC
When creating rasters (We're using PNGs) we're loosing a lot of resolution on the image rendered. Is there anything we can do to increase image quality? We are already using HiDPI.

Here's an example of an image we're using:
![kanevas2017-286222319657-i_ywlybnydiz85s_vijr2siy](https://user-images.githubusercontent.com/5808416/34146269-f10d71e0-e45e-11e7-84d7-d9d624639d53.png)

And here you can see the difference between the image and the render:
![fzhaztpl3fpdn3mpm](https://user-images.githubusercontent.com/5808416/34146404-7a42ea08-e45f-11e7-858c-f1ae17515af1.png)

**Comment by nicholaswmin** [comment] 2017-12-19 12:22
Can you post a [Sketch][sketch] reproducing this Issue?

[sketch]: http://sketch.paperjs.org/

**Comment by mikekov** [comment] 2017-12-28 01:56
Do you use whole number coordinates when you are requesting rendering? Fractional numbers cause re-sampling as far as I could see when I was playing with it.

**Comment by Jolg42** [comment] 2018-01-16 10:14
Please reproduce and post the link here with http://sketch.paperjs.org/

From what I know this could also be because the rendering ratio is not 1:1

**Comment by sapics** [comment] 2018-10-02 10:05
There are no test case to reproduce, thus we cannot detect the bug.
I will close this issue, but feel free to comment if you have any information, we will reopen again.

**Comment by habibillah** [comment] 2019-11-20 22:14
Hi @sapics I have similar issue with this. Look this https://jsbin.com/hunegaxito/edit?html,css,js,output to reproduce the issue. The canvas look render smoother image than its original image

This is [sketch version](http://sketch.paperjs.org/#V/0.12.3/S/hVKxTsMwEP0V4yWp1LhdWIIYKGJgQYiOTYWMc01MbceynbZR1X/nnLSFIioyRMn5vXfvnm9PDddAczpfQxA1HVPRlPF/wx0R3Gy4f1KgyT0pG9FqMIFVEGIJP2fdc5kmAyoZ3RXmm8B86BSwGmRVB2Qnt9Op3SWIKYzlFhzbSNiy1pY8QDrq67Gl1LyCuRORUodgfT6ZeMHWXMlojIlGTypwmpsuc+BlCUZAhnpahmzFtVSx3hrZGPZpq+Qs7LgP4FDWwJYMDt76UrpHSPBN6wTk5/7jWLSNlwGVcvLDssDBweH54Zfr/3LyXFsFWY/t05Irkt6cqSOCRgg+f4oJBxjUUS8tqNRVQaPIBYPJMgZ30emIGd59EvFKXrkBdd2xn3WPinv/gsuRJj3j3UZKcup5qbKYLhm3FkyZfg90FTnsRoBdeFCyMtHykGo0e8BgzvP4fhNOl4KnuKAfGMXaNhJd0nyxPHwB)

**Comment by sapics** [comment] 2019-11-21 03:31
Thanks @habibillah for reproducing!

For changing the canvas size, `view.viewSize` is recommended method.
Please check the [sketch](http://sketch.paperjs.org/#V/0.12.3/S/hVNNT8MwDP0roZd20pbugoSKODDEgQtC7LhNKKReG9akUZJ9Me2/Y7ejbIixHqLUeX5+fk52kREaoiwaLyDIMupHss7pfyUck8KshH+sQLM7ltdyqcEEXkCgEG5H26c8iVtU3LudmjQ9yuE+bCvgJaiiDEgQXw+HdhMjzAoLjq8UrDm0TAfsWuWhJOjNRej/tLSM1SfguYE1o22CnH2G4N4pdGlzESCh6NRQ10qLAsZOEncZgvVZmnrJF6JS5A2XtU4LcFqY7cCBVzkYCQPk0yoM5kKriuJLo2rDP2wRd8RO+ADuIKlV8NqEkh1Cgq+XTkLW1e9T0NZeBWTK2JFkiTaAw/P9L9WXRuWFthUMGmwzMDVnyVWX2mMohOH3J5l0gEYd+JJppHQxjYjkJIOrnIw7qXTAtGvjBM3uRRioziv2o+1DJbx/xvuZxE3Gm6WU+LvmKctkOOPCWjB58tPQWWR7iQJswn2lCkOSW1dJ7B6N6frxzU34Hgqe4ht5RysWtlaoMsoms/0X), I guess that it looks same.

**Comment by habibillah** [comment] 2019-11-21 06:59
Trying using [new image in sketch](http://sketch.paperjs.org/#V/0.12.3/S/hVPLTsMwEPwV40tcqTi9IKEgDhRx4IIQPTYVMs6SWE0cy3ZfVP131kkaGkSpD5aznp2dnXX2VIsKaEJnS/CyoGMq6yx8r4UlUui1cE8lVOSeZLVcVaA9z8GHEB6nu+eMRS0qGt2lOo5PcrjzuxJ4ASovPBJEN5OJ2UYIM8KA5WsFGw4tU4fdqMwXAXp7Efo/bdhm6gvwXsOGhCNDzjFB8GgIXZlMeGAhmurQtapEDjMrA3fhvXFJHDvJl6JUwRsu6yre4uJG51GfZYXzYLt6Lf1bE2J7hHhXr6yEpCcfh6CpnfKq1gk50SOxR7B4f/gl6dIcnKhMCdcNtpmG+iTsqk8dERRCcP1JJi2gCx0fS6mq8pQGkkEGV1lwZVCpw7R740QYzKvQUJ5X7Ka7x1I494KPj0VNxrsJKdGx5pBlPllwYQzojP00dBbZvhAPW/9QqlwHya2rQewBjen7cc2Yj0PBW/wBPtCKpakVqqTJfHH4Bg==)

Jaggies in original image look sharper
 
![076fd](https://user-images.githubusercontent.com/547094/69314469-d2241900-0c66-11ea-8c53-c4e71f2f9c85.png)

**Comment by habibillah** [comment] 2019-11-21 07:20
I think I fix it by add `smoothing: false`. Thank you @sapics

**Comment by sapics** [comment] 2019-12-07 08:17
@habibillah Sorry for late response.
Your two images are same size and you have fixed your problem by yourself, thus, I close this.

**Closed by sapics** 2019-12-07 08:17 UTC
