### ISSUE TITLE
Almost infinite while boucle due to maxDistance on Ctrl+Alt+Del

### ISSUE THREAD

**Issue by stity** [paperjs/paper.js#800] opened 2015-10-07 09:42 UTC
It seems that there is an issue with paperjs when pressing Ctrl+Alt+Del.
I have set the parameter maxDistance to 5. When pressing Ctrl+Alt+Del, paper catch a mousemove with a wrong point attribute (for instance {x: -33554613 y: -111}).
In Tool._handleEvent, a while call _updateEvent to fire the intermediate events but assuming that event are fired every 5 points, more than 6 000 000 events need to be fired.
See the 
screenshots of the Chrome Debugger :
![updateevent](https://cloud.githubusercontent.com/assets/11036145/10333687/daf3101a-6ce5-11e5-854c-db03074e76a1.png)
![handleevent](https://cloud.githubusercontent.com/assets/11036145/10334046/006ab81e-6ce8-11e5-92f6-ac78884fd3af.png)
I think that a test on the point value should be added to prevent this behavior (disregard event when point.length > 10000 for exemple)

**Comment by iconexperience** [comment] 2015-10-07 10:29
I can confirm that this issue occurs. Just running a plain Paper.js app and pressing Ctrl+Alt+Del results in a single `mousemotion` event with totally out-of-place coordinates, in my case `y: -131.1875, x: 33554383`, no matter where the mouse pointer is located at the moment of pressing Ctrl+Alt+Del.

**Comment by iconexperience** [comment] 2015-10-07 10:44
The mouse event that gets fired has `screenX=-1` and `screenY=-1`. This could be used to filter this kind of events before calling `handleMouseMove()`.

**Comment by lehni** [comment] 2015-10-07 11:37
Wow that's bizarre. @iconexperience would you like to take this issue on, since you're working on Windows?

**Comment by iconexperience** [comment] 2015-10-07 12:13
OK, I will try.

**Comment by iconexperience** [comment] 2015-10-07 12:22
Another thing to notice is that the event's `type` is `mouseout` and `toElement` is `null` and `currentTarget` is `document`

**Comment by iconexperience** [comment] 2015-10-07 12:37
I have compared the event with a normal mouse leave event when the mouse pointer moves directly from the canvas to a non-document area, like the scroll bar or the window frame. The only difference seems to be the bizarre coordinates and the `-1` for `screenX` and `screenY`.

**Comment by stity** [comment] 2015-10-07 14:29
In fact, this could be an issue related to chrome : 
[See this jsfiddle](http://jsfiddle.net/10pzjk91/)
in firefox the coordinates are right...

I think Paper should counter this possibility anyway.

**Comment by iconexperience** [comment] 2015-10-07 14:31
Maybe the best solution would really be to handle this issue in `Tool._handleEvent`, because the event is as it is and I think we should not mess with the event's values. We could check in `_handleEvent`for the `mouseout` type and then for an unusually large x or y value. I think 10000 will be too small, as this will be the average screen size of smart phones in two years, but something like `Math.abs(x) > 30000000` should do the job.

**Comment by stity** [comment] 2015-10-07 14:50
For your information, I reported an issue for Chrome.

**Comment by iconexperience** [comment] 2015-10-07 14:54
Thanks, I was just searching in their bug database. Do you have a bug ID or did you report this directly through the browser?

**Comment by stity** [comment] 2015-10-07 14:56
I reported it through the browser but I didn't check if the issue already existed.

**Comment by lehni** [comment] 2015-10-07 15:09
I would handle it further down, since there is also `CanvasView#_handleEvent`. But can't we simply check `screenX/Y` for -1 then?

**Comment by iconexperience** [comment] 2015-10-07 16:02
I am not sure if there is no other case where `screenX` can be negative., that's why I would rather use the x value.

Also, since this is a chrome issue, this should be fixed soon in Chrome. 
Should we really include a workaround for each browser bug into the paper.js codebase, or rather provide a workaround here that can be plugged in as long as the issue exists in Chrome?

A workaround for this issue could look like this:

```javascript
    myTool._originalHandleEvent = Tool.prototype._handleEvent;
    myTool._handleEvent = function(type, point, event) {
        if (event.type === 'mouseout' && event.screenX < 0) {
          return false;
        } else {
          return this._originalHandleEvent(type, point, event);
        }
    }
```

**Comment by iconexperience** [comment] 2015-10-07 19:43
On my system this issue only occurs when I have Chrome development tools running. Without developer tools the event has the correct x value.

**Comment by iconexperience** [comment] 2015-10-07 20:01
@stity I could not find your bug in the database, so maybe they are not taking it serious. Therefore I opened a new issue at https://code.google.com/p/chromium/issues/detail?id=540840

**Comment by stity** [comment] 2015-10-08 09:41
@iconexperience thanks for the workaround, it works for me.
I backed up your chrome issue with a star ;)

**Comment by iconexperience** [comment] 2015-10-08 12:17
@lehni 
Should this issue be closed or do you thin I should create a workaround for the Paper.js codebase?

My personal opinion is that no workaround should be provided, because we cannot implement workarounds for all bug that any browser build ever had.

**Comment by lehni** [comment] 2015-12-27 18:14
I am looking into this now. [Here a simple sketch to replicated it](http://sketch.paperjs.org/#S/TU49C8IwEP0rRxZbKKU6RpzaVRAcrUNMrzY03kmSqlD6302roG97n7xRkLqhkOLYY9CdyITmZuaB2eateWFTGR8UaYQdbIptTTW1A+lgmIBpz4PHyqlrgg+kkMJYE0QQPuGgQpeXxmmLyVeeoWMOnYSlkN/ZUMh+rlONGbyEdfEntsbaki3H1sphs/o4UxrfTPHyxaHqlyEv5Ok8vQE=)

**Comment by lehni** [comment] 2015-12-27 18:23
What's really bizarre: (1 << 15) == 33554432. So I have a hunch that when this happens, for some reason bit 15 gets set in the x-coordinate value!

**Closed** 2015-12-27 18:31 UTC

**Comment by lehni** [comment] 2015-12-27 18:36
Oh wait, @iconexperience was your value a positive 33554383?

**Comment by iconexperience** [comment] 2015-12-28 08:35
Not sure if this is of any help anymore, but yes, my value was `+33554383`.
