### ISSUE TITLE
get nearest loc shows time 0 when should be time 1 (at end of curve/path)

### ISSUE THREAD

**Issue by NoZ4** [paperjs/paper.js#1840] opened 2020-06-30 14:51 UTC
Sorry for no example

basicly if you getnearestloc and the nearest is the very end of the curve/path time shows as zero not as 1;

**Comment by sasensi** [comment] 2020-11-04 09:21
Hi, unfortunately, without a test case, it's hard for us to investigate the issue.
I tried with a very simple case but this seems to be working as expected, as shown by this [sketch](http://sketch.paperjs.org/#V/0.12.7/S/lVLBasMwDP0Vk0tTCCY9FEbGLuu1jMKOaQ+Oo6ReHavISsso/fc5KU2T7jBmMLaen/SebF8ipxqIsujzAKz3URJpLLtYo/MsrHEg3oSDs9go3st1iOPLlrZOhFERNpnI00Sku+QOMgZokU5BDxY0Q5kJphY69Dp/7ZZu3qRYUQ28QeM4KOaLZV/hiaRbOsEatWKDLtA6fzKkfYAi8Hw/iUfFHjpDFytD2o760OAYKBtbGJyTKk3rM7EckMpYu0KLIWGGpFwNs6eG/hSatCGP/xAsbPtLrrsatCAt1vG0MpsGHrwj4Vd4Bak0m0BS30CyMvyOrSt9fDJwlkW/l16rYDuVL/NbdvgWBYE69E59lOW76w8=).
So I'll close this but feel free to reopen it if you can provide the reproduction code.

**Closed by sasensi** 2020-11-04 09:21 UTC
