### ISSUE TITLE
onMouseLeave event doesen't fire when leaving from one path to another.

### ISSUE THREAD

**Issue by VanTudor** [paperjs/paper.js#699] opened 2015-05-27 17:19 UTC
I have two path.circles, each with its own onMouseEnter and onMouseLeave events. When the two circles overlap, or are really close to each other and i hover from one circle directly to another (without hovering on the canvas), the onMouseLeave event doesn't fire on the first one.

**Comment by lehni** [comment] 2015-08-19 11:14
I can't reproduce this in my own tests. What version of paper.js are you experiencing this with?

http://sketch.paperjs.org/#S/nZHBasMwDIZfRfiShIWQFcogZafSWweDHZseXEdtTD1p2E53KH332U5g60bZmA820m99/sBnQfIVRSNejuhVL0qhuIv1SVpQ2iqD9/AIhO/wLH1fLVMrP7cEYcXZBrKdGTArx5ZC8mgb2MzquoSwbafAyk4ProF5PTX22pglG7bfCExPPDhcjZyEu07WKE/hWROPli7FoqWWPn1nv/pa7H7qPsz/rvsF8D/b/UDKa6ZxIC9gElRMjg1Whg95ljLI4A58r10V5YtFvBUwV5DEvgFJ2Q1I+O2dRXl8Y03eiWazvXwA

**Comment by VanTudor** [comment] 2015-08-19 13:22
This was happening in 0.9.22. I had multiple circles that kept moving according to randomly generated vectors. These circles increased in size when the mouse was hovering over them and decreased when the mouse left. When two circles were moving in parallel, so that i could hover from one directly to the other, the onMouseLeave() event didn't fire. I have since dropped the project, but i will try to reproduce the bug.

**Comment by lehni** [comment] 2015-08-20 12:47
Yes please try with 0.9.23, and if it still occurs it would be good if you could share your code so we can reproduce. Thanks!

**Comment by lehni** [comment] 2016-01-08 21:47
I am closing this issue for a lack of new data. If it's still an issue, feel free to reopen.

**Closed by lehni** 2016-01-08 21:47 UTC
Labels: cat: event-handling, type: bug
