### ISSUE TITLE
boundary of raster image element inside svg

### ISSUE THREAD

**Issue by hishin** [paperjs/paper.js#1192] opened 2016-11-02 18:31 UTC
I am loading an svg image onto paper using:

importSVG(mysrc.svg)

The svg includes text as well as raster images within it.
For example, mysvgitem.children[0] is a PointText item, and mysvgitem.children[1] = Raster item.
The svg loads correctly, but when I try to get the boundary information of the raster element inside it for instance

mysvgitem.children[1].boundary

it gives me completely different numbers for width, height and x, y position (than what would show up as the actual boundary, e.g. when I do mysvgitem.children[1].selected = true)

Is this a known bug?

**Comment by supernlogn** [comment] 2016-11-17 10:56
This happens also when you load an SVG image directly to a Raster Element.
Example:
`raster = new paper.Raster('mySvg.svg')`
Now if i print the rasted dimensions( `raster.width`, `raster.height`),
The printed dimensions are obviously wrong.

But I found a way around this bug:
Lets say we have a Raster: `raster = new Raster('mySvg.svg')`
or we import an svg: `raster.importSVG('mySvg.svg')`

Then `raster.width` holds the value we want this raster element to have
Unfirtunatelly, setting `raster.width = raster.width` or `raster.setWidth(raster.getWidth()`
has no effect.

The way of fixing it is to write:
`raster.setHeight(raster.height+1);
 raster.setHeight(raster/height-1);`

Ofcourse the svg image presented has not the initial quality, But at least it is fixed
That is just for now. 
I hope the developers will solve this bug soon.

**Comment by lehni** [comment] 2017-01-03 11:39
Could you share the original SVG file that produces this scenario? Hard to look into an issue without seeing the data. Thanks!

**Comment by lehni** [comment] 2017-03-09 22:06
@supernlogn I am still hoping to get some SVG data to reproduce this. Could you share it?

**Comment by supernlogn** [comment] 2017-05-11 09:33
Here is the image: https://drive.google.com/file/d/0BxzY0txWsh_MN2x0TTRKc2xzTTg/view?usp=sharing
I am just 4 months late :P
Try this:
`
raster = new paper.Raster("theImageIuploaded.svg"); // create new raster from an SVG
raster.translte( paper.Point(300,300)); //center it
raster.setHeight(raster.height+1); raster.setHeight(raster.height-1); // Bug ahoy!!
`
To see that there is a bug. The image suddently shrinks to 151 pixels.

**Comment by lilltiger** [comment] 2017-06-09 10:45
I am in badly need for this stuff to work, so I wonder if there is any progress at all on this front.

I have noticed that the size of the canvas affects the image imported as well, if the canvas size isent of the same aspect ratio as the image the image will be cut of in strange ways.

Also scaling behaves very strangly, if I scale the image using scale(0.5) the image will be scaled down to 50% but the center of the image will be moved to lower right of it's bouding box, so one will only see 1/4 of the image and that part will be the top left quater of the image.

To make even more strange things happen try fiddling with the item position like:
`item.position = paper.view.center;`

This will generate some very strange cut-off's and placement of the image.

[Sketch that demonstrates the issue](http://sketch.paperjs.org/#S/jZDdbsIwDIVfJcoNrUR+SrVNtNo1D4DEzTqhLBjIWOIoMa00xLsvHXuA+cLysT/ZR77xYDzwjm8vQPbMl9ziYdajSSyPJ/bKFmeimDulcivgKibIJBppvPnGYKYsLXoVYyZM5gQHGNVfqWJCPO4dgVda60atdPMi9LPQa2X2ei1WrdCtLEcW/RCGUPBPsCSdj5hou9tUs4ElO16DJYehYvMqVrPbEFgJpWYtI2Y3j4vTaCIkOTqYpIVAkPoH+cj/pX+5bM0XVFo+1aV7r/vymI8E5hLRBcq8e3u//wA=)

**Comment by lehni** [comment] 2017-06-09 12:24
That's indeed a bug. But weirdly, I see the same behaviour for both sketches above. Could you include screenshots of what you're seeing @lilltiger?

**Comment by lehni** [comment] 2017-06-09 12:29
These are two separate issues really, BTW: The one described by @hishin is the same as @lilltiger. What @supernlognis describing is a separate problem and needs a separate issue.

**Comment by lilltiger** [comment] 2017-06-12 09:09
The other behavoiur is that it cuts the other way, so one get's the lower right quadrant of the file insted of the upper left.
But as you say when I open the linksthey look the same untill I reload the Clone & Rasterized one, then it updates to the result shown in this screenshot:

![screenshot_20170612_110549](https://user-images.githubusercontent.com/23436/27026783-349aa72e-4f5f-11e7-942d-677fa9b165ee.png)

**Comment by lilltiger** [comment] 2017-06-12 09:25
@lehni maybe it's mine that needs a different issue, they both are talking about incorrect bound sizes, while for me the sizes seems to be correct, just that the actual image is offset depending on the aspect-ratio and scale compared to the boundingbox.

**Comment by lehni** [comment] 2017-06-12 10:54
What I meant is: There's a big difference between using an SVG as the source for a Raster, or importing it as vector graphics. Issues with bounding boxes in both situations are not at all the same, as the first relies on the browser to do the SVG rendering, while the 2nd is converting it to a paper.js scene graph.

**Comment by lilltiger** [comment] 2017-06-12 11:05
Ahh ok, sorry for missunderstanding.

I have done some more testing and found another strange thing that seems related, when doing translation of the image it moves twice the given translation, I think that messes with the scale as the scale translate it to the center and then back.

Here is an example of the doubled translation:
[Double translation length of images in SVG](http://sketch.paperjs.org/#S/lVFNa8MwDP0rJpcmkNhuQzfaslMPu+wwKOyyjqIlauM1sY2tJmyl/312P2CDXWZjY0mPp/esY6Khw2SerPZIVZPkSWXqGPfgmO937IGNGiLr50L4ssBDMaCnYsyhgy+jYfC8Mp2w1pNxsMMae3F9CuuM2W4UYSeklGMxkeP7Qt4VciZgI2fFpCxkyUOT0WKt1zrAP7AirjprHK1eHtMoIGfbg65IGZ2ySMUydlxrFpYQMebWeBXLQakFi473CgdeoSZ0iwvyv/gzjhxo3wJhOpEyDyf7xRb/xwI1gUbjcKV6Dgm+VK5qMf2RNUpTWk5zVk6z83X2G1kugJtzCD57fILPkGvB07JRbc23qm2XpjUuzsJhPbrpoLCvLKHtn3pP2SKM9N0h7G1U4ZP569vpGw==)

**Comment by lilltiger** [comment] 2017-06-12 12:15
I couldent find any issues in the scale nor the translation functions, but for some reason the transformation matrix seems to be applied twice when the item is drawn.
The position and bounds are proper when printing them to console, but on the canvas they are applied twice.

![screenshot_20170612_140923](https://user-images.githubusercontent.com/23436/27033385-5e438aa4-4f79-11e7-9d41-ff38fb229a8d.png)

(Just a screenshot of the last sketch but with printing out the positions and mouseovering the object to show the difference in values.)

**Comment by lilltiger** [comment] 2017-06-13 09:24
@lehni this issue eludes me quite a bit, I have traced it down to, that for some reason the view(when doing the translation) seems to be modified by the translate call.

`item.translate(20,20);`

Then on line 3528:
```
getView: function() {
	return this._project._view;
}
```
It will return the view translated with the inverse of the transform done, like here it would return a view that is offsetet by -20,-20.

But I have no clue at all why it would do this.

**Comment by lilltiger** [comment] 2017-06-13 10:25
It seems to have to do with the fact that the item has not finished constructing, if I place a timeout in the import function then it works as expected.
But I thought that the object is supposed to be fully loaded before executing the user code.

[Expected behaviour acchived when using timeout](http://sketch.paperjs.org/#S/VVBNb8IwDP0rUS8UiXzQapso2nmX3Zh2WScUUhcy1jhq3CKB+t+XQieE5YM/nt+zfUmcbiApks0RyBySRWKwGvNetyz0e/bKZgciHwopQ86h4ycIxJdCN/qMTp+CMNhI7wNhq/dQQS+nUPoWsd5agkYqpZYyU8sXrp65Wkm9VSue5VzlIorM1qUrXYT/gCFhG48tbT7f0nGBBas7Z8iiS9lIxebsUjoWPVoA+rANYEfpHXYDTHaPxmERjP6FVImn+VXyoecx2JEgnvy/Sm/hJHbYuSoIQv8ONQldVekVP9WDPYPMRr5HzWHBsnj2TWiYr+Nrdy3oo0frKCTF1/fwBw==)

**Comment by lilltiger** [comment] 2017-06-13 10:49
Now that I think about it I seem to recall that we had a simmilar issue erlier with regular SVG's without images, that they acted strangly because they where not fully loaded when read in as strings. But that issue was fixed, maybe this is the same thing but for raster, could it be that it emits a state of loaded before it actualy is fully loaded?

**Comment by lilltiger** [comment] 2018-02-27 08:12
Fixed my sketches, CORS was preventing the images from loading, added http://sketch.paperjs.org to the list of allowed origins.

**Comment by park9140** [comment] 2018-03-01 00:29
For another repro of this you can see it when importing from svg in this [sketch](http://sketch.paperjs.org/#S/nVRtb5swEP4riE+tsgXz0iSQthNJ0yZplrTQvHVMKwEDbsAw40Caaf99B92qdpq0af6A7x4/d/fYZ/xNpG6CRUO0t5h7kfhO9FK/8guXCSFLd5lwJlBcCleVfXTcdahDa7xJkixl3F5cHT2cftgnsVBglpOUnjmi3ESOKGAKuQgNAdjx4H3HET+cO/Q0L8I3VBmoxAdz4j5h9gVcqMEFyEhzQCPOM0OSyrJslmozZaGkIIQkyAJxNcnYx4Ru/0iVdV2X6uWKDBSU7cF6erFK4vOokqFpz0CESRhxQDotrQJqLQXBZS+t4wUkVFwBloGd86cYA4ypu4nx+43rbavDob5RndlrcvdZrZFnrldFZAznmBXYEc+rEqcMe/xFjYrQGylt8ATOXJoHKUsASVzOyP4INRVZ0+s6P00Vac12G7UEWW83O3K7dQyhAYljCKIpxbVmlm4rCQz74ErP9UnihvhlPyk0KIjT0ihITmBn3T9vEEb31SH+JrvV/tVZXOF1G4yI4QAQ3+WuUdeUMhp2N26OW9o7sujNrBJdX4WpCWNqz6PBPATLLuHTu+ibtzD3P6bBxWVFMJPxxEK3pqThm8OkUyFjbxDde0B36IR8BLL2aK5IfKOuYXEAGa3eYvjotv0xt/OpeTXYWFYjabA7Lo+l5TCM+yiItWvdKkcje3Aoeje7XnghOVThikLXLUpXG3f1taFmUrA70Rt6cRFLUq5es86hVDxWHIb9htxaLtSDOvWLOB+eqDLaxtJspwcSm05mB+Q7lHdmShsP3WA1vXvkhc6XQTgNk0k06Y36o90gH4QjotmlbZK/Yg79V+a/YA79/+hisPYLBc/QHrq1e3q8CRy6b0waiuWbXt3CGFmLCM0VPfGHfuQlc/N2aRXrZB7aSzm6Vxb2/fJyi1fD8f1dWbfYni9m1vVJfz0awb35/7/g+ZpL9Z2rnqHqBYH54RjevA3D7jZLCeW5aHz6/P0H)

The embedded image has a transform on it that is applied as it is initially rendering but places the image in the wrong location where as it places the rectangle where it is expected.

**Comment by lilltiger** [comment] 2018-03-06 07:31
I have tried this patch out and it does seem to fix the issue, and I am yet to find any complications from it!

Great work @park9140!

**Comment by lehni** [comment] 2018-03-06 14:11
Closed by #1452

**Closed by lehni** 2018-03-06 14:11 UTC
Labels: cat: import-export, needs: test-case, type: bug
