### ISSUE TITLE
Canvas-less mode not available in NodeJS / Electron

### ISSUE THREAD

**Issue by geloescht** [paperjs/paper.js#1103] opened 2016-07-12 11:53 UTC
I am trying to use paper.js with electron and hit the following exception:
```
Error: Module version mismatch. Expected 47, got 46.
[...]
    at Object.<anonymous> ([censored]/node_modules/canvas/lib/bindings.js:3:18)
[...]
```
This is expected when a binary module, such as canvas, is required in electron without re-compiling it manually for electron (instead of node).

However, I am not using any features of the binary canvas module in my application. I am directly exporting my paper.js project to SVG. It should therefore not be necessary to call `require('canvas')` (the line which triggers the exception) in paper.js.
Canvas-less mode should be available or even the default in Node (and as a consequence also in Electron). Actual canvas emulation is not required in most use cases where paper.js is coupled with Node.

**Comment by lehni** [comment] 2016-07-12 15:56
I just tried this and it works for me... What do I need to do, to get this version mismatch? Could you perhaps share some example code that allows me to reproduce the issue?

What I've done:

* I Installed https://github.com/electron/electron-quick-start
* I added the code of the SvgExport.js example to main.js

This just worked...

**Comment by lehni** [comment] 2016-07-12 17:34
I believe 89c60b1a056e657526cf9e1acc4a4bbb33c1e51d / 8a45c5dff9da9a55a5d8bca7133481fba64d4dd3 solve your issue. Could you please test?

8a45c5dff9da9a55a5d8bca7133481fba64d4dd3

**Comment by geloescht** [comment] 2016-07-13 11:03
It does! Thank you for the quick response.

**Comment by lehni** [comment] 2016-07-13 12:02
Great! I'll close this then.

**Closed by lehni** 2016-07-13 12:02 UTC
