### ISSUE TITLE
Compound path drawing

### ISSUE THREAD

**Issue by mikelevy** [paperjs/paper.js#1371] opened 2017-09-01 20:24 UTC
Hello,
I am creating a little drawing application and I want to be able to add brushes as tools. I will be given brushes as SVG. However I am noticing that when drawing it is not performing as well on touch devices. It performs well on desktop though.

What is the best way to have a CompoundPath with SVG path data and on pointerMove/mouseDrag move it along the canvas? 

I can not share any code because of confidentiality, but I may be able to put a separate build together that doesnt release any information. I just wanted to know if there are any examples out there (I have not been able to locate any) and what they best way to do it is?

**Comment by alexjlockwood** [comment] 2017-09-02 14:39
Check out these:

https://github.com/w00dn/papergrapher
https://github.com/memononen/stylii

**Comment by lehni** [comment] 2017-10-04 14:55
Closing this since we're using the issues database for actual bugs and features, not discussions.

**Closed by lehni** 2017-10-04 14:55 UTC

**Comment by lehni** [comment] 2017-10-04 15:28
Yes, I'm not happy with Google groups myself either. But since I've had very little time available to work on Paper.js myself lately, there is not much I can do about it at the moment. And posting questions here will just clog up the issues database which makes maintaining Paper.js in the little time available even harder (and won't get those questions answered...).

**Comment by lehni** [comment] 2017-10-04 15:29
Perhaps you'd be willing in helping out, @alexjlockwood? I think it's time for some proper community building...  I would love to install a https://www.discourse.org/ instance also to have a proper forum, and perhaps we should start hanging out on the [Gitter channel](https://gitter.im/paperjs/paper.js)?

**Comment by alexjlockwood** [comment] 2017-10-04 15:36
I'll give it a shot and see if I can answer any open questions... I've been using the library quite a lot recently and I love it. :D 

I guess no matter what you end up using (i.e. google groups, discourse, gitter, etc.), we'll need to somehow encourage people to answer questions somehow either way.

Then again there are always going to be those questions about feature requests and what the library will look like in the future that I won't be able to answer.

**Comment by lehni** [comment] 2017-10-04 15:54
I am looking for maintainers of the library itself also. Would this be of interest to you?

**Comment by alexjlockwood** [comment] 2017-10-04 16:06
Yeah, definitely! I would probably need to learn how the build system works though... I have to admit I don't really get how it works. :P

BTW, in case you are curious, here's what I've been working on the past month or so using paper.js: https://twitter.com/alexjlockwood/status/913523790222684160

Most of the paper.js code is here: https://github.com/alexjlockwood/ShapeShifter/tree/paperjs/src/app/scripts/paper

Its still got a long way to go but at least I don't get as confused by view/project/local coordinates as much anymore. :)

**Comment by lehni** [comment] 2017-10-04 19:02
Oh wow, that looks really good! The UI is nicely done also. What framework are you using?

Paper.js build system [Prepro.js](https://github.com/lehni/prepro.js) predates much of the JS module efforts and is custom made. it's main purpose is to be able to load the raw source scripts directly in the browser without any additional transpiration or the need for source maps (which didn't exist back then), for very simple, direct and fast development cycles. 

I'll probably eventually switch to Rollup or Webpack or something the like, but I think that's going to happen after 1.0.0 is released...

The README should explain what to do, but basically, you can run `gulp load` and it creates a version of the library that loads itself directly from the sources. 

Please let me know if you struggle with any of it.

**Comment by lehni** [comment] 2017-10-04 19:10
Some more explanations about Prepro.js:

Basically, any line of code that starts with `/*#*/` contains preprocessing statements which will ge parsed and replaced when the final version is built. But these statements also work like normal JavaScript that is run in the browser when the `gulp load` version is being used.

As an example, see this statement here:

```js
/*#*/ if (__options.booleanOperations) {
/*#*/     include('path/PathItem.Boolean.js');
/*#*/ }
```

When building the library, `'path/PathItem.Boolean.js'` is only included if `__options.booleanOperations` is true (here it is loaded from `src/option.js`). The same works when the unprocessed code is run in the browser, as long as the client version of `prepro.js` is loaded which provides `include()`. See `src\load.js`.

You will also see `/*#=*/` statements, which means whatever follows will be replacd with its actual value in the source code. So `epsilon = /*#=*/Numerical.EPSILON` becomes `epsilon = 1e-12` in the final preprocessed code.

And `this._changed(/*#=*/(Change.GEOMETRY | Change.PIXELS))` becomes `this._changed(521)`

Neat, right?

**Comment by alexjlockwood** [comment] 2017-10-04 22:30
Thanks! I'm using Angular 4 w/ TypeScript.

I was wondering about the /* # */ stuff, thanks for explaining. What exactly are you looking to "maintain" in particular? Just curious, because I've noticed there hasn't been much activity around here recently.

**Comment by lehni** [comment] 2017-10-05 10:18
There are many things that are time consuming and where it would be great to do it in a community effort rather than by myself:
- Discussing new features and goals, figuring out a more up-to-date road map
- Working on actual new features, in feature branches and have discussions about them
- Reviewing bug reports, making sure they're reproducible or communicate with the reporter that more information is required, and maybe attempting to analyze or even fix them
- Keep documentation up to date, both in form of JSDoc comments in the source files, as well as on the site, of which the source lives on https://github.com/paperjs/paperjs.org
- Keep the showcase area of the site populated with newer projects. I have a list of very interesting projects but haven't found the time to get to it.

I can think of more, but this already shows that there are many areas that could benefit from a joint effort.

**Comment by alexjlockwood** [comment] 2017-10-05 12:21
Ahh, sounds good. I actually created a pull request to update some documentation but I think it failed a presubmit or something... not sure if you saw it: https://github.com/paperjs/paper.js/pull/1374

Here's another one that fixed one of my other bugs too: https://github.com/paperjs/paper.js/pull/1382
