### ISSUE TITLE
Uncaught Error: Unable to find canvas with id "myCanvas"

### ISSUE THREAD

**Issue by dariukas** [paperjs/paper.js#732] opened 2015-07-14 20:21 UTC
I tried to add the library of "paper.js" to my project. Since I put the library in the body:

    <body>
    <script src="js/paper-full.js" type="text/javascript"></script>
    <script src="js/inter.js" type="text/paperscript" canvas="myCanvas">
    ...
    <canvas id="myCanvas" resize></canvas>
    </body>

I got the error like: "Uncaught Error: Unable to find canvas with id "myCanvas".

However, if I load the library in the head, then the error disappears.

    <head>
     ...
    <script src="js/paper-full.js" type="text/javascript"></script>
    <script src="js/inter.js" type="text/paperscript" canvas="myCanvas">
    </head>
    <body>
    ...
    <canvas id='myCanvas' resize></canvas>
    </body>

That never happened using other libraries (e. g. three.js).

Between, there is no explanation what are the differences among "paper-core.js" and "paper-full.js".

**Comment by iconexperience** [comment] 2015-07-15 20:23
Regarding the differences between core and full versions, please refer to the Github page at https://github.com/paperjs/paper.js

The main difference is that paper-core.js does not include Paperscript support.

**Comment by lehni** [comment] 2015-08-19 11:08
@dariukas I can't reproduce this on Chrome. What browser are you experiencing this with?

**Comment by lehni** [comment] 2015-09-13 14:22
Closing for the lack of further information. Feel free to reopen once a test-case can be provide.

**Closed by lehni** 2015-09-13 14:22 UTC
