### ISSUE TITLE
Implement new, improved smooth() methods.

### ISSUE THREAD

**Issue by mike-marcacci** [paperjs/paper.js#338] opened 2013-11-11 17:15 UTC
The `smooth()` method works extremely well in most situations, but when two segments are closer than the hardcoded threshold, path lines start shooting all over the place.

It would be wonderful if `smooth()` either adapted to the distance between segments (although that might degrade performance), or accepted a `threshold` argument.

Cheers!

**Comment by lehni** [comment] 2015-09-07 09:08
So I've started working on the https://github.com/paperjs/paper.js/tree/new-smooth branch again, finally.

Right now, there are 4 implementations of smoothing approaches implemented for testing:

- `smooth()`: The current smooth algorithm, with its strengths and weaknesses: Smoothing-strength cannot be adjusted, it's not symmetric across the path (a regular open path results in irregular smoothing) and it doesn't handle hugely different distances between the points very well, due to the fact that the handles on each segment are symetric (handleIn = -handleOut). But it produces very smooth curves, due to the fact that it takes into account the position and handles of at least 4 of it's neighbours (?). This number might actually be much higher, as the processing goes through the full set of points, but that's at least how it visually "feels"  when observed. After adding 4 new points, the already smoothed parts don't change much when smoothing again.
- `smoothCatmullRom()`: As the name says, uniform catmull-rom splines converted to beziers <https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline>. The algorithm is very simple and fast,  and is applied on a per-segment basis, through `segment.smoothCatmullRom()`. It takes the two immediate neighbours into account and results in pretty smooth curves, although not as smooth as the original `smooth()`, because it acts on less data. It also doesn't have a tension parameter. I've been trying to find a way to convert cardinal splines to beziers, since they offer a tension parameter, but haven't found a way yet, not sure there is a simple one. Uniform catmull-rom splines are a special case of cardinal splines, with c = 0. There are also other types of catmull-rom splines that are of interest, e.g. centripedal and chordal, see <https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline#/media/File:Catmull-Rom_examples_with_parameters..png>. I'm not sure if and how these can be converted to beziers yet. Some of the disatvantages of the original `smooth()` also apply here: Symetric handles mean it's not so good with hugely different distances in points, and as stated, no tension parameter.
- `smoothGeometric()`: The previous candidate for a new approach to smoothing. It is based on a purely heuristic and empiric geometric method without a name that's outlined in two documents I've found: <http://www.antigrain.com/research/bezier_interpolation/>, <http://scaledinnovation.com/analytics/splines/aboutSplines.html>. It comes with a tension parameter, and its handles are weighted, meaning it handles hugely different distances in points better. But it results in less smooth curves than the original `smooth()` and somewhat odd handle placements.
- `smoothContinous()`: The new kid on the block, thanks to Lubos Brieda who took the approach outlined by Oleg V. Polikarpotchkin, which was used for the original `smooth()`, found a simpler implementation which also seemed to fix the symetry issues: <https://www.particleincell.com/2012/bezier-splines/> VS <http://www.codeproject.com/Articles/31859/Draw-a-Smooth-Curve-through-a-Set-of-2D-Points-wit>. It computes the handles by making sure that the first and second derivatives of all involved curves are continuous across their boundaries. I've modified it to add support for closed curves, and added some simplifications due to the fact that handles are always symetrical and x/y can be processed in one pass. The results on closed curves are very similar, while open curves are finally symetrical. It produces very smooth curves with symetric handles, and has no tension parameter.

So these are the contendners. My current thoughts are as follows:

- `smoothContinous()` replaces `smooth()`, as it fixes some of its flaws, while preserving the benefits (and reducing code size).
- We could offer both `smoothCatmullRom()` and `smoothGeometric()` as well, since their code footprint is very small and they might end up being useful in many situations. They could be exposed either trough an `options` argument on smooth(), or in some other form, e.g. under a different function name. I haven't decided yet what's best.
- Any smoothing approach that doesn't offer tension could of course be modified to scale its handles with a factor, not sure how useful that would be, but why not.
- I'd like to add a way to also smooth only parts of a path, instead of all segments. With `smoothCatmullRom()` and `smoothGeometric()` this can already be done, simply by calling these methods directly on the segments that need smoothing. With `smoothContinous()` it's trickier, since the results are affected by those of its neighbours. So there won't be a way simply call it on a Segment. But there could still be a way to define a range on the path.

So how about:

    path.smooth({ method: 'catmull-rom' }); // or just 'catmull', 'hermite', 'spline'?

    path.smooth({
        method: 'continous', // the current smoothContinous(), and the default when ommited
        from: 0, // could also support path.firstSegment,
        to: 5 // could also support path.segments[5]
    });

    path.smooth({
        method: 'geometric', // the current smoothGeometric()
        tension: 0.5
    });

    path.smooth(); // default method == 'continous'

We could also name it `type` instead of `method`.

In the same way, this new `smooth()` function could be called on Segment, but only 'catmull' and 'geometric' would be supported there, for the reasons stated above.

This approach would open the door to other smoothing methods later on.

Or maybe it's best to just go with plain old different function names?

Feedback on all these questions is very welcome!

**Comment by lehni** [comment] 2015-09-07 10:00
Oh dear, ignore the typo for now, it should of course say `continuous` : )

**Comment by nicholaswmin** [comment] 2015-09-07 11:26
+1 From me - I've implemented a hybrid Ramer-Douglas-Peucker + Catmull-Rom for smoothing the path while it's being drawn. 

For a Pencil tool, just having a smooth() Catmull-Rom or any of the new smoothing techniques doesn't usually cut it, due to the huge amount of points created by the mouse events.

Simplification on the other hand via `simplify()` uses Schneider's algorithm which is rather heavy compared to RDP. 

Someone who wants fast (near-real-time), smoothing/simplification of a Pencil Tool cannot use what's already there, even with the new smoothing methods.

Any thoughts?

**Comment by lehni** [comment] 2015-09-07 12:30
@nicholaswmin I just saw your post here, which talks about the same topic: 
http://stackoverflow.com/questions/30748316/svg-paths-and-the-catmull-rom-algorithm
Would you mind sharing your code for conversion of centripetal Catmull-Rom splines to bezier curves? I am interested in those for the same reasons as you.
As for Ramer-Douglas-Peucker, that would be fairly easy to add under another function as well, allowing you to use a combination of both approaches, just like you outlined here now.

**Comment by lehni** [comment] 2015-09-07 12:34
@nicholaswmin just found it here:
https://github.com/nicholaswmin/VectorTests/blob/master/js/ext-editorNext.js#L343
Would you be OK with this being merged into paper.js somehow?

**Comment by nicholaswmin** [comment] 2015-09-07 12:50
Sorry for the delay: 

Here it is: https://gist.github.com/nicholaswmin/c2661eb11cad5671d816.

Yes, of course.

**Comment by lehni** [comment] 2015-09-07 12:53
Very cool! I'll do some tests. Perhaps we can skip the 'geometric' approach altogether then. 

And we could use a similar approach for `simplify()`, with an option object passed to it controlling the method and amount of simplification.

**Comment by timuric** [comment] 2015-09-07 14:03
Very excited about suggested improvements by @lehni  

> I'd like to add a way to also smooth only parts of a path, instead of all segments.

Thats great! I use partial smoothing a lot in my project. 

> Or maybe it's best to just go with plain old different function names?

Personally I find different functions more readable, and also comfortable with autocomplete. But options are also ok.

**Comment by nicholaswmin** [comment] 2015-09-07 14:12
@lehni I've yet to understand why `simplify()` uses Schneider's algorithm instead of a *RDP + Catmull-Rom* method. 

In my tests it was many times faster and behaved more reliably than Schneider's algorithm alone. I can't really substantiate my claims without a demonstrable example but that was my definitive observation at the time I was comparing all these methods.

AFAIK, Schneider's algorithm is most commonly used to simplify paths in real-time. I'm saying this with a pinch of salt, I got the impression after researching real-time simplification/curve-fitting methods and found this gem: http://sarahfrisken.com/efficientCurveFitting.pdf

The paper was trying to solve the problem of curve-fitting and simplifying in real-time and the **control method** to test against was Scheider's Algorithm.

**Comment by timuric** [comment] 2015-09-07 15:52
Maybe this can be helpful http://www.mit.edu/~ibaran/curves/ it is an algorhitm for high-quality piecewise-clothoid curves, useful for processing hand-drawn sketches. It has [open source](https://code.google.com/p/cornucopia-lib/source/checkout) implementation.

**Comment by lehni** [comment] 2015-09-07 16:05
@nicholaswmin, I've now implemented your algorithm: 9c604d8be2208d33326fec8ba0830b6467411a9b
I love how by processing segments rather than cures, the algorithm becomes simpler, uses less calculations and avoids repetition across the curve boundaries. I'm really pleased with the results! Will do more tests and post results here shortly.

**Comment by lehni** [comment] 2015-09-07 16:32
Now finally some examples, illustrating that each approach has its own character and probably merits a place in the library.

First, a closed square:

```js
var path1 = new Path.Rectangle({
    center: view.center,
    size: [220, 220],
    fullySelected: true,
    strokeWidth: 8,
    opacity: 0.25
});

var path2 = path1.clone();
var path3 = path1.clone();
var path4 = path1.clone();

path1.position = [200, 200];
path2.position = [550, 200];
path3.position = [200, 550];
path4.position = [550, 550];

path1.strokeColor = 'black';
path2.strokeColor = 'green';
path3.strokeColor = 'red';
path4.strokeColor = 'blue';

path2.smoothGeometric();
path3.smoothCatmullRom(0.5);
path4.smoothContinuous();
```

![squares](https://cloud.githubusercontent.com/assets/213275/9720439/5b68ce48-558e-11e5-82bd-e9987802c27b.png)

Next, an open path with straight lines:

```js
var path1 = new Path({
    segments: [
        [0, 261],
        [177, 0],
        [197, 12],
        [300, 316]
    ],
    fullySelected: true,
    strokeWidth: 8,
    opacity: 0.25
});

var path2 = path1.clone();
var path3 = path1.clone();
var path4 = path1.clone();

path1.position = [200, 200];
path2.position = [550, 200];
path3.position = [200, 550];
path4.position = [550, 550];

path1.strokeColor = 'black';
path2.strokeColor = 'green';
path3.strokeColor = 'red';
path4.strokeColor = 'blue';

path2.smoothGeometric();
path3.smoothCatmullRom(0.5);
path4.smoothContinuous();
```

![lines](https://cloud.githubusercontent.com/assets/213275/9720459/89fbd98a-558e-11e5-9df1-4db86ce91679.png)

And lastly, the same example with different values for tension in the Catmull-Rom algorithm:

```js
var path1 = new Path({
    segments: [
        [0, 261],
        [177, 0],
        [197, 12],
        [300, 316]
    ],
    fullySelected: true,
    strokeWidth: 8,
    opacity: 0.25
});

var path2 = path1.clone();
var path3 = path1.clone();
var path4 = path1.clone();

path1.position = [200, 200];
path2.position = [550, 200];
path3.position = [200, 550];
path4.position = [550, 550];

path1.strokeColor = 'black';
path2.strokeColor = 'green';
path3.strokeColor = 'red';
path4.strokeColor = 'blue';

path2.smoothCatmullRom(0.0);
path3.smoothCatmullRom(0.5);
path4.smoothCatmullRom(1.0);
```

![catmull-rom](https://cloud.githubusercontent.com/assets/213275/9720469/aee9d558-558e-11e5-99b4-7eb58a1abb3a.png)

**Comment by lehni** [comment] 2015-09-07 16:35
@puckey as always, would be curious to hear your thoughts on the API style, as outlined here https://github.com/paperjs/paper.js/issues/338#issuecomment-138244902...

**Comment by lehni** [comment] 2015-09-07 19:01
@christophknoth and here how the different versions now behave in your tests from 2013.

black = original path
orange = `smoothCatmullRom(0.5);`
green = `smoothGeometric(0.4);`
red = `smoothContinuous();`
blue = `smooth(); // the old smooth`

![comparison](https://cloud.githubusercontent.com/assets/213275/9721876/92a16acc-55a3-11e5-8189-2f133c5ae2be.png)

**Comment by puckey** [comment] 2015-09-08 08:19
Good stuff!

I think it would be best to use a single object literal as argument and forego the string argument. It feels a little too much for something as specific as this. An object literal will allow for less docs (seeing as you will want to document each type of smoothing separately, since there are different properties involved for customizing)

I would go for 'catmull-rom' for the type, I think.. seeing as googling 'catmull' returns Catmull-Clark as the first related-to-algorithms result (at least, for me)

**Comment by lehni** [comment] 2015-09-08 21:21
@puckey and you prefer this over separate method names? We could also go this route:

```js
path.smoothCatmullRom(0.5, 10, 15); // Smooths with tension = 0.5, from segment 10 - 15)
```

VS

```js
path.smooth({
    type: 'catmull-rom',
    tension: 0.5,
    from: 10,
    to: 15
});
```

Note that the term `tension` is sort of wrong in the context of Catmull Rom. The literature speaks of knot parameterization, defined by `α, 0 <= α <= 1`...

**Comment by puckey** [comment] 2015-09-09 09:34
Hmm.. yeah if the parameters are really diverse it might be a better idea to use separate method names.

**Comment by lehni** [comment] 2015-09-11 09:17
Actually, the only variation is this tension / alpha factor, which some approaches have, and some don't. So why don't we name it `factor`, a broad enough term, and use the object literal approach?

```js
path.smooth({
    type: 'catmull-rom',
    factor: 0.5,
    from: 10,
    to: 15
});
`

**Comment by puckey** [comment] 2015-09-11 09:42
Yes, great.
path.smooth() for most cases and configurable through object literal.

**Comment by christophknoth** [comment] 2015-09-13 11:41
I worked on an idea for a smoothed line (in purple) that never overlaps with was not overlapping before when it gets smoothed. But it turned out to be not so good for animation so it is not really handy for paperjs. But I guess all the test lines that I used to optimize it could be quite handy to see the subtle differences the other smooth functions have.

http://christoph-knoth.com/paperjs-smooth-08/ 

Things I found while playing with it:

smoothGeometric(0.55) can make a square into a circle, but no matter how much I increase catmull it will not go very round. So catmull will always be closer to the original straight line and a bit more blocky: 

<img width="875" alt="screenshot 2015-09-11 16 19 37" src="https://cloud.githubusercontent.com/assets/282518/9817068/1c84e1ec-58a1-11e5-8403-488e50f82ddc.png">

Maybe the parameters of catmull should be limited between 0 and 1 if not they can go really crazy in a kind of unpredictable way (somewhere above 1.6). Geometric does not need to be limited I guess because it is quite continuous in the increase and it could be quite nice to play with it. This is 1.8 for both:

<img width="1095" alt="screenshot 2015-09-11 16 29 13" src="https://cloud.githubusercontent.com/assets/282518/9817292/406a79fe-58a2-11e5-9b2e-7f0471c689a3.png">


The continuous still has the problem that the old smooth had, that when two very close points follow a long distance it creates a knot. But as @lehni said the symmetric curves look much better: 

<img width="880" alt="screenshot 2015-09-11 16 22 40" src="https://cloud.githubusercontent.com/assets/282518/9817122/592c9a7c-58a1-11e5-9961-872af9ffebed.png">

So all in all:

Use restrict when you want to never have overlaps that were not there before and if it does not need to be fast.
Use catmullrom when it should be closest to the original line.
Use geometric when you want to be able to change the curviness a lot.
Use continuous for the most smooth result and points are well distributed and it should behave like in the old paper.js.

**Comment by nicholaswmin** [comment] 2015-09-13 15:00
@christophknoth 

> Maybe the parameters of catmull should be limited between 0 and 1

Catmull-Rom's alpha parameter is knot parameterisation, not tension. The values are intended to be between 0 and 1 - Anything outside that range will cause unexpected behaviour.

- When `alpha = 0`, the resulting curve is the standard Catmull-Rom spline (uniform Catmull-Rom spline).
- When `alpha=0.5`, the resulting curve is the centripetal Catmull-Rom spline.
- When `alpha = 1`, the product is a chordal Catmull-Rom spline.

AFAIK, Catmull-Rom splines are intended to fit a bit more snug on the control points(this is especially true for the centripetal variation), therefore creating a circle out of a rectangle should prove a tad hard, if not impossible.

**Comment by christophknoth** [comment] 2015-09-13 15:03
@nicholaswmin then please remove my "maybe" :)

**Comment by nicholaswmin** [comment] 2015-10-25 13:58
Is this going to get merged eventually?

**Comment by lehni** [comment] 2015-10-25 15:25
Oh yes, forgot about this one. Will include it in the next release!

**Comment by lehni** [comment] 2015-10-25 21:53
@christophknoth the square-to-circle "miracle" is linked to KAPPA, which happens to be [0.5522847498307936](http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfGT8/OK83NS9XLy0zX8SnNTizKTE3P0vB0DAhw1rYHKkopSE7ML8jPzSoqVrKJjawE=):
http://whizkidtech.redprince.net/bezier/circle/
http://www.whizkidtech.redprince.net/bezier/circle/kappa/

**Comment by Syndesi** [comment] 2015-11-19 23:05
Wow, your work is so cool, I can't believe it! :D

**Comment by lehni** [comment] 2016-01-06 15:33
Finally tackling this for release...

I'm still torn about the API:

```js
path2.smooth({ type: 'geometric' });
path3.smooth({ type: 'catmull-rom', factor: 0.5 });
path4.smooth({ type: 'continuous', from: 10, to: 15 });
```
VS:
```js
path2.smoothGeometric();
path3.smoothCatmullRom(0.5);
path4.smoothContinuous({ from: 10, to: 15 });
```

The first approach has a couple of benefits internally, e.g. the reuse of code to handle ranges, but this could be shared through a private method among the public methods of the second approach as well.

The second approach looks more readable, and is shorter...

What do you think?

**Comment by timuric** [comment] 2016-01-06 15:36
Second approach looks more readable to me, and also supports benefits of autocomplete.

**Comment by lehni** [comment] 2016-01-06 15:54
Yes it is more readable for sure, but it results in messier / more code internally, and it offers less flexibility in future changes / additions. Regarding auto-complete: how many times a day do you need to write code that smooths a path? : )

**Comment by timuric** [comment] 2016-01-06 16:17
Agree it is not something that is written frequently and thats why it can be hard to remember available options or proper spelling. For example I could imagine that after a month I would be hesitant between "catmull-rom" or "catmull" or even just forget the name catmull. However it is not a big deal to use factory pattern if it offers better flexibility to the maintainers. Another benefit of the factory API is that it would result in more succinct documentation.

**Comment by lehni** [comment] 2016-01-06 16:55
Yes, I agree... Another question:

    { from: 0, to: 2 }

or

    { start: 0, end: 2 }

And as so often in C,Java&Co.-land, start is inclusive while end is exclusive. But when passing segments instead of indices, you'd expect them to be inclusive both I think:

    { start: path.segments[0], end: path.segments[3] }

**Comment by puckey** [comment] 2016-01-06 17:04
If I were to put it into a sentence, I would say: 'smooth this path from the first segment to the second'

ThereforeI would prefer: { from: 0, to: 2 }

**Comment by lehni** [comment] 2016-01-06 17:16
Should `to` always be inclusive in this case? I tend to think yes...

Perhaps as a convention, we can use the `start, end` naming in the library when `end` is exclusive, and `from, to` when `to` is inclusive?

**Comment by bmacnaughton** [comment] 2016-01-06 17:40
You could do {from: 0, through: 2} or {from: 0, thru: 2}. That's
unambiguous. But the first is long and the second is not standard spelling
though it's used a lot.

I agree that if you're specifying segments that I'd expect you to use the
segments I provide.

**Comment by timuric** [comment] 2016-01-06 17:55
I would expect it to be the consistent with `removeSegments(from[, to])`

**Comment by lehni** [comment] 2016-01-06 18:12
And another question about ranges. Starting with this square path:

![screen shot 2016-01-06 at 18 59 59](https://cloud.githubusercontent.com/assets/213275/12150073/bc10f298-b4a7-11e5-8520-d80b0609e8f1.png)

If I call `path.segments[1].smooth()` I get this:

![screen shot 2016-01-06 at 19 03 54](https://cloud.githubusercontent.com/assets/213275/12150134/4553a0a0-b4a8-11e5-8797-d5efabfb0e1d.png)

But if I work with ranges on `path` instead, I am not sure yet how to handle the segments at the beginning / end of the range:

```js
path.smooth({ type: 'catmull-rom', from: path.segments[0], to: path.segments[2] }); // inclusive
```

Two options:

1. Call `smooth()` on each of the segments in the range just like in a simple for-loop:

![screen shot 2016-01-06 at 19 06 14](https://cloud.githubusercontent.com/assets/213275/12150181/9524a6ba-b4a8-11e5-914e-b9c308832587.png)

You can see how this results in a shape that reaches beyond the specified range because `handleIn` in the first segment also gets calculated based on the previous segment, as well as `handleOut` in the last segment, based on the next segment.

But one can argue that when specifying a range, the effects of smoothing should not go beyond this range. Hence:

2. Perform the same as 1. but exclude the handles at the beginning and end:

![screen shot 2016-01-06 at 19 11 02](https://cloud.githubusercontent.com/assets/213275/12150289/449673d0-b4a9-11e5-899d-bb2635483d3b.png)

But for a range involving 3 segments, this turns out to be the same as just calling `smooth()` on the middle segment. I'm not really happy with either outcome yet... Thoughts?

**Comment by lehni** [comment] 2016-01-06 21:32
I went with option 3. and after a lot of testing, I quite how it behaves it. You can test it on the https://github.com/paperjs/paper.js/tree/new-smooth branch, it now works for all smoothing methods.

**Comment by lehni** [comment] 2016-01-07 10:35
Regarding the ranges and wether `to` should be exclusive or inclusive. While I agree that it's weird if the behavior here is different than `removeSegments()`, I also find it rather unintuitive to work in that way in use cases where I would like to smooth a part of a path. I am still torn about this open question.

I did rename the parameters `(from, to)` to `(start, end)` in all the methods that use the "end-exclusive" convention (only two public methods: `removeSegments()` and `removeChildren()`.

We could offer both conventions in the object literal now: `{ from: to: }` being inclusive, and `{ start: end: }` following the "end-exclusive" convention... That wouldn't be too tricky to implement.

**Comment by lehni** [comment] 2016-01-11 18:23
So here's the decision regarding the range:

- `removeChildren()` and `removeSegments()` have their parameters named `(start, end)`, indicating it's using the "end-exclusive" convention.
- `smooth()` can receive `from` and `to` properties, similar to that `Path.Line()` and `Path.Rectangle()` constructor, and just like there, these properties describe a geometric situation, not an abstract range of objects in an array. And I think hence it is better if both are then inclusive.

**Comment by nicholaswmin** [comment] 2016-01-11 18:49
Do we expect that the new smooth methods can smooth a path in real-time?

`range` options look to me like something that can be used to smooth only the final part of the path instead of smoothing everything continuously.

**Comment by lehni** [comment] 2016-01-11 18:57
That's a good question. Yes you can use it to smooth continuously. You'd just keep calling it with the range that you just added (plus depending of the smooth method used, a few more segments, to create smooth connections).

And since I am supporting negative values to then be offset from the end rather than the beginning, it would be super easy to do so:

```js
path.smooth{{ from: -2, to: -1 });  // smooths the two last segments of a path.
```

You can also do this, of course:
```js
path.lastSegment.smooth();
```

**Comment by lehni** [comment] 2016-01-11 19:27
I have now merged the new smooth() functions into `develop` in 20f90bbee25147c3e923bd80ccfdbab7e7ef65f4. I think we're done!

**Comment by lehni** [comment] 2016-01-11 19:28
Reopening, as I still need to work on documentation : /

**Closed** 2016-01-15 17:14 UTC
Labels: cat: path-processing, pri: important, type: feature
