### ISSUE TITLE
Path Boolean: Path.Unite() error in method propagateWinding: "Cannot read property 'getLength' of null"

### ISSUE THREAD

**Issue by ghenania** [paperjs/paper.js#1091] opened 2016-06-22 09:36 UTC
[Here] (http://sketch.paperjs.org/#S/ZVVNbxw3DP0rwl7sApIgUqQkJuip5wAGeqx72Ew2iOvp2lhvWqBF/3sfZ2fs2MYexKH4/fi0/+6O+z8Puw+7X+8P5+nbLu6mhy/+/Xh6+OMwnfM0H/an658+3h5vj3/tT+GGw8/hePg73OzP365vd5/YKBdtg6I0zr30ZlPLxFY0JuIsoiShZWU1iYk7JFYNqWSuphSTlDykqs0utS7dYholl26lz4OzjtpgRgivRtbmLrmSqcQysWaywRRLEM2NmQdylCwspf+gcol656ngevUJz4aXe7cM6bWPS7MXbb1Ji2WulG2Mjk5Qjo2Cbkcu0iuCkKIRQm8sqH6wtyvZWh81oLVerNCLClMyLUvpBPuiVSKhQ8a4UFhjGRGmykUnxhxbZYtEWUiIA+oQrqXFOvLoRdl9ClWx2CjXWgeh7gJRMNxYrcGxcw+fmHquJmRRMEg26zKlCrvGNUIQaWohtVxGN0AB69ZbDWlkaoMb+vQypfIMCBHUIsbYgfPEwH1QR9lkKD9Ixpf0iPGRAg+c3PCNAAQIxqUYrf1Si8iYkncxGLuzCr4opQrzoqntolAGGpswbT5+qvVw8aC4nmFzWE+kxVpJ8RXyvH3g50EANi1RXXAv0XbJ64Irmg8zrcK0mcbNZTONm8tmGtcTqdvIlYdxBDAYLXFF6lGLr1yBAgaBcsNUlkxdESmg3L6MHhio2gRPfPuuZ2ZqFgbYJILqFT1iD4KDVNkXFfkqi03Jt7KRAp7SMDBHFCWJAB/WgbVLz4toWbDcDpAYUgJ4lIsFkDKwLYpt1Eu9BBUgoeIMISdBZt9CqFrmbuorVUdnm0A75T4itqRUxCZnO6LUzI1Akc1htf/ndufPzvLo0JtHR0ZWqoo5T+mFRolqNhv6TKO08KiAiBuR0nsmpYVKHaA9Uym955JTSQ0oL1QaJpMHwAq1uIUM7t8qRrVFDJt73AK+MDlt/i9UTksAvBsvXE5LBNJ6ITPa8oGuFaRXL08Ft4K/LmWghx+eHn9WO5Hn3HTrbP13Q/nr3Tz/8jA/nDDlq8/z98PVx0X/dD493B/e3/Brj9Phy6p+47BeXDB8hAYxvx/vzofrG/b0j28z76f7q0X/LvN643fn0/74NO8RpWrBYMvWye0Rf1+fT4f9/ePD3fH8tPvw2+///Q8=)  is an example where this error could occur.

The error description is:
``` 
length = curve.getLength();
                                ^
TypeError: Cannot read property 'getLength' of null
    at propagateWinding (/PATH/TO/paper.js/dist/paper-full.js:9729:19)
    at computeBoolean (/PATH/TO/paper.js/dist/paper-full.js:9512:5)
    at Path.unite (/PATH/TO/paper.js/dist/paper-full.js:9886:11) 
```

**NOTE that this error doesn't occur in Sketch but only with the last code of #Develop branch.**

**Comment by lehni** [comment] 2016-07-08 23:44
Could you tell me with which version / commit you're observing this? I can't reproduce it locally, and I've tried a few stages through the last couple of week on the develop branch now...

**Comment by ghenania** [comment] 2016-07-12 08:13
I was on `develop`, commit `f04dd14: Remove jsdom legacy code`.

**Comment by lehni** [comment] 2016-07-12 11:03
@ghenania did you try with `0.10.2`? Is it still happening there?

**Comment by lehni** [comment] 2016-07-13 07:45
Hmm, now I'm on that exact commit and I still can't see the error. What am I missing?

**Comment by ghenania** [comment] 2016-07-13 12:24
I tried to reproduced the issue with 0.10.2 (branch `prebuilt/module`) but I get this error:

```
/PATH/TO/node_modules/paper/dist/paper-full.js:9831
                                        || !seg._visited && !nextSeg._visited
                                                                    ^

TypeError: Cannot read property '_visited' of null
 at findBestIntersection (/Users/Mohamed/Documents/Developpement/Fontself/opentype.js/node_modules/paper/dist/paper-full.js:9831:34)

```

**Comment by lehni** [comment] 2016-07-13 12:38
You get this with the above test case?

**Comment by lehni** [comment] 2016-07-13 12:40
If you open the sketch above, it will run on 0.10.2. Do you get an error then? I don't.

**Comment by ghenania** [comment] 2016-07-13 13:55
Sorry I was not clear !
I tried to reproduced the issue but I get the error `Cannot read property '_visited' of null` before I could get this issue we were talking about in this bug.

Here are the paths I get the error with. 

````
var P1 = new Path("M339.2136,172.59643c0,-25.19821 -20.42407,-45.62 -45.61772,-45.62c25.19184,0.00123 45.61421,20.42132 45.61544,45.61772c0,0.00076 0,0.00152 0,0.00228c0,-0.00076 0,-0.00152 0,-0.00228l0,277.52699c0.00228,25.19821 -20.42407,45.62228 -45.61772,45.62228c-25.19821,0 -45.62228,-20.42636 -45.62228,-45.62228l0,-277.52699c0.00001,-0.13765 0.00062,-0.27515 0.00185,-0.41251c-0.11756,-55.97169 -24.07077,-80.93936 -77.62428,-80.93936c-3.12497,0 -6.17695,-0.31478 -9.124,-0.9124c20.82325,-4.22669 36.496,-22.63664 36.496,-44.70532c0,-22.07096 -15.67275,-40.48319 -36.496,-44.70988c2.94705,-0.59762 5.99903,-0.9124 9.124,-0.9124c104.1573,-0.00228 168.86471,66.13303 168.86471,172.59415z M48.53208,145.15828c-11.09706,-0.00228 -22.22606,-4.02596 -31.00335,-12.16685c-18.47838,-17.12803 -19.57098,-45.9918 -2.44295,-64.4679c42.15288,-45.46945 88.24733,-68.52352 137.01283,-68.52352c3.12497,0 6.17695,0.31478 9.124,0.9124c-20.82553,4.22669 -36.49828,22.63664 -36.49828,44.70988c0,22.06868 15.67275,40.47863 36.49828,44.70532c-2.94933,0.59762 -5.99903,0.9124 -9.124,0.9124c-22.65033,0 -45.57894,12.858 -70.10197,39.31075c-8.98942,9.69881 -21.20646,14.60752 -33.46455,14.60752z M247.97132,172.59643c0,-0.00076 0,-0.00152 0,-0.00228c0,0.00076 0,0.00152 0,0.00228z M293.5936,126.97643c0.00076,0 0.00152,0 0.00228,0c-0.00076,0 -0.00152,0 -0.00228,0z");
var P2 = new Path("M161.22489,90.3276c-20.82553,-4.22669 -36.49828,-22.63664 -36.49828,-44.70532c0,-22.07096 15.67275,-40.48319 36.49828,-44.70988c20.82325,4.22669 36.496,22.63664 36.496,44.70988c0,22.06868 -15.67275,40.47863 -36.496,44.70532z");
````

I'm using  `prebuilt/module` branch in my project where this error occurs.
But I can't reproduce it in sketch.

Extracted info from paper `package.json` file :
````
  "_id": "paper@0.10.2",
  "_shasum": "641eaff1dcc79c5aa27d6303e901e618a003de8a",
  "_from": "git://github.com/paperjs/paper.js.git#prebuilt/module",
  "_resolved": "git://github.com/paperjs/paper.js.git#de56e28467dde747a99e21d1ff9349f27bc7902f"

```

**Comment by lehni** [comment] 2016-07-13 14:09
I just tested your new paths with the specific version you posted (git://github.com/paperjs/paper.js.git#de56e28467dde747a99e21d1ff9349f27bc7902f), and I'm again not seeing any problems! We're not getting anywhere...

Are you actually testing with the paths  that your code statements generate, or are you outputting them from internally calculated paths? Please test with the ones you post also, as there may be an issue of precision here, since coordinates get rounded when the string path-data is generated.

And if the rounding is indeed the problem, there is a way to generate higher precision strings. you can call: `path.getPathData(null, 16)` and it will use the highest precision available.

**Comment by lehni** [comment] 2016-07-14 06:50
@ghenania sent me [this failing sketch](http://sketch.paperjs.org/#S/pVfbbuM2EP0VwX2wjZVoXkRRSnb3ZVssCnSLBQL0Jc6DItOOGkUyJOXWIP/eGZK6xcpugSqxJXKGw5kzZ0b0y6JM7/TibHFxq9vsZuEvsmqH42Nd/a2zlmSFTuvV+nxbbsuHtPaah4P3yVt+xPuDrpu8Kj9tF4yw7cJ7uivKBkY3bXs822weHx/JoyBVfdhwSukGlnRKZ09FXt7OqrIkSTZGDMq6TK8LHVyn2e2hru7LHSwp9aNH4Q8UCY3ocEUeZyGhlA1TYrv4/PHg7fOiwJVVqXHimLY3Hpr6xinq++Y7CxgjNFQ+9QJO/ZgkMjRPVqmgPlOCJEmcwZPR9FBHOLnXa2ZGKsEOTAWoI81TbyewhpIssNvbjSPP6qKi2Rc+/wAGzvlfuIzDTKL/GwxgHEYSEypj34VfBMqO6ZuQnC/BxBn6/8PhtJBuR2Mw6Fe8BTKzAY/2kyf7eRhOTMUQDiUKrcHiUCRglZJYKd+AJzxGBJN2ECOgLE5MPiFOSoSygxgHUtnnMah6x7jcz4LquOG8+CmUGXV5lA5HTKMVF3BDZCD+YAJAMEFg4NrYQ7kXPFI/SntoExGMchAg1FNehZ2jk/wDU1SkDLYsFgZbEUmDE4dnGVrMFDoeMge6gTaGVJgRhMEIl06mfpB9CxOa9p1nKI18A5QFe8J4xa/3YTgbekj7sDmdJ3rYBTpCos9MR7lxHYx5bg3MJoRBjOE7CUmAcUhcLG+RMSBuzBAXAWiyBOjrBwlhQnUDuKHiQJ0hVZ33A/2FJMKEGDHbNnhMmFL9MFKn5RxOwD0tZeH1GEWQbgEehBwoARmiEeEJFA4EFcXKjMHXMRJ7oShn/6UjnXaFnxaQHBeQqR8HwztpwriBldLQPQpjH7CNEmC7hdohjTQWamgQsZJdg7CNZK5DZHyehPYNBNuqif+qz6LZNLFB2ucpUU1abBq6kVVziQwEdELOQShJhAYjsD1NN8JCkw4W5ffZDjpsHFdsGUDEkTAIRcz4pKCFGohkR0d4yUCmTbOMQBdiRNzDCIHrRpYM4YQMaRqx9D0yqGjoU53HM4R4r2blTM3i64DF9nUQ+t3LgMuuY2H1JdDSgMXMcxFi8fUDFy31p69fPqTmTTvScSzm3xVMWSZwNZPgYJrhns8+HVFmyphO1ZHmLeVN1Q5MmZZ90Ne97bqTJDEZcTEKYXOADxzMPi/hhNed+fK7Y1W3F399XYHE91700zEtdxc36VE3Z219r30vPR6L529pW+dPZubVnhA7C2nW5g/6j/RZ16TJ0kKvOOHQCj13o/BvV2w23lfdegbKrIKNS122jT1r4mQDp805qwfd/t7qu2b1khVp0/wJp9iz5XdYsDSudMthNZ4Xv6BlOD6iwurS2L2kV1fWhX1Vr1A/B2V2DrePdmdS6PLQ3sDMhw/rbfmyLT24sqpsqkKTojqscjSAk+ZkfH/tdrT28ysnzPcrJyN589vdsX1erddop83Lez2ycKz1g1s+LLXryhbO2oBB05kCC84hvNr6eTzEa+QLuS/zVvcrzwfF1+ExS+H8v9J1vX5raRwxys/fFy8xjO/MoW7Q3m63i6X3wQSHWcPJX9M2XZX3ReF7LFqDcIla6/Plz23zOdsdvCfmf2z9utbp7Ska7qaLRg8yYz/d7b7c5MVuDOWr4T1Ksci+VEVV4w+kWu+Whl3wk8rsc6wgic3i7PLq9V8=) by email.

**Comment by lehni** [comment] 2016-07-14 06:55
@ghenania but in this example, the error is: `Cannot read property '_visited' of null`, while your bug report speaks of `Cannot read property 'getLength' of null`. So it's not actually the same issue?

**Comment by lehni** [comment] 2016-07-14 07:16
@ghenania So 083a2c6e0df5736184817a6770a2213f36e224bb fixes this exception, but I don't think the resulting path is what you're looking for, since there are some extra touching lines that don't get fully merged. It may be that our overlap detecting code is faulty, or that the paths aren't fully overlapping. Before I zoom in and analyze what's really the case: Could you shed some light as to how these paths are created?

**Comment by lehni** [comment] 2016-07-19 14:39
@ghenania I am working on the test-case you provided by email.

But please note that this data is **extremely** tricky for boolean operations, and even Adobe Illustrator is having a hard time with the data, for this reason:

You are trying to unite different shapes that only have touching bezier curves, no actual overlapping areas. This works well with straight lines, but once curves are involved, it gets tricky. To illustrate. Here your shapes, moved apart a little to show the curves that normally touch:

![screen shot 2016-07-19 at 16 34 14](https://cloud.githubusercontent.com/assets/213275/16953822/c5d12918-4dce-11e6-909c-b428fe6fb529.png)

It would be much easier to process, and probably produce much more reliable results, if those would really overlap and produce decent intersections:

![screen shot 2016-07-19 at 16 33 29](https://cloud.githubusercontent.com/assets/213275/16953848/dcb78956-4dce-11e6-80cc-ebd7b80c9b59.png)

What's more, it looks like your paths aren't *exactly* in the same places, so while some of the curves touch, others are separate..

Here what Adobe Illustrator makes out of that:

![screen shot 2016-07-19 at 16 36 45](https://cloud.githubusercontent.com/assets/213275/16953875/02ff1c5a-4dcf-11e6-9d3f-10f62b8d2ac2.png)

And here the result of a local version that sort of works:

![screen shot 2016-07-19 at 16 38 46](https://cloud.githubusercontent.com/assets/213275/16953948/4a2eac80-4dcf-11e6-941b-82311fdb6543.png)

It looks like we're going to be doing better : ) But this is a hell of a tricky area. I'd recommend staying clear of such paths if you can.

**Comment by lehni** [comment] 2016-07-19 14:42
[Here a simplified test-case](http://sketch.paperjs.org/#S/tVhLb9s4EP4rhC9OUIng8M1kc+ppDwUW2GPSg6uosJHEDlzXBRLkv+9QMinKolzZ6OqQBzWcF7/5Zqj32XrxUs9uZv8+1btqOStm1ebR/79fbMnjYrcgd+T+YU3wmX9xQLnk3AJrH15IRTVPVkDthdPUOjBgXfuYihVcUXDKcXVYs5qUnFHJtVAq7h2ok5KUzRrrHshIVWVjwHJmgpgp2HAvU0VrVjIjQxB5saGRfdmEZp0UFkMamATSqAbjuAuhD/UAmWINqka70FJ2ulizFYwB16XsOBxQAwOHjKUrb2xePKwfdvMvnAuqDePOHt6JQlpLQejOG7UswVjKVCqWybk8mfPkqJWdnHQW0JMY4iqmWuQwk1GdwUzIcHCqcX+i91MRM5RbguBUCp9JjK3MOpHLzTTYDpcqRlE4QRbDSPRoSn2YF6e0w5SiQjstR7BEtXOiQ7ZwFaCTIFSkDKcwDZx6rajosKixnHw02mL+Do+QFj2n+FpBzCGXjSBYLm1Ywr8rXJQCgAUzjvPCy4FkwRltHAiCgrYpvbBbyCKjkGAo6AnEAmBW5eTeQmIGZZ7Jz9lcdlFdRQJLKEaacQbrKRyHf29tOaCdfQaf5QGgLJjUiHObA+if7BhvJ/gvtjmEalesmQBjErGz6bAqyaDFZBl+2knBEk+Dam0Uxz5KJRjJA/gRN54tEKuCKx1O0doG1EwqDS55iI/KGBbKyUELfoWYT3zg/kCwmLDNxPyJtpywTFQq6eGP1WJi2TrrWsljnZgSLCjDY6UA5AUvIcRxIuw11OOccCudjoOJbqFvtdDR7hjwe0DKSEVsNUBK3kAKrVwpnNlRexA7gae+lTxou4Z66ciC7WxqS+3ObsrRJbWqsRSchVABh/4ClglRcUmVA6k7ckWIaWttPHMcnIiUVPgcJwSH3lgJ0nVZz0l5t5hEQ0G9GuHQ4YSZ5dCJx5VtlxYD41o1jQGEoyAF5qsotaTcgOlaZu8tKKxCbk6OVD23Ly2AwfAqzanRKuk3JyarvgVWgMCJ1B88ptIZqiQDzuMerDIqtTLCxjMtOTdUWDzEGDSKSRxroTtVfqoxDJv1WSPc/9Sum5Ht8i69Z8sDwoJbGPn5lRz2jlZ0b8kjUFKjuYp8iw0RHDXISTZk3HOwxBaj8DYZVjBjR7WJLJ6pTd/F/DQXSsFqPTLrYRNzypoQqfRVlZv1jqZMAb8Z9TyylI0Uq1qwaZfcn9NrZOzLepRB/NUv9tp838vIDdsKVxGh/VKOTSAotFmxoY2GU0osD6W4txSPVOESaGNkpB9MeI6TPAjBcB5GbuaqYWYCBtNxMdsLM1IjnRBRaKxiokWfUqglkKfPOsJPciVFCzvvX6SqQ7LxPgWd5Qq4Q8T6DyAFYOg4rMVkYnF4ClJgu1qTBTBF8SJikKwzb1uCEmjiLb1dcYu0FHHXm1gHaTyXoP74VJEQ1AUfQvw0ihkJwQI43/Qwx77iY5TNvat3M2xMDMfO7NSJKNBgbdcF/HVPa2Ei7zT+HhAQWcbXC4LXQu7dMTYg+QyWfv3KddlhGnJiHdcwi7eUPtdYvDVYc0btZ3pxVizXQdryzzDZNCIbM3PEY1OnigyLjTSlYxIbG40yhDxxosud2sP66y0e3Np/Yt3WP8gdWde/yOfNy+vm5/rxn8VuefVOvq+enz9vnjfbGzL/9ryonubk47rZ9n2zJVd+7wp3slv89RcBwN+fPl2T9/ZbrX/9iopQwuv7e1e/0GpbL3b1lf+oe7/6en1LWlEvRrf1y2ZfX3kDcS16gErm2/pxfpvo3tZ7XEbvD4ttHPiT/lyv0IrXELWhcGrho41+Vf+iVb3e1VtS3iFSmtVZMfuGfj69blbr3Y/Zzf3Xj/8A) for testing

**Closed** 2016-09-24 18:54 UTC
Labels: cat: boolean-operations, type: bug
