### ISSUE TITLE
Scaling rasters down creates very poor quality

### ISSUE THREAD

**Issue by haoyangnz** [paperjs/paper.js#707] opened 2015-06-08 06:29 UTC
Scaling rasters down to say, 0.2, makes the result very poor. This is probably due to a naive resampling algorithm (should be bicubic).

If there's no plan enhancing this, may I submit a pull request?

**Comment by jardakotesovec** [comment] 2015-06-08 06:33
Afaik quality of scaling generally depends on browser canvas implementation. Only way around it to use better resampling implemented in js - like this [project](https://github.com/nodeca/pica).

**Comment by HaoyangFeng** [comment] 2015-06-08 06:49
Sure. Do you think we can have some js re sampling built in with option switch on the scale API?

**Comment by lehni** [comment] 2015-06-08 16:03
Sounds like it's related to #615 ?

**Comment by HaoyangFeng** [comment] 2015-06-09 01:43
@lehni Yes. Do you want me to close this issue? Also, is there any plan on #615?

**Comment by lehni** [comment] 2015-06-09 09:08
No let's keep it open. I made a suggestion in #615 but haven't heard back, what do you think about it?

**Comment by HaoyangFeng** [comment] 2015-06-09 11:41
I don't fully understand what you've suggested in #615.
What would the following example look like using what you suggested?
```
var raster = new Raster(url);
raster.scale(0.1);
```
Replace `raster.scale(0.1)` to `raster.resize(0.1)` or something else?

**Comment by sapics** [comment] 2015-08-04 23:43
:+1: `raster.resize(0.1)`

**Comment by haoyangnz** [comment] 2015-08-04 23:45
any update on this?

**Comment by lehni** [comment] 2016-01-08 21:46
Closing as it is a duplicate of #615

**Closed by lehni** 2016-01-08 21:46 UTC
Labels: cat: canvas-rendering, type: feature
