### ISSUE TITLE
getItems return erroneous objects for selected items query

### ISSUE THREAD

**Issue by ceremcem** [paperjs/paper.js#1587] opened 2018-10-29 20:18 UTC
> Originally asked in SO: https://stackoverflow.com/q/53031869/1952991

According to my understanding, `project.getItems({selected: true})` returns wrong results: I'm selecting a curve, it returns the parent Path: [Sketch](http://sketch.paperjs.org/#S/nVVNb9swDP0rhBE0Npq6afYFxCt26HbYYcOADtih6UGxmViNIgWSXDco8t9HybLjtE1XLIBtSXyPfKJI5TGSbI3RNLpeoc3LaBTlqnDze6ahVnrFtKpkAZewYMLgTM+ke5x1vRVcIlkk1vCL2TL2A8WljS/G4xHQK0kyB2+gqbFarfBKCaWJNtRYDJ9Z//DClmS9GLexgpkVRS/ApAtwHPLRQT4FyPk5GBSYW1BSbMGW3EBe6XuEOdoaUQKbK5ox2uwchaoJvlyjtOZogHddADiKeT8hzORDEOEeU/KFbbMWkuW2kgBJtKpmujAwV9aq9Znmy9L2c+7J3y2us86Vm7njqWRuuZIxp/kIChSWJY8OBeCYfDCCB3o0LugtUNJ7O8gagKk5HT54brpEeyWYMT+pMGLaW3CSM4MwvHIpG06bJYAFnWTMBxR/3DilUexC0PfGewtZvBhBfzq5TVKCL22ZkTL47LkZnJ7yQRfQ/R6cI+fvhg9us/56unG5g9PLZqudbdcO5hrZKutrdzX6NultHq5DCVAa3iR3e0Tu9qncN6gNsfeCvaiX3bywV4c75L7KKnDBKmGfBjPc1dQTphe9y9q6bCuPGuuHqgx+VbWM8Z60J11q2hb3HYgH14kzl9x1xIZtUKcbre4IlNLabzS28dTsO+nULWJHOTlxzFSonDkBSe8kIDT35QEi9YvPUH1dVlcHgN4d+GXffrHnjZqFBKYgKyGeHSrSFkkr9MWGBjgoG2jvmiA3zF4A/IfSwPyX1vbbpp+q39FN/NiGnPqIuySlzvnG8jLurhw1v+vnPlfSKIGU9aU37S0HEp0MUrNXSthWZSevG/WdzqKzV3+zyNN29G/ma9wXj4mmN7e7vw==) 

Try clicking on a curve or a segment. Whole path will be moved. Then try changing the behavior by setting `var workaround = false` to `var workaround = true` to observe desired behavior. 

How can I get exactly what is really selected? 

## Current workaround 

I'm currently adding those objects into an array on selection and use those items instead of `project.getItems({selected: true})`.

**Comment by sasensi** [comment] 2018-11-04 11:43
As stated in my [SO answer](https://stackoverflow.com/a/53134346/7615922), I don't see this as a bug since curves and segments are not items.
I think the problem is more related to how selection is currently handled (see discussion in #1588).
I close this issue because the subject is already discussed in #1588.

**Closed by sasensi** 2018-11-04 11:43 UTC
