### ISSUE TITLE
The paper.project.exportSVG({asString:true}) exports only a part of the canvas.

### ISSUE THREAD

**Issue by hentrymartin** [paperjs/paper.js#1017] opened 2016-03-16 19:13 UTC
Consider that the canvas is of size 638_280(w_h), the exportSVG exports svg of 300px width and 150px of height.

**Comment by lehni** [comment] 2016-03-16 19:16
As with all bugs: Test case please so I can reproduce. Thanks.

**Comment by lehni** [comment] 2016-03-27 20:23
Could you please provide a test-case for this? If not then I'll have to close the bug.

**Comment by IncidiumGit** [comment] 2016-04-06 13:46
I'm just learning paper.js too and came across this problem. It is because the browser canvas defaults to a width of 300 and a height of 150. Override these values with your own width and height values in the canvas tag.

**Comment by lehni** [comment] 2017-03-09 22:07
Closing in lack of a test-case.

**Closed by lehni** 2017-03-09 22:07 UTC
Labels: cat: import-export, status: needs-example, type: bug
