### ISSUE TITLE
WebGL Shaders Question

### ISSUE THREAD

**Issue by m-2k** [paperjs/paper.js#917] opened 2016-01-20 14:12 UTC
Hi guys! You have a cool framework. But is it possible to use shaders to the canvas?

```js
> document.getElementById('viewbox').getContext('webgl');
< null
```
I want to use it for effects like this http://tympanus.net/Development/RainEffect/

**Comment by lehni** [comment] 2016-01-21 21:47
I have no clue, never done that... I wonder if you can get a webgl context on a same canvas that already has a 2d context? Probably not, right?

**Comment by lehni** [comment] 2016-01-22 09:48
I think you can either retrieve a `2d` context, or a `webgl` context from the same canvas, but not both. But in the linked example, the background image is used as a texture for the effect. So what you'll need to do is to use the paper.js canvas for that instead.

**Comment by lehni** [comment] 2016-01-22 09:55
And to confirm my assumption above: [Sketch](http://sketch.paperjs.org/#S/dY49D4JAEET/ymUrSMwVlBArNTR0lmJx3G1Ow7FLuBVJjP9dPioTLWfy3mReQKZDyOHcotgb7MCyW/JoBmUNjSaqvXJsHx2SaDugETwFXFJSw0bUkBY1rYZM2XEWtl57lAOT4LSwmfviyuoP98TGhw21TJED6sA+Wad/lGWVFvPtZn7W9nwniZBfru8P)

**Comment by lehni** [comment] 2016-01-22 14:38
Closing this as it's not a bug, nor anything we can change really. The possibilities are there, outside of paper.js, I believe. A demo would be nice though!

**Comment by m-2k** [comment] 2016-01-22 20:49
Thanks for the answer. Yes, it's not a bug, I was looking for a possible solution.
I'm not looking 3d renderer, then I would chose threejs. I want 'realistic' effects on the 2d objects.

Look at the links below. As I understand the use of shaders is only possible in conjunction WebGL renderer. And using WebGL be incorporated into the framework.

Fundamentals of understanding
http://stackoverflow.com/questions/12758915/canvas-2d-context-or-webgl-for-2d-game

The framework with the ability to use the WebGL or 2D renderer to choose from.
http://threejs.org/docs/#Reference/Renderers/CanvasRenderer

A series of articles to introduce to WebGL
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context

**Comment by lehni** [comment] 2016-01-22 23:00
I already pointed at a possible solution. There is nothing stopping you from using the Paper.js 2D canvas as a texture for other effects that take place in another WebGL canvas, just like the linked example that yo linked to is doing it. But this is not something we will incorporate directly into the framework, as it is not necessary to do so.

This doesn't need to happen in the same Canvas. Paper.js is using the 2D renderer for the time being. Building bezier rendering in WebGL is far from trivial.

**Closed by lehni** 2016-01-22 23:00 UTC
